src/components/pages/index.js

Closes https://educandu.atlassian.net/browse/EDU-103
This works in Chrome, Firefox and Safari on MacOS.

EDU-103 Do a full page refresh (without using the cache) when home page is loaded from cache

---

.github/workflows/ci.yml
package.json
src/components/default-page-template.js
src/components/document-import-table.js
src/components/document-import-table.less
src/components/document-import-table.yml
src/components/pages/import-batch-creation.js
src/components/pages/import-batch-creation.less
src/components/pages/import-batch-creation.yml
src/components/pages/import-batch-view.js
src/components/pages/import-batch-view.yml
src/components/pages/import-batches.js
src/components/pages/import-batches.less
src/components/pages/import-batches.yml
src/domain/schemas/import-schemas.js
src/domain/validation-middleware.js
src/resources/page-names.yml
src/resources/resources.json
src/server/import-controller.js
src/styles/main.less

Unfortunately it's not possible to prevent antd table from a full re-render on each checkbox click (there are a lot of issues on their GH repo, but they're not fixing it). I managed to cut down the lag maybe by 50% but it's still a very bad experience. The only remedies would be either paging or virtualizing the table.
Closes https://educandu.atlassian.net/browse/EDU-149

EDU-149 Improve UX on import pages

---

README.md
dev/cli.js
dev/docker-container.js
dev/helpers.js
dev/index.js
dev/jest.js
dev/load-balanced-node-process-group.js
dev/load-balancer.js
dev/maildev-container.js
dev/minio-container.js
dev/minio-helper.js
dev/mongo-container.js
dev/node-process.js
dev/process.js
gulpfile.js
package.json
test-app/index.js
yarn.lock

This PR does a little bit more than in the ticket (sorry, again). The idea is to extract the tasks that are the same in elmu, oma and educandu (and other packages), which is probably 95% reusable (and our gulpfiles a little bit lighter). For now I extracted some stuff to a folder called `dev`, we can continue to do this and then create an npm package out of this directory.
Closes https://educandu.atlassian.net/browse/EDU-186

EDU-186 Extract common dev tasks into reusable modules

---

src/components/pages/my-space.js
src/components/pages/my-space.less
src/components/pages/users.js
src/components/rooms-tab.less
src/styles/main.less
src/styles/tabs.less

Closes https://educandu.atlassian.net/browse/EDU-218
I made `my-space` look like `users`, but made `users` use the same component as `my-space` :)
How's that for compromise?
Looks like this:

EDU-218 Streamline tabs styling

---

migrations/automatic/educandu-2022-01-03-01-add-ear-training-tests-order.js
src/plugins/ear-training/constants.js
src/plugins/ear-training/display/ear-training-display.js
src/plugins/ear-training/ear-training.yml
src/plugins/ear-training/editing/ear-training-editor.js
src/plugins/ear-training/info.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-226
The migration script ran locally, over a prod db dump, in `5.36s` over 52 documents.

EDU-226 Toggle tests order in ear-training plugin

---

jest.config.js
src/components/pages/my-space.js
src/components/pages/my-space.less
src/components/pages/my-space.yml
src/components/pages/users.js
src/components/pages/users.yml
src/components/used-storage.js
src/components/used-storage.less
src/resources/common.yml
src/resources/resources.json
src/server/my-space-controller.js
src/styles/antd-overrides.less
src/styles/global-variables.less
src/styles/main.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-356
Decided to show this in a separate tab after all, due to the current form layout we have on the account tab.
_Example with < 95% occupied storage:_
_Example with >= 95% occupied storage:_

EDU-356 Show storage tab on MySpace page

---

src/components/icons/general/copy-to-clipboard-icon.js
src/components/icons/general/paste-from-clipboard-icon.js
src/components/plugin-selector-dialog.js
src/components/section-display.js

Closes https://educandu.atlassian.net/browse/EDU-528
Original icons:
Adjusted icons:

EDU-528 Replace clipboard icon

---

src/plugins/image-tiles/image-tiles-display.js
src/plugins/image-tiles/image-tiles.less

Closes https://educandu.atlassian.net/browse/EDU-563
On ELMU it the following tiles case:
- first tile has an internal document as the link and markdown formatting as the description
- second tile has no link
- third tile has en external link as the link
would be fixed and look like:

EDU-563 Keep image tile link style as set globally (do not overwrite)

---

src/components/pages/room.js
src/components/pages/room.less

Closes https://educandu.atlassian.net/browse/EDU-618
**Owner/collaborator views on desktop and mobile:**
**Member (non-collaborator) views on desktop and mobile:**

EDU-618 Rework lessons list styling to be responsive for all view cases

---

src/components/pages/search.js
src/domain/constants.js
src/services/document-service.js
src/services/document-service.spec.js
src/stores/document-store.js

https://educandu.atlassian.net/browse/EDU-756
This is a very naïve implementation making verified documents simply counting "3 matched tags more". For more sophisticated system we would have to also change the way we make tags count and open a bigger box. So maybe we can try and see how far we can get with this solution?

EDU-756 adjust search relevance logic

---

src/components/media-player/track-mixer.less

Closes https://educandu.atlassian.net/browse/EDU-788
...and looks like this (text intentionally made black):

EDU-788 Clip text in track mixer bars to bar size

---

src/api-clients/export-api-client.js
src/api-clients/import-api-client.js
src/components/pages/create-import.js
src/components/pages/create-import.less
src/components/pages/create-import.yml
src/domain/schemas/export-schemas.js
src/domain/schemas/import-schemas.js
src/resources/resources.json
src/server/export-controller.js
src/server/import-controller.js
src/services/batch-service.js
src/services/batch-service.spec.js
src/services/document-import-task-processor.js
src/services/document-import-task-processor.spec.js
src/services/export-service.js
src/services/export-service.spec.js
src/services/user-service.js
src/services/user-service.spec.js
src/stores/user-store.js

Closes https://educandu.atlassian.net/browse/EDU-832
The original plan was to trigger the final import through Postman, using the `POST /api/v1/imports` endpoint.
However the body of this request is required to have alot more information about the imported documents than just the IDs.
I've implemented a simple(r) alternative though :) Through this, the steps needed to be followed for the final import are4 adjusted as mentioned here: https://educandu.atlassian.net/browse/EDU-835

EDU-832 Extend export import functionality

---

src/components/markdown.less

Closes https://educandu.atlassian.net/browse/EDU-943
I also decreased the left padding for each list level in general from around 3em to 2.5em which I find looks better.
Before:
After:

EDU-943 Fix list styling in markdown

---

src/components/media-player/media-player-track-group.js
src/components/media-player/media-player-track.js
src/components/media-player/multitrack-media-player.js
src/components/media-player/preloading-media-player-track.js
src/components/pages/doc.js
src/components/pages/revision.js
src/components/section-display.js
src/components/sections-display.js
src/ui/react-helper.js

Closes https://educandu.atlassian.net/browse/EDU-951
After spending more than one day on this issue, I have currently drawn the line at transforming the bug into a different bug we could live with until we want to invest more time in this.
The situation is as follows:
- when a media plugin section sets a youtube URL as its `sourceUrl`, then plays and pauses it, then moves another section up, before it, the `react-player` starts disregarding the `false` value we pass to its `playing` param and starts auto-playing the video
- it seems the `react-player` ends up in an incorrect state from this point on
- using a `ref` for the value we pass to the `playing` param of the `react-player` does not solve the issue of its state change being disregarded in the described scenario
- manually pausing …

EDU-951 Partial fix for youtube video auto-play scenario

---

package.json
src/components/media-player/plyr/media-playback.js
src/components/media-player/plyr/media-playback.less
src/components/media-player/plyr/media-player.js
src/components/media-player/plyr/media-player.less
src/domain/constants.js
src/plugins/audio/audio-display.js
src/plugins/video/video-display.js
src/styles/main.less
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1002
This library also has a few glitches that I have corrected or that we might need to correct (or live with). So far though it seems to be less of a black box compared to `react-player` and the play/pause toggle seems to be reliable.
Also, all videos can now be played/paused by clicking on the video itself, so we would have consistency between youtube and CDN resources.

EDU-1002 Use plyr instead of react-player in video and audio plugins

---

migrations/educandu-2023-01-16-01-migrate-youtube-urls-to-playback-ranges.js

Closes https://educandu.atlassian.net/browse/EDU-1033
Snippet of the report of running the script on a PROD dump (from 16.01.2023 12PM), containing just the `documents` update:
[EDU-1033 Prod dump report.txt](https://github.com/educandu/educandu/files/10427865/EDU-1033.Prod.dump.report.txt)

EDU-1033 Migrate known youtubeURLs with start/stop times to playback ranges

---

src/components/media-player/multitrack-media-player.js
src/components/media-player/multitrack-media-player.less

Closes https://educandu.atlassian.net/browse/EDU-1049

EDU-1049 Show multitrack as loading until all tracks are ready

---

migrations/educandu-2023-01-26-01-add-width-to-markdown-with-image-plugin.js
src/plugins/markdown-with-image/markdown-with-image-display.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/markdown-with-image/markdown-with-image-info.js
src/plugins/markdown-with-image/markdown-with-image.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1055

EDU-1055 Add width to markdown-with-image plugin

---

src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1084
For a little visual context, it's about the link to the profile page of the owner of the room the current user was invited to:

EDU-1084 Map userId of room invitation into client data, for room invitation cards on dashboard

---

migrations/educandu-2023-02-13-01-rename-source-types-in-catalog-plugin-items.js
src/plugins/catalog/catalog-display.js
src/plugins/catalog/catalog-info.spec.js
src/plugins/catalog/catalog-item-editor.js
src/plugins/catalog/catalog-utils.js
src/plugins/catalog/catalog.less
src/plugins/catalog/catalog.yml
src/plugins/catalog/constants.js
src/plugins/iframe/iframe-editor.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1119
Attaching picture with (German) translations to check if they make sense this way.
**Case 1: Link list**
----
**Case 2: Image tiles**

EDU-1119 Change external link source input to url-input in catalog plugin

---

src/components/item-panel.js
src/components/pages/room.js
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1129
**NOTE 1:** I will test this today in the evening on a Windows machine to test for any potential problems there.
**NOTE 2:** I removed the drag&drop help tooltip as it did not look good in most cases (it also would render very far from the mouse cursor in most cases).

EDU-1129 Make panels draggable by their entire header

---

src/plugins/interactive-media/interactive-media-display.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-slideshow/media-slideshow-display.js
src/plugins/media-slideshow/media-slideshow-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1157
For a bit of clarification:
The `media-player` - `parts` param gets passed to the progress bar, which either displays the timecode for each part, or the `text` of each part, when provided.
The `text` is something we use for the range selector, but we want the timecodes for the other cases. 
So we need to map the parts (which to be fair we should have done anyway) to exclude chapter text, otherwise it gets rendered instead of the timecode.

EDU-1157 Correct data passed to media-player parts

---

src/components/media-player/media-player-progress-bar.less

Easily closes https://educandu.atlassian.net/browse/EDU-1153 with keeping the nice hover effect of the bar height changing.

EDU-1153 Fix progress bar tooltip flickering due to overlap of tooltip with the bar

---

src/components/pages/room.js
src/components/pages/room.less
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/room-service.js
src/services/room-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1155
**Explanation of the entangled situation**
For room documents there are 3 possible points of view:
1. owner (can see all documents, including drafts)
2. collaborator member, in "collaborative" rooms (can see only non-draft documents)
3. simple member, in "exclusive" rooms (can see only non-draft documents)
The complication comes for viewpoints 1. and 2., as they both can change the order of documents.
The previous solution:
- filtered out the non-draft documents on the server side, for viewpoints 2. and 3.
- **displayed** draft documents always at the end for viewpoint 1. and did not allow moving them
- whenever viewpoints 1. or 2. changed the documents order on client side, server side ensured draft documents were always at the end …

EDU-1155 Fix room documents sorting hopefully for good

---

src/services/amb-service.js
src/services/amb-service.spec.js

The context URI in amb was changed from `https://w3id.org/kim/amb/draft/context.jsonld` to `https://w3id.org/kim/amb/context.jsonld`
see also
* https://github.com/dini-ag-kim/amb/issues/167
* https://gitlab.com/oersi/oersi-schema/-/issues/3
With this PR the new context URI should be used. I hope I haven't missed anything.

AMB context URI Update

---

src/components/markdown.less
src/plugins/markdown-with-image/markdown-with-image.less

Closes https://educandu.atlassian.net/browse/EDU-1428
Examples of the cases involved:

EDU-1438 Fix cases that did not wrap in markdown-with-image (quote, video, audio)

---

migrations/educandu-2023-11-23-01-fix-unique-keys-in-section-contents.js
src/plugins/catalog/catalog-utils.js
src/plugins/ear-training/ear-training-info.js
src/plugins/interactive-media/interactive-media-info.js
src/plugins/media-analysis/media-analysis-utils.js
src/plugins/media-slideshow/media-slideshow-info.js
src/plugins/multitrack-media/multitrack-media-utils.js
src/plugins/quick-tester/quick-tester-info.js
src/plugins/select-field/select-field-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1432
With a copy of production data (from October 2023) the following sections were fixed:
~~~
Migrated 425 documents in collection 'documents'
* 512 'catalog' sections in 403 documents
* 16 'ear-training' sections in 10 documents
* 0 'interactive-media' sections in 0 documents
* 0 'media-analysis' sections in 0 documents
* 0 'media-slideshow' sections in 0 documents
* 0 'multitrack-media' sections in 0 documents
* 20 'quick-tester' sections in 19 documents
* 0 'select-field' sections in 0 documents
Migrated 5597 documents in collection 'documentRevisions'
* 594 'catalog' sections in 5249 documents
* 18 'ear-training' sections in 216 documents
* 0 'interactive-media' sections in 0 documents
* 0 'media-analysis' sections in 0 documents
* 0 …

EDU-1432 Fix duplicate keys in section content

---

migrations/educandu-2024-04-15-01-reset-documentRequests-collection.js
src/components/pages/tests.js
src/domain/schemas/document-request-schemas.js
src/server/tests-controller.js
src/services/document-request-service.js
src/services/document-request-service.spec.js
src/stores/collection-specs/document-requests.js

There are two optimizations regarding space consumption according to the findings described in the ticket:
1. Switching the `_id` field data type from `string` to `ObjectId`
2. Removing the compound index
There is also a new tab on the tests page to create 10.000 entries for one year for testing purposes.
Closes https://educandu.atlassian.net/browse/EDU-1541

EDU-1541 Create fake document requests for testing

---

src/components/pages/document.less

Closes https://educandu.atlassian.net/browse/EDU-1575
I tried both positioning orders (left <-> right):
**Desktop**
**Mobile**
I went with the "categories then rating" order because it looks ok on mobile out of the box, with keeping the page padding (so that the rating element is right aligned with the page content). Otherwise we would need to introduce more spacing on the right (which you break right side alignment) or push the page content lower.
Does this sound alright?

EDU-1575 Fix rating position on document page
