educandu/educandu

src/plugins/media-slideshow/media-slideshow-editor.js

Closes https://educandu.atlassian.net/browse/EDU-875

EDU-875 Inline chapter index management in media-slideshow with all multimedia player logic

---

src/components/media-player/media-player-track-group.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-slideshow/media-slideshow-editor.js

Closes https://educandu.atlassian.net/browse/EDU-874

EDU-874 Fix lack of propagation of range and duration changes in certain cases

---

migrations/educandu-2022-10-11-01-add-image-fit-to-media-slideshow-chapters.js
src/plugins/media-slideshow/constants.js
src/plugins/media-slideshow/media-slideshow-display.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/media-slideshow/media-slideshow-info.js
src/plugins/media-slideshow/media-slideshow.less
src/plugins/media-slideshow/media-slideshow.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-854

EDU-854 Add image scaling options in media slideshow

---

src/components/pages/doc.js

Closes https://educandu.atlassian.net/browse/EDU-855

EDU-855 Keep resources when copying sections through clipboard

---

src/api-clients/http-client.js
src/components/media-player/multitrack-media-player.js

Closes https://educandu.atlassian.net/browse/EDU-870

EDU-870 Fix CORS issue in media player download

---

src/api-clients/export-api-client.js
src/domain/schemas/export-schemas.js
src/domain/schemas/import-schemas.js
src/server/export-controller.js
src/services/batch-service.js
src/services/batch-service.spec.js
src/services/document-import-task-processor.js
src/services/document-import-task-processor.spec.js
src/services/document-service.js
src/services/document-service.spec.js
src/services/export-service.js
src/services/export-service.spec.js
src/services/import-service.js
src/services/import-service.spec.js
src/stores/order-store-base.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-876

EDU-876 Simplify import logic by dropping revisions restrictions

---

src/components/media-player/media-player-track-group.js

Closes https://educandu.atlassian.net/browse/EDU-879

EDU-879 Do not continuously call 'onDuration'

---

src/components/media-player/media-player-track.js

Closes https://educandu.atlassian.net/browse/EDU-869

EDU-869 Ensure tracks do not play on pause in Firefox

---

src/components/music-xml-document.js

Closes https://educandu.atlassian.net/browse/EDU-881

EDU-881 Support compressed MusicXML files

---

src/plugins/multitrack-media/multitrack-media-icon.js

Closes https://educandu.atlassian.net/browse/EDU-883

EDU-883 Replace incorrectly generated icon component for multitrack-media

---

src/components/media-player/main-track-editor.js
src/components/media-player/media-duration-cache.js
src/components/media-player/preloading-media-player-track.js
src/components/media-player/secondary-track-editor.js
src/utils/media-utils.js

Closes https://educandu.atlassian.net/browse/EDU-885

EDU-855 Fix crash due to quick state change when typing fast into multitrack sourceUrl fields

---

src/components/pages/tests.js
src/components/url-input.js
src/components/url-input.less
src/components/url-input.yml
src/domain/constants.js
src/resources/resources.json
src/styles/main.less
src/ui/validation.js
src/ui/validation.spec.js
src/utils/media-utils.js
src/utils/media-utils.spec.js
src/utils/storage-utils.js
src/utils/storage-utils.spec.js
src/utils/url-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-884

EDU-884 Add url-input component

---

migrations/educandu-2022-10-18-01-remove-sourceType-from-audio-plugin.js
src/components/url-input.js
src/domain/constants.js
src/plugins/audio/audio-display.js
src/plugins/audio/audio-editor.js
src/plugins/audio/audio-info.js
src/plugins/audio/audio-info.spec.js
src/plugins/plugin-registry.js
src/services/document-service.spec.js
src/ui/validation.js
src/utils/media-utils.js
src/utils/media-utils.spec.js
src/utils/source-utils.js
src/utils/source-utils.spec.js
src/utils/storage-utils.js
src/utils/storage-utils.spec.js

**Branched out of:** https://github.com/educandu/educandu/pull/674
Closes https://educandu.atlassian.net/browse/EDU-888

EDU-888 Use url-input component in audio plugin

---

migrations/educandu-2022-10-20-02-change-CDN-paths-into-portable-URLs.js
src/components/url-input.js
src/plugins/audio-waveform/audio-waveform-editor.js
src/utils/source-utils.js
src/utils/source-utils.spec.js

**Magically** 🧙‍♀️ closes https://educandu.atlassian.net/browse/EDU-892

EDU-892 Persist portable URL

---

src/components/pages/admin.js
src/components/pages/users.js
src/components/pages/users.less
src/components/pages/users.yml
src/resources/resources.json
src/styles/tabs.less

Closes https://educandu.atlassian.net/browse/EDU-893

EDU-893 Add users filter

---

src/plugins/multitrack-media/multitrack-media-display.js
src/plugins/multitrack-media/multitrack-media-editor.js
src/plugins/multitrack-media/multitrack-media-utils.js

Closes https://educandu.atlassian.net/browse/EDU-847

EDU-847 Allow single track in multitrack plugin

---

src/plugins/abc-notation/abc-notation-info.js
src/plugins/annotation/annotation-info.js
src/plugins/audio-waveform/audio-waveform-info.js
src/plugins/audio/audio-info.js
src/plugins/catalog/catalog-info.js
src/plugins/ear-training/ear-training-info.js
src/plugins/image/image-info.js
src/plugins/interactive-media/interactive-media-info.js
src/plugins/markdown/markdown-info.js
src/plugins/media-analysis/media-analysis-info.js
src/plugins/media-slideshow/media-slideshow-info.js
src/plugins/multitrack-media/multitrack-media-info.js
src/plugins/music-xml-viewer/music-xml-viewer-info.js
src/plugins/pdf-viewer/pdf-viewer-info.js
src/plugins/quick-tester/quick-tester-info.js
src/plugins/table/table-info.js
src/plugins/video/video-info.js
src/utils/source-utils.js
src/utils/source-utils.spec.js
src/utils/storage-utils.js
src/utils/storage-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-897

EDU-897 Fix section content redaction

---

src/components/admin/technical-maintenance-tab.yml
src/components/confirmation-dialogs.yml
src/components/markdown-help.yml
src/components/markdown-input.yml
src/components/pages/batches.yml
src/plugins/audio-waveform/audio-waveform.yml
src/plugins/catalog/catalog-item-editor.js
src/plugins/catalog/catalog.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-891

EDU-891 Replace the term 'CDN' with 'internal storage'

---

src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis.less
src/plugins/media-analysis/media-analysis.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-849

EDU-849 Allow playback by clicking on a part

---

src/components/icons/general/help-icon.js
src/components/section-display.js

Closes https://educandu.atlassian.net/browse/EDU-877

EDU-877 Replace info icon in section

---

package.json
src/common/github-flavored-markdown.js
src/components/markdown-input.js
src/components/markdown.js
src/plugins/markdown/markdown-display.js
src/plugins/markdown/markdown-editor.js
src/plugins/plugin-registry.js
src/plugins/table-of-contents/table-of-contents-display.js
src/plugins/table-of-contents/table-of-contents-editor.js
src/plugins/table-of-contents/table-of-contents-icon.js
src/plugins/table-of-contents/table-of-contents-info.js
src/plugins/table-of-contents/table-of-contents.less
src/plugins/table-of-contents/table-of-contents.yml
src/resources/resources.json
src/styles/main.less
src/test-helper.js
test-app/src/index.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-857

EDU-857 TOC plugin

---

src/plugins/audio-waveform/audio-waveform-icon.js

Closes https://educandu.atlassian.net/browse/EDU-889

EDU-889 Replace audio waveform plugin icon

---

src/api-clients/wikimedia-commons-api-client.js
src/components/pages/tests.js

Closes https://educandu.atlassian.net/browse/EDU-894
I stopped here after having a working search client, because I think from here on we can directly implement a new tab on the resource picker without the need for mocking up a preliminary UI.

EDU-894 Create a search client for Wikimedia Commons files

---

src/components/resource-picker/file-preview-screen.js
src/components/resource-picker/files-upload-screen.js
src/components/resource-picker/files-upload-screen.less
src/components/resource-picker/files-upload-screen.yml
src/components/resource-picker/utilities.less
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-898

EDU-898 Improve visibility of CDN image editor

---

src/plugins/memory/constants.js
src/plugins/memory/memory-display.js
src/plugins/memory/memory-editor.js
src/plugins/memory/memory-icon.js
src/plugins/memory/memory-info.js
src/plugins/memory/memory-utils.js
src/plugins/memory/memory.yml
src/plugins/plugin-registry.js
src/resources/resources.json
src/test-helper.js
test-app/src/index.js

Closes https://educandu.atlassian.net/browse/EDU-906
Temp or suggested icon:

EDU-906 Add empty memory plugin

---

src/plugins/audio-waveform/audio-waveform-info.spec.js
src/plugins/audio/audio-info.spec.js
src/plugins/ear-training/ear-training-info.spec.js
src/plugins/image/image-info.spec.js
src/plugins/markdown-with-image/markdown-with-image-info.spec.js
src/plugins/markdown/markdown-info.spec.js
src/plugins/memory/constants.js
src/plugins/memory/memory-editor.js
src/plugins/memory/memory-info.js
src/plugins/memory/memory-info.spec.js
src/plugins/memory/memory-utils.js
src/plugins/memory/memory-utils.spec.js
src/plugins/memory/memory.less
src/plugins/memory/memory.yml
src/plugins/table-of-contents/table-of-contents-info.spec.js
src/resources/resources.json
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-907

EDU-907 Create memory editor component

---

src/components/flip-card.js
src/components/flip-card.less
src/plugins/memory/memory-display.js
src/plugins/memory/memory-utils.js
src/plugins/memory/memory-utils.spec.js
src/plugins/memory/memory.less
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-908

EDU-908 Create memory display component

---

src/components/markdown.less

Closes https://educandu.atlassian.net/browse/EDU-919

EDU-919 Clear potential floats before starting a blackquote

---

migrations/educandu-2022-11-03-01-add-sourceUrl-to-memory-plugin.js
src/components/flip-card.js
src/components/flip-card.less
src/components/media-player/media-player.js
src/components/media-player/multitrack-media-player.js
src/plugins/memory/memory-display.js
src/plugins/memory/memory-editor.js
src/plugins/memory/memory-info.js
src/plugins/memory/memory-info.spec.js
src/plugins/memory/memory-tile.js
src/plugins/memory/memory-utils.js
src/plugins/memory/memory-utils.spec.js
src/plugins/memory/memory.less
src/plugins/memory/memory.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-916
---

EDU-916 Expand memory plugin data model

---

src/api-clients/room-api-client.js
src/components/pages/room.js
src/components/room-invitation-creation-modal.js
src/components/room-invitation-creation-modal.yml
src/domain/schemas/room-schemas.js
src/domain/schemas/room-schemas.spec.js
src/domain/schemas/shared-schemas.js
src/domain/schemas/shared-schemas.spec.js
src/domain/validation-constants.js
src/resources/resources.json
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/mail-service.js
src/services/room-service.js
src/services/room-service.spec.js
src/utils/input-validators.js

Closes https://educandu.atlassian.net/browse/EDU-920

EDU-920 batch room invitations

---

src/components/flip-card.js
src/components/flip-card.less
src/components/icons/general/check-icon.js
src/components/resource-picker/files-viewer.less
src/components/room-card.less
src/components/section-display.less
src/plugins/memory/memory-display.js
src/plugins/memory/memory-tile.js
src/plugins/memory/memory.less
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-912

EDU-912 Mark tiles match found in memory plugin

---

src/components/pages/room.js
src/components/room-metadata-form.yml
src/server/document-controller.js
src/server/document-controller.spec.js
src/server/revision-controller.js
src/server/room-controller.js
src/server/storage-controller.js
src/services/storage-service.js
src/utils/doc-utils.js
src/utils/room-utils.js
src/utils/room-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-921

EDU-921 Restrict document deletion in rooms to owners

---

src/components/room-metadata-form.js
src/styles/utilities.less

Closes https://educandu.atlassian.net/browse/EDU-922

EDU-922 Streamline formitem tooltip icon and cursor

---

src/components/flip-card.js
src/components/flip-card.less
src/plugins/memory/memory-display.js

Closes https://educandu.atlassian.net/browse/EDU-938

EDU-938 Keep cards flipped in pairs

---

src/components/media-player/media-player.js
src/components/media-player/media-range-selector.js
src/components/media-player/media-range-selector.less
src/components/media-player/media-range-selector.yml
src/components/media-player/multitrack-media-player.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-923

EDU-923 Replace media range selection means

---

migrations/educandu-2022-11-15-01-add-textOffsetInEm-to-markdown-with-image-plugin.js
src/plugins/catalog/catalog-editor.js
src/plugins/iframe/iframe-editor.js
src/plugins/markdown-with-image/markdown-with-image-display.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/markdown-with-image/markdown-with-image-info.js
src/plugins/markdown-with-image/markdown-with-image.less
src/plugins/markdown-with-image/markdown-with-image.yml
src/resources/resources.json
src/utils/array-utils.js
src/utils/array-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-924

EDU-924 Add text offset to markdown-with-image plugin

---

src/components/locale-context.js
src/components/media-player/main-track-editor.js
src/components/media-player/media-player-controls.js
src/components/media-player/media-player-progress-bar.js
src/components/media-player/media-volume-slider.js
src/components/media-player/timeline.js
src/components/object-width-slider.js
src/components/step-slider.js
src/plugins/audio-waveform/audio-waveform-editor.js
src/plugins/catalog/catalog-editor.js
src/plugins/iframe/iframe-editor.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/markdown-with-image/markdown-with-image.yml
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/music-xml-viewer/music-xml-viewer-editor.js
src/plugins/table-of-contents/table-of-contents-editor.js
src/resources/resources.json
src/utils/string-utils.js

Closes https://educandu.atlassian.net/browse/EDU-942

EDU-942 Create StepSlider component and use it where applicable

---

src/components/document-metadata-modal.js
src/components/info.js
src/components/info.less
src/components/resource-picker/files-upload-screen.js
src/components/resource-picker/files-upload-screen.less
src/components/room-invitation-creation-modal.js
src/components/room-metadata-form.js
src/plugins/abc-notation/abc-notation-editor.js
src/plugins/annotation/annotation-editor.js
src/plugins/audio-waveform/audio-waveform-editor.js
src/plugins/catalog/catalog-editor.js
src/plugins/diagram-net/diagram-net-editor.js
src/plugins/ear-training/ear-training-editor.js
src/plugins/iframe/iframe-editor.js
src/plugins/image/image-editor.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/matching-cards/matching-cards-editor.js
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/multitrack-media/multitrack-media-editor.js
src/plugins/music-xml-viewer/music-xml-viewer-editor.js
src/plugins/pdf-viewer/pdf-viewer-editor.js
src/plugins/table/table-editor.js
src/plugins/video/video-editor.js
src/styles/main.less
src/styles/utilities.less

Closes https://educandu.atlassian.net/browse/EDU-947

EDU-947 Consolidate info labels and icons

---

src/plugins/markdown-with-image/markdown-with-image.less

Closes https://educandu.atlassian.net/browse/EDU-944

EDU-944 Make the image span the available width

---

src/components/control-panel.less
src/components/pages/doc.less

Closes https://educandu.atlassian.net/browse/EDU-946

EDU-946 Remove pointer events from invisible footer parts

---

src/components/locale-context.js

Closes https://educandu.atlassian.net/browse/EDU-948

EDU-948 Fix localization hook

---

src/components/media-player/media-player-track.js
src/components/section-display.js
src/components/sections-display.js
src/plugins/matching-cards/matching-cards-tile.js
src/plugins/table/table-designer-menu.js
src/ui/hooks.js
src/ui/react-helper.js

Closes https://educandu.atlassian.net/browse/EDU-939

EDU-939 Only re-render sections when the content has changed

---

.eslintignore
.github/workflows/publish.yml
.github/workflows/verify.yml
package.json
src/bootstrap/server-bootstrapper.js
src/data/language-name-provider.js
src/test-setup.js
src/ui/hooks.js
test-app/src/index.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-930

EDU-930 Update nodejs to v18

---

src/components/document-metadata-modal.js
src/components/pages/room.js

Closes https://educandu.atlassian.net/browse/EDU-958

EDU-958 Restrict draft option to room owners

---

src/components/media-player/media-duration-cache.js
src/components/media-player/media-hooks.js
src/components/media-player/media-player-track.js
src/components/media-player/youtube-thumbnail-url-cache.js
src/utils/image-utils.js
src/utils/media-utils.js
src/utils/media-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-949

EDU-949 Use high res Youtube thumbnail if available

---

src/components/document-metadata-modal.js
src/components/pages/doc.js

Closes https://educandu.atlassian.net/browse/EDU-970

EDU-970 Allow updating draft state when editing metadata

---

migrations/archived/automatic/educandu-2022-03-09-01-add-updatedOn-to-rooms.js
migrations/archived/automatic/educandu-2022-04-11-02-add-updatedBy-to-lessons.js
migrations/archived/automatic/educandu-2022-07-14-01-remove-document-key.js
src/services/batch-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-953

EDU-953 Fix mongodb warning

---

src/components/pages/doc.less
src/components/templates/page-template.js

Closes https://educandu.atlassian.net/browse/EDU-954

EDU-954 Try to fix control panel stickyness on mobile once again

---

package.json
src/utils/unique-id.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-973

EDU-973 Use nanoid for id generation

---

migrations/educandu-2022-12-19-01-make-userId-unique-in-passwordResetRequest.js
src/services/user-service.js
src/stores/collection-specs/password-reset-requests.js
src/stores/password-reset-request-store.js

Closes https://educandu.atlassian.net/browse/EDU-979

EDU-979 Set single password reset request per user

---

src/components/media-player/media-player-track.js

Closes https://educandu.atlassian.net/browse/EDU-981

EDU-981 Rerender media player in specific case

---

src/server/user-controller.js

Closes https://educandu.atlassian.net/browse/EDU-985

EDU-985 Fix log out (due to passport changes in latest version)

---

README.md
migrations/educandu-2022-12-19-01-make-userId-unique-in-passwordResetRequest.js
migrations/educandu-2022-12-20-01-create-requestLimitRecords-collection.js
package.json
src/bootstrap/server-config.js
src/components/confirmation-dialogs.js
src/components/login-form.js
src/components/login-form.yml
src/components/pages/login.js
src/domain/constants.js
src/resources/resources.json
src/server/admin-controller.js
src/server/educandu-server.js
src/server/user-controller.js
src/server/user-controller.spec.js
src/services/request-limit-record-service.js
src/stores/collection-specs/request-limit-records.js
src/stores/database.js
src/stores/request-limit-record-store.js
src/utils/request-utils.js
src/utils/string-utils.js
src/utils/string-utils.spec.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-976

EDU-976 Prevent password brute forcing

---

src/server/user-controller.js

Closes https://educandu.atlassian.net/browse/EDU-988

EDU-988 Really fix log out this time

---

src/server/user-controller.js
src/utils/session-utils.js
src/utils/session-utils.spec.js
src/utils/unique-id.js

Closes https://educandu.atlassian.net/browse/EDU-978

EDU-978 Prevent session hijacking

---

src/components/login-form.js
src/domain/constants.js
src/domain/rate-limit-middleware.js
src/server/error-controller.js
src/server/user-controller.js
src/server/user-controller.spec.js
src/services/request-limit-record-service.js

Closes https://educandu.atlassian.net/browse/EDU-986

EDU-986 Rate limit password reset API endpoints

---

migrations/educandu-2022-07-30-01-initial-schema.js
migrations/educandu-2022-12-22-05-create-externalAccounts-collection.js
src/domain/rate-limit-middleware.js
src/domain/schemas/external-account-schemas.js
src/server/user-controller.js
src/services/external-account-service.js
src/services/request-limit-record-service.js
src/services/user-service.js
src/stores/collection-specs/external-accounts.js
src/stores/database.js
src/stores/external-account-store.js
src/stores/request-limit-record-store.js
src/stores/user-store.js

Closes https://educandu.atlassian.net/browse/EDU-990

EDU-990 Create external accounts collection, store and service

---

src/plugins/matching-cards/matching-cards.less

Closes https://educandu.atlassian.net/browse/EDU-998

EDU-998 Ensure matching-cards tiles contain centered text regardless of number of paragraphs

---

src/plugins/matching-cards/matching-cards.less
src/styles/elements.less

Closes https://educandu.atlassian.net/browse/EDU-999

EDU-999 Reduce font in matching cards on phone

---

src/components/flip-card.js
src/components/flip-card.less
src/components/not-supported-section.less
src/plugins/matching-cards/matching-cards-display.js

Closes https://educandu.atlassian.net/browse/EDU-997

EDU-997 Flip card rendering issues

---

src/components/pages/doc.js

Closes https://educandu.atlassian.net/browse/EDU-982
[EDU-982]: https://educandu.atlassian.net/browse/EDU-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EDU-982 Ensure control panels top distance when window height changes on mobile

---

README.md
gulpfile.js
package.json
src/bootstrap/server-config.js
src/server/user-controller.js
src/utils/session-utils.js
src/utils/session-utils.spec.js
test-app/src/index.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1019
and depends on https://github.com/educandu/rooms-auth-lambda/pull/6
**IMPORTANT:** Update rooms-auth-lambda dependency before merging this PR.
[EDU-1019]: https://educandu.atlassian.net/browse/EDU-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EDU-1019 Validate rooms-auth-lambda requests based on header secret

---

src/components/flip-card.js
src/components/flip-card.less
src/plugins/matching-cards/matching-cards-display.js
src/plugins/matching-cards/matching-cards-tile.js
src/plugins/matching-cards/matching-cards.less

Closes https://educandu.atlassian.net/browse/EDU-1021

EDU-1021 Fix matched overlay position on scrollable cards

---

src/server/user-controller.js

Closes https://educandu.atlassian.net/browse/EDU-1022

EDU-1022 Save last login date for users

---

src/components/storage-plan-modal.js

Closes https://educandu.atlassian.net/browse/EDU-1024

EDU-1024 Fix form in modal always showing the values of the last open state

---

migrations/educandu-2023-01-12-01-add-playbackRange-to-video-plugin.js
src/components/media-player/main-track-editor.js
src/components/media-player/media-range-readonly-input.js
src/components/media-player/media-range-readonly-input.yml
src/components/media-player/media-range-selector.js
src/components/media-player/media-range-selector.less
src/plugins/video/video-display.js
src/plugins/video/video-editor.js
src/plugins/video/video-info.js
src/resources/common.yml
src/resources/resources.json
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1030

EDU-1030 Support range in video plugin

---

migrations/educandu-2023-01-12-02-add-playbackRange-to-audio-plugin.js
src/plugins/audio/audio-display.js
src/plugins/audio/audio-editor.js
src/plugins/audio/audio-info.js
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1029
[This PR](https://github.com/educandu/educandu/pull/772) **needs to be merged first**, before reviewing and merging the current one.

EDU-1029 Support range in audio plugin

---

migrations/educandu-2023-01-13-01-remove-midi-from-abc-notation-plugin.js
migrations/educandu-2023-01-13-02-remove-midi-from-ear-training-plugin.js
migrations/educandu-2023-01-13-03-add-playbackRange-to-ear-training-plugin.js
src/components/abc-notation.js
src/components/abc-notation.less
src/components/media-player/media-range-readonly-input.js
src/plugins/abc-notation/abc-notation-display.js
src/plugins/abc-notation/abc-notation-editor.js
src/plugins/abc-notation/abc-notation-info.js
src/plugins/abc-notation/abc-notation.yml
src/plugins/ear-training/ear-training-display.js
src/plugins/ear-training/ear-training-editor.js
src/plugins/ear-training/ear-training-info.js
src/plugins/ear-training/ear-training-info.spec.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1006

EDU-1006 use plyr in abc notation and ear training

---

src/components/media-player/plyr/media-duration-identifier.js
src/components/media-player/plyr/media-player.js
src/components/media-player/plyr/youtube-player.js
src/plugins/matching-cards/matching-cards-tile-display.js
src/utils/media-utils.js
src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1039

EDU-1039 Replace react-player-in-media-utils

---

src/components/media-player/main-track-editor.js
src/components/media-player/media-range-readonly-input.js
src/components/media-player/media-range-selector.js
src/components/media-player/plyr/html5-player.js
src/components/media-player/plyr/media-duration-identifier.js
src/components/media-player/secondary-track-editor.js
src/components/url-input.js
src/plugins/audio/audio-editor.js
src/plugins/ear-training/ear-training-editor.js
src/plugins/matching-cards/matching-cards-tile-editor.js
src/plugins/video/video-editor.js
src/utils/media-utils.js
src/utils/media-utils.spec.js
src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1040

EDU-1040 Rework media helpers

---

src/components/media-player/media-range-selector.js
src/components/media-player/plyr/media-player.js
src/components/resource-picker/resource-preview.js

Closes https://educandu.atlassian.net/browse/EDU-1037

EDU-1037 Use plyr-based media player in media-range-selector

---

src/components/error-page.js
src/server/error-controller.js
src/server/user-controller.js
src/services/user-service.js
src/services/user-service.spec.js
src/stores/user-store.js

Closes https://educandu.atlassian.net/browse/EDU-995

EDU-995 Extend post-auth logic for external accounts

---

src/components/media-player/main-track-editor.js
src/components/media-player/plyr/html5-player.js
src/components/media-player/plyr/media-player.js
src/components/media-player/plyr/media-player.less
src/components/media-player/plyr/youtube-player.js
src/domain/constants.js
src/plugins/interactive-media/interactive-media-display.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-slideshow/media-slideshow-display.js
src/plugins/media-slideshow/media-slideshow-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1007

EDU-1007 Use plyr player in overlayed media plugins

---

src/components/login-form.js
src/components/pages/login.js
src/server/user-controller.js
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1038

EDU-1038 Redirect back to original URL after SAML login

---

src/components/media-player/youtube-thumbnail-url-cache.js
src/utils/image-utils.js
src/utils/media-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1044

EDU-1044 Adjust to Youtube high rest image fallback change

---

src/server/educandu-server.js

Closes https://educandu.atlassian.net/browse/EDU-1047

EDU-1047 Place basic auth middleware only before pages

---

src/components/media-player/plyr/media-player.js
src/components/media-player/plyr/multitrack-media-player.js
src/components/media-player/plyr/youtube-player.js
src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1048

EDU-1048 Replace multitrack-player in media analysis

---

migrations/educandu-2023-01-20-01-correct-volume-presets-in-multitrack-data.js
migrations/educandu-2023-01-20-01-correct-volume-presets-in-multitrack-data.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1051

EDU-1051 Correct persisted volume presets

---

src/plugins/ear-training/ear-training-display.js

Closes https://educandu.atlassian.net/browse/EDU-1052

EDU-1052 Fix visited tests in ear training plugin

---

src/components/media-player/multitrack-media-player.js

Closes https://educandu.atlassian.net/browse/EDU-1073

EDU-1073 fix player reloading

---

src/components/media-player/html5-player.js
src/components/media-player/media-player.js
src/components/media-player/multitrack-media-player.js
src/components/media-player/youtube-player.js

Closes https://educandu.atlassian.net/browse/EDU-1053

EDU-1053 Fix media playing out of range

---

src/components/section-display.less
src/styles/global-variables.less
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1036

EDU-1036 Restore section display overlay button styles after Antd update

---

src/components/section-display.js
src/components/section-display.less
src/components/sections-display.js
src/components/sections-display.less
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-1066

EDU-1066 Restyle section display header

---

src/components/media-player/multitrack-media-player.js

Closes https://educandu.atlassian.net/browse/EDU-1075

EDU-1075 Show actual track names in display mode track mixer

---

src/components/media-player/media-player.js
src/components/media-player/youtube-player.js
src/plugins/matching-cards/matching-cards-tile-display.js
src/ui/react-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1072

EDU-1072 Remount media player completely in case sourceUrl or playbackRange changes

---

src/components/default-page-footer.less
test-app/src/bundles/page-footer.js
test-app/src/bundles/page-footer.less

Closes https://educandu.atlassian.net/browse/EDU-1077

EDU-1077 Wrap page footer links on small screens

---

src/components/search-bar.js
src/components/search-bar.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1058

EDU-1058 Change search-bar validation approach

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.yml
src/components/filter-input.js
src/components/icons/general/filter-icon.js
src/components/pages/docs.js
src/components/pages/docs.yml
src/components/pages/search.yml
src/components/resource-picker/storage-location.js
src/components/resource-picker/storage-location.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1080
**Before**
**Current**

EDU-1080 Extract filter component

---

src/components/pages/doc.js
src/components/section-display.js
src/resources/resources.json
src/ui/browser-helper.js
src/utils/doc-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1079

EDU-1079 Scroll to the last seen section after switching views on doc page

---

src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1081
Cleanup and refactoring left this small casualty behind 😬

EDU-1081 Correct media duration util method

---

src/components/document-card.js

Closes https://educandu.atlassian.net/browse/EDU-1085

EDU-1085 Show user names of createdBy and updatedBy correctly

---

README.md
src/bootstrap/client-bootstrapper.js
src/bootstrap/server-bootstrapper.js
src/bootstrap/server-config.js
src/components/license-select.js
src/components/license-select.yml
src/components/pages/tests.js
src/domain/schemas/media-library-item-schemas.js
src/resources/license-manager.js
src/resources/resources.json
src/server/page-renderer.js
test-app/src/index.js

Closes https://educandu.atlassian.net/browse/EDU-1018

EDU-1018 Set up a license list and selector

---

src/domain/rate-limit-middleware.js
src/services/request-limit-record-service.js
src/stores/request-limit-record-store.js
src/stores/request-limit-record-store.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1003

EDU-1003 Fix number overflow case for requestLimitRecords

---

src/components/resource-picker/resource-preview.less

Closes https://educandu.atlassian.net/browse/EDU-1105
**Before**
**After**

EDU-1105 Fix file preview for videos

---

src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1106

EDU-1106 Gladly shorten translations for copyright notice

---

migrations/educandu-2023-02-02-01-add-posterImage-to-interactive-media-plugin.js
migrations/educandu-2023-02-02-02-add-posterImage-to-multitrack-media-plugin.js
migrations/educandu-2023-02-02-03-add-posterImage-to-media-analysis-plugin.js
src/components/media-player/main-track-editor.js
src/components/media-player/multitrack-media-player.js
src/components/resource-picker/resource-picker.js
src/components/url-input.js
src/plugins/interactive-media/interactive-media-display.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/interactive-media/interactive-media-info.js
src/plugins/interactive-media/interactive-media-info.spec.js
src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/media-analysis/media-analysis-info.js
src/plugins/media-analysis/media-analysis-info.spec.js
src/plugins/media-analysis/media-analysis-utils.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/multitrack-media/multitrack-media-display.js
src/plugins/multitrack-media/multitrack-media-editor.js
src/plugins/multitrack-media/multitrack-media-info.js
src/plugins/multitrack-media/multitrack-media-info.spec.js
src/plugins/multitrack-media/multitrack-media-utils.js
src/plugins/video/video-editor.js
src/plugins/video/video-info.spec.js
src/plugins/video/video.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1091

EDU-1091 Add poster image to all video playing plugins

---

src/components/pages/room.js
src/components/pages/room.less
src/components/pages/room.yml
src/components/user-card.js
src/components/user-card.less
src/resources/resources.json
src/server/room-controller.js
src/services/client-data-mapping-service.js
src/styles/mixins.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1093

EDU-1093 Allow room owners to see member emails

---

src/components/pages/doc.js

Closes https://educandu.atlassian.net/browse/EDU-1082 (or at least gives it a shot)

EDU-1082 Try to fix misplaced control panels on non-touch devices

---

migrations/educandu-2023-02-08-01-change-cdn-urls-in-rooms.js
migrations/educandu-2023-02-08-01-change-cdn-urls-in-rooms.spec.js
migrations/educandu-2023-02-08-02-change-accessible-cdn-urls-in-documents.js
migrations/educandu-2023-02-08-02-change-accessible-cdn-urls-in-documents.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1110
The JIRA ticket https://educandu.atlassian.net/jira/software/projects/EDU/boards/1?selectedIssue=EDU-1110 contains:
- the reports of running the 2 scripts on Production data on OMA, as attachments
- the list of ELMU CDN URLs, as comment

EDU-1090 Migrate accessible CDN URLs

---

src/components/media-player/main-track-editor.js
src/components/media-player/secondary-track-editor.js
src/components/url-input.js
src/plugins/audio/audio-editor.js
src/plugins/ear-training/ear-training-editor.js
src/plugins/image/image-editor.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/video/video-editor.js
src/resources/common.yml
src/resources/resources.json
src/utils/source-utils.js
src/utils/wikimedia-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1092

EDU-1092 Prefill copyright for youtube and wikipedia

---

src/components/media-player/track-mixer-display.js

Closes https://educandu.atlassian.net/browse/EDU-1108

EDU-1108 Reset solo state when volumes or preset change

---

src/components/room-card.js
src/components/room-card.less

Closes https://educandu.atlassian.net/browse/EDU-1109

EDU-1109 Center room content vertically on card (leaving space for closing icon)

---

src/components/login-form.js
src/components/resource-picker/resource-selector.js
src/domain/constants.js

Closes https://educandu.atlassian.net/browse/EDU-1112

EDU-1112 Introduce media library feature toggle

---

src/components/control-panel.js
src/components/pages/doc.js

Gladly fixes https://educandu.atlassian.net/browse/EDU-1107

EDU-1107 Fix broken control panel state

---

migrations/educandu-2023-02-10-01-change-accessible-cdn-urls-catalog-external-link-types.js
migrations/educandu-2023-02-10-01-change-accessible-cdn-urls-catalog-external-link-types.spec.js.js

Closes https://educandu.atlassian.net/browse/EDU-1117

EDU-1117 Migrate CDN URLs in external sources inside the catalog plugin

---

src/components/drag-and-drop-container.js
src/components/item-panel.js
src/components/item-panel.less
src/components/pages/room.js
src/components/pages/room.less
src/components/section-display.js
src/components/section-display.less
src/styles/utilities.less
src/utils/room-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1114
**Owner view:**
**Collaborator view:**
**Member view (aka exclusive room member):**

EDU-1114 Make room documents draggable

---

src/common/github-flavored-markdown.js
src/common/github-flavored-markdown.spec.js
src/components/debounced-input.js
src/components/markdown-input.js
src/components/never-scrolling-text-area.js
src/components/pages/tests.js

Closes https://educandu.atlassian.net/browse/EDU-1111

EDU-1111 Sanitize CDN URLs in all Markdown inputs

---

src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1118
This worked out easily enough without compromise 😊

EDU-1118 Fit 4 user/room cards per row

---

src/components/media-player/media-player.less
src/plugins/matching-cards/matching-cards-tile-display.js
src/plugins/matching-cards/matching-cards.less

Closes https://educandu.atlassian.net/browse/EDU-1124

EDU-1124 Fix matching-cards plugin tile for audio-only media

---

src/api-clients/document-api-client.js
src/components/pages/dashboard.js
src/components/pages/user-profile.js
src/domain/schemas/document-schemas.js
src/server/document-controller.js
src/services/document-service.js
src/services/document-service.spec.js
src/stores/document-store.js

Closes https://educandu.atlassian.net/browse/EDU-1125

EDU-1125 Do not show private documents in documents tab or user profile

---

src/server/document-controller.js
src/server/room-controller.js
src/server/room-controller.spec.js
src/server/user-controller.spec.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1126

EDU-1126 Fix error when sorting room documents

---

src/components/default-page-header.js
src/resources/common.yml
src/resources/resources.json
test-app/src/bundles/page-header.js

Closes https://educandu.atlassian.net/browse/EDU-1140

EDU-1140 Remove new document menu entry

---

src/components/room-card.less

Closes https://educandu.atlassian.net/browse/EDU-1158
Small visual of before and after:

EDU-1158 Remove extra content padding in room card

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.yml
src/components/document-metadata-modal.js
src/domain/constants.js
src/domain/permissions.js
src/domain/permissions.spec.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1142

EDU-1142 Create accreditedAuthor role

---

src/components/pages/doc.js
src/components/pages/doc.less

Closes https://educandu.atlassian.net/browse/EDU-1160

EDU-1160 Fix control panels positioning when open

---

src/components/admin/admin-settings-tab.js
src/components/admin/admin-settings-tab.less
src/components/admin/admin-settings-tab.yml
src/components/admin/announcement-settings.js
src/components/admin/homepage-documents-table.js
src/components/admin/homepage-documents.js
src/components/admin/homepage-tags.js
src/components/admin/settings-documents-table.js
src/components/admin/settings-documents-table.yml
src/components/admin/special-page-settings.js
src/components/pages/index.js
src/resources/common.yml
src/resources/resources.json
src/server/index-controller.js
src/styles/utilities.less
test-app/src/bundles/site-logo.less

Closes https://educandu.atlassian.net/browse/EDU-1147

EDU-1147 Support homepage documents and tags

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.less
src/components/pages/search.js
src/components/pages/search.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1161

EDU-1161 Make users selectable

---

src/components/navigation-desktop.js
src/components/navigation-desktop.less
src/components/navigation-mobile.js
src/components/navigation-mobile.less
src/components/navigation-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1166

EDU-1166 Improve navigation

---

migrations/educandu-2023-02-24-01-add-events-collection.js
src/api-clients/comment-api-client.js
src/components/pages/doc.js
src/domain/constants.js
src/domain/schemas/comment-schemas.js
src/domain/schemas/event-schemas.js
src/server/comment-controller.js
src/services/comment-service.js
src/services/comment-service.spec.js
src/services/document-service.js
src/services/document-service.spec.js
src/stores/collection-specs/events.js
src/stores/comment-store.js
src/stores/database.js
src/stores/event-store.js
src/test-helper.js
src/utils/comment-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1168

EDU-1168 capture events in new collection

---

src/components/media-player/multitrack-media-player.js
src/plugins/music-xml-viewer/music-xml-viewer-editor.js
src/plugins/pdf-viewer/pdf-viewer-editor.js
src/utils/array-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1174

EDU-1174 fix js error in multitrack player

---

src/components/admin/homepage-tags.js
src/components/tag-select.js
src/plugins/music-xml-viewer/music-xml-viewer-editor.js
src/plugins/pdf-viewer/pdf-viewer-editor.js
src/utils/array-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1175

EDU-1175 homepage tags input should always suggest tags

---

src/components/pages/doc.less

Closes https://educandu.atlassian.net/browse/EDU-1170

EDU-1170 Fix broken document payge layout

---

src/components/default-page-header.js
src/components/default-page-header.less
src/components/navigation-desktop.js
src/ui/hooks.js

Closes https://educandu.atlassian.net/browse/EDU-1159

EDU-1159 Make navigation bar sticky

---

migrations/educandu-2023-02-28-01-migrate-document-media-to-media-library.js
migrations/educandu-2023-02-28-01-migrate-document-media-to-media-library.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1181

EDU-1181 Migrate CDN resources out of document-media

---

src/api-clients/notifications-api-client.js
src/components/dashboard/notifications-tab.js
src/components/dashboard/notifications-tab.less
src/components/dashboard/notifications-tab.yml
src/components/pages/dashboard.js
src/components/pages/dashboard.yml
src/resources/resources.json
src/server/controller-factory.js
src/server/notification-controller.js
src/services/client-data-mapping-service.js
src/services/event-service.js
src/services/notification-service.js
src/stores/notification-store.js
src/styles/main.less
src/ui/default-prop-types.js
src/utils/notification-utils.js
src/utils/notification-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1178

EDU-1178 Create notifications tab on user dashboard

---

src/bootstrap/client-bootstrapper.js
src/components/navigation-desktop.js
src/components/navigation-desktop.less
src/components/navigation-mobile.js
src/components/navigation-utils.js
src/components/notification-context.js
src/components/pages/dashboard.js
src/components/pages/dashboard.yml
src/components/root.js
src/resources/common.yml
src/resources/resources.json
src/server/educandu-server.js
src/server/notification-controller.js
src/server/page-renderer.js
src/server/storage-controller.js

Closes https://educandu.atlassian.net/browse/EDU-1179

EDU-1179 Show badges for notifications

---

migrations/educandu-2023-03-01-02-remove-readOn-from-notifications-collection.js
src/api-clients/notifications-api-client.js
src/bootstrap/client-bootstrapper.js
src/components/dashboard/activities-tab.js
src/components/dashboard/activities-tab.less
src/components/dashboard/notifications-tab.js
src/components/dashboard/notifications-tab.less
src/components/dashboard/notifications-tab.yml
src/components/default-page-footer.less
src/components/icons/user-notifications/comments-icon.js
src/components/icons/user-notifications/edit-doc-icon.js
src/components/navigation-desktop.js
src/components/navigation-desktop.less
src/components/navigation-mobile.js
src/components/navigation-mobile.less
src/components/navigation-utils.js
src/components/notification-context.js
src/components/pages/dashboard.js
src/components/root.js
src/domain/schemas/notification-schemas.js
src/resources/common.yml
src/resources/resources.json
src/server/notification-controller.js
src/server/page-renderer.js
src/services/event-service.js
src/services/notification-service.js
src/stores/collection-specs/notifications.js
src/stores/notification-store.js
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1183

EDU-1183 Make notifications dismissable

---

src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/multitrack-media/multitrack-media-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1173

EDU-1173 Fix toggling showVideo on automatically with any player settings change

---

migrations/educandu-2023-03-02-01-add-emailNotificationFrequency-to-users-collection.js
src/api-clients/user-api-client.js
src/components/dashboard/settings-tab.js
src/components/dashboard/settings-tab.yml
src/domain/constants.js
src/domain/schemas/user-schemas.js
src/resources/resources.json
src/server/user-controller.js
src/server/user-controller.spec.js
src/services/amb-service.spec.js
src/services/batch-service.spec.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/comment-service.spec.js
src/services/document-service.spec.js
src/services/room-service.spec.js
src/services/storage-service.spec.js
src/services/user-service.js
src/services/user-service.spec.js
src/stores/room-store.spec.js
src/stores/user-store.spec.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1185

EDU-1185 add email notification frequency to users

---

src/components/resource-selector/media-library/media-library-search-screen.yml
src/components/resource-selector/wikimedia/wikimedia-search-screen.yml
src/plugins/audio-waveform/audio-waveform-editor.js
src/plugins/audio-waveform/audio-waveform-generator-dialog.js
src/plugins/audio-waveform/audio-waveform.less
src/plugins/audio-waveform/audio-waveform.yml
src/resources/resources.json
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1189
**And last but not least, mobile beauty**

EDU-1189 Support metadata input in audio-waveform plugin

---

gulpfile.js
src/bootstrap/server-config.js
src/domain/constants.js
src/resources/resources.json
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/mail-service.js
src/services/mail-service.yml
src/services/notification-service.js
src/services/scheduling/job-scheduler.js
src/services/scheduling/jobs/send-notification-emails-job.js
src/stores/notification-store.js
src/test-helper.js
test-app/src/index.js

Closes https://educandu.atlassian.net/browse/EDU-1186

EDU-1186 Periodically send notification reminder emails

---

src/components/comments-panel.js
src/components/dashboard/settings-tab.js
src/components/markdown-input.js
src/components/room-metadata-form.js

Closes https://educandu.atlassian.net/browse/EDU-1199

EDU-1199 Give the people what they want

---

src/components/dashboard/settings-tab.js
src/components/room-metadata-form.js

Closes https://educandu.atlassian.net/browse/EDU-1192

EDU-1192 Let there be a picker

---

src/services/notification-service.js

Closes https://educandu.atlassian.net/browse/EDU-1202

EDU-1202 Do not send emails for an empty notification list

---

src/components/pages/search.js
src/components/pages/search.yml
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-documents-tab.less
src/components/redaction/redaction-media-library-tab.js
src/components/resource-info-cell.js
src/components/resource-info-cell.less
src/components/room-card.js
src/components/room-card.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1204

EDU-1204 Streamline resource info cell

---

src/plugins/table-of-contents/table-of-contents-display.js
src/plugins/table-of-contents/table-of-contents.less
src/plugins/table-of-contents/table-of-contents.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1195

EDU-1195 Adjust table of contents plugin

---

src/components/homepage/homepage-document-cards.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1205

EDU-1205 Change homepage documents headline

---

src/plugins/separator/separator-icon.js

Closes https://educandu.atlassian.net/browse/EDU-1200

EDU-1200 Change separator plugin icon

---

src/components/dashboard/rooms-tab.js
src/components/dashboard/rooms-tab.less
src/components/dashboard/rooms-tab.yml
src/components/room-card.js
src/components/room-card.less
src/components/room-card.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1193

EDU-1193 Room related improvements

---

src/plugins/matching-cards/matching-cards-display.js

Closes https://educandu.atlassian.net/browse/EDU-1191

EDU-1191 Adjust matching cards audio play/stop

---

src/components/dashboard/favorites-tab.js
src/components/dashboard/favorites-tab.less
src/components/favorite-star.js
src/components/pages/dashboard.js

Closes https://educandu.atlassian.net/browse/EDU-1210

EDU-1210 Improve dashboard favorites management

---

src/components/pages/search.js
src/components/redaction/redaction-document-tags-tab.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js

Closes https://educandu.atlassian.net/browse/EDU-1201

EDU-1201 Scroll to top after pagination changes in search results table

---

src/api-clients/document-api-client.js
src/server/document-controller.js
src/server/document-controller.spec.js
src/services/document-service.js
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1203

EDU-1203 Fix document edit permissions for maintainers

---

README.md
src/bootstrap/server-config.js
src/services/mail-service.js
src/test-helper.js
test-app/src/index.js

Closes https://educandu.atlassian.net/browse/EDU-1206

EDU-1206 Enable configuring email receiver ignore pattern

---

src/plugins/music-learning-block/music-learning-block.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1214

EDU-1214 Change display name for music-learning-block plugin

---

src/components/document-metadata-modal.js

Closes https://educandu.atlassian.net/browse/EDU-1233

EDU-1233 Fix protected state update rule

---

migrations/educandu-2023-03-14-01-add-messages-to-rooms-collection.js
src/api-clients/room-api-client.js
src/domain/constants.js
src/domain/schemas/room-schemas.js
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/room-service.js
src/services/room-service.spec.js
src/stores/room-store.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1229

EDU-1229 Set up message board backend logic

---

src/components/comments-panel.less
src/components/confirmation-dialogs.js
src/components/confirmation-dialogs.yml
src/components/error-page.js
src/components/pages/doc.less
src/components/pages/room.js
src/components/pages/room.less
src/components/pages/room.yml
src/domain/constants.js
src/plugins/separator/separator.yml
src/resources/resources.json
src/styles/mixins.less
src/ui/hooks.js
test-app/src/custom-components/homepage-template.less

Closes https://educandu.atlassian.net/browse/EDU-1230

EDU-1230 Add message board to room

---

src/plugins/interactive-media/interactive-media-editor.js
src/plugins/quick-tester/quick-tester.less

Closes https://educandu.atlassian.net/browse/EDU-1238

EDU-1238 Fix quick tester buttons wrapping

---

src/components/homepage/homepage-trust-footer.less
src/components/pages/doc.less
src/components/pages/room.js
src/components/pages/room.less
src/components/section-display.less
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1232
**Room owner view**
**Room member view**
Very nice on the eyes :heart_eyes: :laughing:

EDU-1232 Style message board

---

src/components/pages/room.js
src/components/pages/room.less
src/components/pages/room.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1254

EDU-1254 Improve message board display

---

src/api-clients/media-library-api-client.js
src/components/resource-selector/media-library/media-library-file-dropzone.js
src/components/resource-selector/media-library/media-library-file-dropzone.less
src/components/resource-selector/media-library/media-library-metadata-form.js
src/components/resource-selector/media-library/media-library-options.js
src/components/resource-selector/media-library/media-library-options.less
src/components/resource-selector/media-library/media-library-screens.js
src/components/resource-selector/media-library/media-library-search-screen.js
src/components/resource-selector/media-library/media-library-search-screen.less
src/components/resource-selector/room-media/room-media-files-viewer.less
src/components/resource-selector/shared/action-invitation.less
src/components/resource-selector/shared/resource-preview-screen.js
src/components/resource-selector/shared/resource-search-bar.js
src/components/resource-selector/shared/resource-search-bar.less
src/components/resource-selector/shared/resource-search-bar.yml
src/components/resource-selector/shared/selected-resource-display.js
src/components/resource-selector/shared/selected-resource-display.less
src/components/resource-selector/wikimedia/wikimedia-screens.js
src/components/resource-selector/wikimedia/wikimedia-search-screen.js
src/domain/constants.js
src/domain/schemas/media-library-item-schemas.js
src/plugins/audio-waveform/audio-waveform-generator-dialog.js
src/resources/common.yml
src/resources/resources.json
src/server/media-library-controller.js
src/services/media-library-service.js
src/styles/main.less
src/utils/media-library-utils.js
src/utils/wikimedia-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1249

EDU-1249 Media library improvements

---

src/services/saml-config-service.js

Closes https://educandu.atlassian.net/browse/EDU-1258

EDU-1258 Fix Shibboleth authentication

---

src/components/dashboard/storage-tab.js
src/components/dashboard/storage-tab.less
src/components/resource-selector/room-media/room-media-screens.js
src/components/used-storage.js

Closes https://educandu.atlassian.net/browse/EDU-1261

EDU-1261 Have the frontent support the case of no storage plan with used bytes

---

src/services/user-service.js
src/services/user-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1260

EDU-1260 Fix closing of own user account

---

test-app/src/custom-components/homepage-template.less

Closes https://educandu.atlassian.net/browse/EDU-1242

EDU-1242 Ensure hero height in all browsers

---

src/components/pages/room-membership-confirmation.js
src/components/pages/room-membership-confirmation.yml
src/domain/constants.js
src/resources/resources.json
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/room-service.js
src/services/room-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1244

EDU-1244 Ensure rendering of room page is not hindered by members entering through the yet undiscovered back door

---

src/components/markdown-input.yml
src/components/pages/room.js
src/components/resource-selector/resource-selector.js
src/components/resource-selector/room-media/room-media-default-screen.js
src/components/resource-selector/room-media/room-media-screens.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/components/room-media-context.js
src/plugins/media-analysis/media-analysis.yml
src/resources/resources.json
src/server/room-controller.js
src/server/room-controller.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1263

EDU-1263 Fix room context cases

---

src/components/homepage/homepage-oer-presentation.js
src/components/homepage/homepage-oer-presentation.yml
src/components/login-form.js
src/components/login-form.less
src/components/login-form.yml
src/components/navigation-desktop.js
src/components/navigation-desktop.less
src/components/navigation-mobile.js
src/components/navigation-mobile.less
src/components/pages/doc.less
src/components/pages/login.js
src/components/registration-form.js
src/components/registration-form.less
src/components/registration-form.yml
src/plugins/table/table.less
src/resources/common.yml
src/resources/resources.json
src/styles/mixins.less
test-app/src/custom-components/homepage-template.less

Closes https://educandu.atlassian.net/browse/EDU-1248

EDU-1248 Homepage touch-up

---

src/server/document-controller.js

Closes https://educandu.atlassian.net/browse/EDU-1268

EDU-1268 Allow anonymous users to view document history

---

src/components/login-form.less
src/components/pages/reset-password.js
src/components/pages/reset-password.less
src/components/pages/reset-password.yml
src/components/registration-form.js
src/components/registration-form.less
src/components/registration-form.yml
src/components/user-steps-form.js
src/components/user-steps-form.less
src/domain/schemas/user-schemas.js
src/index.js
src/resources/resources.json
src/server/user-controller.js
src/server/user-controller.spec.js
src/services/user-service.js
src/stores/user-store.js

Closes https://educandu.atlassian.net/browse/EDU-1266

EDU-1266 Lock back door

---

src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1273

EDU-1273 Bring beforeUnload back

---

package.json
src/components/diff-view.js
src/components/diff-view.less
src/components/document-version-history.js
src/components/document-version-history.yml
src/components/pages/comparison.js
src/components/pages/comparison.less
src/components/pages/comparison.yml
src/components/pages/document.js
src/components/section-display.js
src/components/sections-display.js
src/domain/page-name.js
src/domain/page-resolver.js
src/plugins/markdown/markdown-info.js
src/plugins/table-of-contents/table-of-contents-display.js
src/plugins/table-of-contents/table-of-contents.less
src/plugins/table-of-contents/table-of-contents.yml
src/resources/common.yml
src/resources/page-names.yml
src/resources/resources.json
src/server/comparison-controller.js
src/server/controller-factory.js
src/styles/main.less
src/ui/default-prop-types.js
src/utils/document-revision-comparison-utils.js
src/utils/document-revision-comparison-utils.spec.js
src/utils/document-utils.js
src/utils/routes.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1259

EDU-1259 Add document revision comparison page

---

src/components/resource-selector/media-library/media-library-screens.js
src/components/resource-selector/media-library/media-library-search-screen.js
src/components/resource-selector/shared/selected-resource-display.js
src/components/resource-selector/shared/selected-resource-display.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1267

EDU-1267 Allow edit initial item in media library

---

src/components/dashboard/storage-tab.js
src/components/media-player/media-volume-slider.js
src/components/pdf-document.js
src/components/redaction/redaction-media-library-tab.js
src/components/resource-selector/media-library/media-library-file-dropzone.js
src/components/resource-selector/media-library/media-library-file-dropzone.less
src/components/resource-selector/media-library/media-library-item-modal.js
src/components/resource-selector/media-library/media-library-search-screen.js
src/components/resource-selector/media-library/media-library-search-screen.yml
src/components/resource-selector/media-library/media-library-upload-screen.js
src/components/resource-selector/room-media/room-media-default-screen.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/components/resource-selector/shared/resource-preview.js
src/components/resource-selector/shared/upload-button.js
src/components/resource-selector/shared/upload-button.less
src/domain/constants.js
src/domain/upload-limit-exceeded-middleware.js
src/plugins/audio-waveform/audio-waveform-generator-dialog.js
src/plugins/pdf-viewer/pdf-viewer-display.js
src/resources/common.yml
src/resources/resources.json
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-1255

EDU-1255 Show upload limit to users

---

src/components/dashboard/activities-tab.js
src/components/dashboard/notifications-tab.js
src/components/document-metadata-modal.js
src/components/empty-state.js
src/components/pages/document.js
src/components/pages/room-membership-confirmation.js
src/components/pages/room.js
src/components/pages/room.less
src/components/pages/room.yml
src/components/room-card.js
src/components/room-creation-modal.js
src/components/room/message-board.js
src/components/room/message-board.less
src/components/room/message-board.yml
src/components/room/room-documents.js
src/components/room/room-documents.less
src/components/room/room-documents.yml
src/components/room/room-members.js
src/components/room/room-members.less
src/components/room/room-members.yml
src/components/room/room-settings.js
src/components/room/room-settings.less
src/components/room/room-settings.yml
src/components/user-card.js
src/resources/resources.json
src/server/room-controller.js
src/services/mail-service.js
src/styles/main.less
src/ui/default-prop-types.js
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1279

EDU-1279 Rework room page

---

src/utils/document-revision-comparison-utils.js
src/utils/string-utils.js
src/utils/string-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1277

EDU-1277 Render a more human-readable text comparison

---

src/domain/validation-constants.js

Closes https://educandu.atlassian.net/browse/EDU-1283

EDU-1283 Increase max length of document short descriptions

---

src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1280

EDU-1280-Wait-for-comments-section-before-scrolling-down

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1274

EDU-1274 Make active accounts table fit into page

---

migrations/educandu-2023-04-03-01-rename-description-to-shortDescription-in-media-library-items-collection.js
src/api-clients/media-library-api-client.js
src/components/pages/search.js
src/components/pages/tests.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js
src/components/resource-info-cell.js
src/components/resource-selector/media-library/media-library-item-modal.js
src/components/resource-selector/media-library/media-library-metadata-display.js
src/components/resource-selector/media-library/media-library-metadata-form.js
src/components/resource-selector/media-library/media-library-screens.js
src/components/resource-selector/media-library/media-library-upload-screen.js
src/domain/schemas/media-library-item-schemas.js
src/domain/validation-constants.js
src/plugins/audio-waveform/audio-waveform-generator-dialog.js
src/resources/common.yml
src/resources/resources.json
src/services/media-library-service.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1275

EDU-1275 Rename description to shortDescription in mediaLibraryItems

---

src/components/error-page.js
src/components/error-page.less
src/components/error-page.yml
src/domain/constants.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1278
I decided against including the logo on this page as I realized we'd be introducing more things that can go wrong.
Kept it simple and instead introduced a "Home" button.
The cases look like this:

EDU-1278 Use empty state on error page

---

src/components/document-version-history.js

Closes https://educandu.atlassian.net/browse/EDU-1286

EDU-1286 Migrate newly introduced Timeline component

---

package.json
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1284

EDU-1284 Update MongoDB to v6

---

src/components/dashboard/activities-tab.js
src/components/dashboard/documents-tab.js
src/components/dashboard/favorites-tab.js
src/components/dashboard/notifications-tab.js
src/components/dashboard/rooms-tab.js
src/components/dashboard/storage-tab.js
src/components/document-comments-panel.js
src/components/favorite-star.js
src/components/homepage/homepage-document-cards.less
src/components/pages/dashboard.js
src/components/pages/dashboard.less
src/components/pages/document.js
src/components/pages/room-membership-confirmation.js
src/components/pages/user-profile.js
src/components/spinner.js
src/components/spinner.less
src/styles/main.less
src/styles/utilities.less
src/ui/hooks.js

Closes https://educandu.atlassian.net/browse/EDU-1287
There are a few bonus commits in here which:
- ensure spinner is visible with the naked eye when fetching data 😄 
- fix overflowing homepage on mobile
- fix misplaced and strange looking avatar on mobile (when user name is wider than the avatar width)

EDU-1287 Fix favorites inconsistent state

---

src/components/room-invitation-creation-modal.js

Close https://educandu.atlassian.net/browse/EDU-1292

EDU-1292 Fix SSR on room members tab

---

migrations/educandu-2023-04-04-01-rename-accreditedEditors-to-allowedEditors-in-documents.js
migrations/educandu-2023-04-04-02-rename-accreditedEditors-to-allowedEditors-in-documents.js
src/components/document-metadata-modal.js
src/components/document-metadata-modal.yml
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-documents-tab.yml
src/domain/data-extractors.js
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/services/client-data-mapping-service.js
src/services/document-service.js
src/services/document-service.spec.js
src/stores/document-store.js
src/test-helper.js
src/ui/default-prop-types.js
src/utils/document-revision-comparison-utils.js
src/utils/document-utils.js
src/utils/document-utils.spec.js
src/utils/revision-utils.js
src/utils/revision-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1293

EDU-1293 Rename accredited editors to allowed editors

---

src/components/pages/batches.js

Closes https://educandu.atlassian.net/browse/EDU-1300

EDU-1300 Remove console warning from react caused by different timestamps rendered on server vs client side

---

src/components/admin/user-accounts-tab.js
src/components/item-panel.js
src/components/pages/batches.js
src/components/resource-selector/shared/files-list-viewer.js
src/components/room/room-documents.js
src/components/section-display.js
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1302

EDU-1302 Remove some unnecessary tooltips

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.less
src/components/admin/user-accounts-tab.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1301
I also changed the actions column content for that tab.
Old:
New:

EDU-1301 Fix storage reminders error and improve actions column content

---

src/utils/document-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1305

EDU-1305 Correct translation keys

---

src/components/media-player/media-duration-cache.js
src/components/media-player/youtube-player.js
src/components/media-player/youtube-thumbnail-url-cache.js

Closes https://educandu.atlassian.net/browse/EDU-1311

EDU-1311 Give up determining media durations after three failed attempts

---

src/components/pages/document.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1310

EDU-1310 Fix spelling mistake

---

src/components/media-player/html5-player.js
src/components/media-player/media-player.js
src/components/media-player/youtube-player.js
src/plugins/matching-cards/matching-cards-tile-display.js

Closes https://educandu.atlassian.net/browse/EDU-1304

EDU-1304 Exclude play icon layer for media player in matching cards

---

src/plugins/matching-cards/matching-cards-tile-display.js

Closes https://educandu.atlassian.net/browse/EDU-1306

EDU-1306 Skip first seeking operation as Youtube gets the hickups otherwise

---

src/server/page-renderer.js

Closes https://educandu.atlassian.net/browse/EDU-1312

EDU-1312 Add timestamp to main script and stylesheet

---

src/components/pages/document.js
src/services/document-service.js
src/services/document-service.spec.js
src/test-helper.js
src/utils/document-utils.js
src/utils/document-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1315

EDU-1315 Allow room owners and collaborators to restore revisions

---

src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1318

EDU-1318 Keep selected revision after hard-deletion

---

src/utils/document-utils.js
src/utils/document-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1322

EDU-1322 Allow only maintainers and admins to restore revisions of public documents

---

src/components/dashboard/documents-tab.js
src/components/dashboard/documents-tab.yml
src/components/empty-state.js
src/components/pages/dashboard.yml
src/resources/resources.json

Close https://educandu.atlassian.net/browse/EDU-1324

EDU-1324 Clarify public documents tab

---

README.md

Closes https://educandu.atlassian.net/browse/EDU-1325

EDU-1325 Fix Github workflow for JIRA labeling step

---

migrations/educandu-2023-10-05-01-add-documentInputs-collection.js
src/api-clients/document-input-api-client.js
src/domain/schemas/document-input-schemas.js
src/server/controller-factory.js
src/server/document-input-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-input-service.js
src/services/document-input-service.spec.js
src/stores/collection-specs/document-inputs.js
src/stores/database.js
src/stores/document-input-store.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1336

EDU-1336 Add document inputs collection

---

src/api-clients/document-input-api-client.js
src/components/document-inputs-panel.js
src/components/document-inputs-panel.yml
src/components/document-version-history.js
src/components/icons/general/inputs-icon.js
src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/domain/constants.js
src/domain/schemas/document-input-schemas.js
src/resources/resources.json
src/server/document-input-controller.js
src/services/document-input-service.js
src/stores/document-input-store.js
src/styles/history-panel.less
src/styles/main.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1339

EDU-1339 Add basic UI for inputs mode

---

src/components/pages/comparison.js
src/components/pages/document.js
src/components/section-display.js
src/components/sections-display.js
src/plugins/select-field/select-field-display.js
src/plugins/select-field/select-field-info.js
src/plugins/text-field/text-field-display.js
src/plugins/text-field/text-field-info.js
src/ui/default-prop-types.js
src/utils/object-utils.js
src/utils/object-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1337

EDU-1337 Collect document inputs on document and comparison pages

---

src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1340

EDU-1340 Simplify document page states for overlapping cases

---

src/components/document-inputs-panel.js
src/components/document-inputs-panel.yml
src/components/document-version-history.js
src/components/document-version-history.yml
src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/components/section-display.js
src/resources/common.yml
src/resources/resources.json
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1341

EDU-1341 submit document inputs

---

src/components/pages/document.less
src/components/section-display.js
src/components/section-display.less

Closes https://educandu.atlassian.net/browse/EDU-1342

EDU-1342 Indicate input sections in display mode

---

src/components/document-inputs-panel.js
src/components/document-inputs-panel.yml
src/components/pages/document.js
src/components/section-display.js
src/components/sections-display.js
src/domain/schemas/document-input-schemas.js
src/plugins/select-field/select-field-display.js
src/plugins/text-field/text-field-display.js
src/resources/resources.json
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1344

EDU-1344 Enable switching between existing inputs

---

migrations/educandu-2023-10-12-01-add-inputSubmittingDisabled-to-documents-and-revisions copy.js
src/components/document-metadata-modal.js
src/components/document-metadata-modal.yml
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/server/document-controller.spec.js
src/server/room-controller.spec.js
src/services/amb-service.spec.js
src/services/document-input-service.js
src/services/document-input-service.spec.js
src/services/document-service.js
src/services/document-service.spec.js
src/services/room-service.spec.js
src/stores/document-store.js
src/test-helper.js
src/ui/default-prop-types.js
src/utils/document-utils.spec.js
src/utils/notification-utils.spec.js
src/utils/revision-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1338

EDU-1338 Allow disabling input submitting

---

src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/resources/resources.json
src/utils/document-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1346

EDU-1346 Switch to view last input after submitting

---

src/components/pages/document-input.js
src/domain/page-name.js
src/domain/page-resolver.js
src/server/document-input-controller.js

Closes https://educandu.atlassian.net/browse/EDU-1348

EDU-1348 Add document-input page

---

src/components/confirmation-dialogs.js
src/components/confirmation-dialogs.yml
src/components/dashboard/document-inputs-tab.js
src/components/dashboard/document-inputs-tab.less
src/components/dashboard/document-inputs-tab.yml
src/components/pages/dashboard.js
src/components/pages/dashboard.yml
src/resources/resources.json
src/server/document-input-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/styles/main.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1349

EDU-1349 Show document inputs on dashboard

---

src/components/document-inputs-panel.js
src/components/document-inputs-panel.yml
src/components/pages/document.js
src/resources/resources.json
src/styles/history-panel.less

Closes https://educandu.atlassian.net/browse/EDU-1347

EDU-1347 Streamline document input UI elements on document page

---

src/api-clients/document-input-api-client.js
src/components/document-inputs-panel.js
src/components/pages/dashboard.js
src/components/pages/dashboard.yml
src/components/pages/document-input.js
src/components/pages/document.js
src/components/pages/room.js
src/components/pages/room.yml
src/components/room/room-document-inputs.js
src/components/room/room-document-inputs.less
src/components/room/room-document-inputs.yml
src/domain/schemas/document-input-schemas.js
src/resources/common.yml
src/resources/resources.json
src/server/document-input-controller.js
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/document-input-service.js
src/stores/document-input-store.js
src/styles/main.less
src/styles/mixins.less
src/utils/document-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1350

EDU-1350 Show document inputs on room page

---

src/components/pages/comparison.js
src/components/pages/document-input.js
src/components/pages/document.js
src/components/section-display.js
src/components/sections-display.js
src/domain/schemas/document-input-schemas.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1356

EDU-1356 Refactor section display props

---

src/api-clients/document-input-api-client.js
src/components/confirmation-dialogs.js
src/components/confirmation-dialogs.yml
src/components/dashboard/document-inputs-tab.js
src/components/document-comments-panel.js
src/components/document-comments-panel.yml
src/components/document-input-section-comments.js
src/components/document-input-section-comments.less
src/components/document-input-section-comments.yml
src/components/room/room-document-inputs.js
src/components/section-display.js
src/components/sections-display.js
src/domain/schemas/document-input-schemas.js
src/resources/common.yml
src/resources/resources.json
src/server/document-input-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-input-service.js
src/services/document-input-service.spec.js
src/styles/main.less
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1351

EDU-1351 Allow comments on document inputs

---

src/api-clients/document-input-api-client.js
src/components/pages/dashboard.js
src/components/pages/document.js
src/domain/schemas/document-input-schemas.js
src/server/document-input-controller.js
src/services/document-input-service.js
src/stores/document-input-store.js

Closes https://educandu.atlassian.net/browse/EDU-1360

EDU-1360 Fix exception for non collaborative rooms

---

src/components/dashboard/notifications-tab.js
src/components/dashboard/notifications-tab.yml
src/domain/constants.js
src/domain/schemas/event-schemas.js
src/resources/resources.json
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-input-service.js
src/services/event-service.js
src/services/notification-service.js
src/stores/document-input-store.js
src/stores/event-store.js
src/test-helper.js
src/utils/notification-utils.js
src/utils/notification-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1357

EDU-1357 Add notifications for document inputs

---

src/domain/schemas/document-input-schemas.js
src/server/document-input-controller.js
src/server/room-controller.js

Closes https://educandu.atlassian.net/browse/EDU-1361

EDU-1361 Add authorize endpoint for document input media

---

src/components/document-inputs-panel.js
src/components/document-inputs-panel.yml
src/components/empty-state.js
src/components/pages/document.js
src/components/resource-selector/media-library/media-library-file-dropzone.js
src/components/resource-selector/media-library/media-library-search-screen.js
src/components/resource-selector/shared/upload-button.js
src/plugins/file-upload-field/file-upload-field-display.js
src/plugins/file-upload-field/file-upload-field.less
src/resources/common.yml
src/resources/resources.json
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-1366

EDU-1366 Polish UI

---

src/api-clients/room-api-client.js
src/components/dashboard/storage-tab.js
src/components/pages/dashboard.js
src/components/resource-selector/room-media/room-media-default-screen.js
src/components/resource-selector/room-media/room-media-screens.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/domain/schemas/room-schemas.js
src/server/document-controller.js
src/server/document-controller.spec.js
src/server/room-controller.js
src/server/room-controller.spec.js
src/server/tests-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/room-service.js
src/services/room-service.spec.js
src/ui/default-prop-types.js
src/utils/storage-utils.js
src/utils/storage-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1363

EDU-1363 Refactor room media overview

---

src/components/dashboard/storage-tab.js
src/components/dashboard/storage-tab.less
src/components/dashboard/storage-tab.yml
src/components/pages/dashboard.js
src/components/pages/room.js
src/components/resource-selector/room-media/room-media-files-viewer.yml
src/components/room/room-document-inputs.js
src/components/room/room-document-inputs.less
src/components/room/room-document-inputs.yml
src/components/room/room-documents.js
src/resources/resources.json
src/styles/mixins.less
src/ui/default-prop-types.js
src/utils/storage-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1368

EDU-1368 Refine storage quota handling

---

src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1367

Update correct data structure in pending document inputs

---

src/components/pages/room.js
src/components/room/room-document-inputs.js
src/server/document-controller.js
src/server/document-controller.spec.js
src/server/room-controller.js
src/server/room-controller.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1369

EDU-1369 Streamline room tab internal state handling and thus fix error on document input deletion

---

src/plugins/select-field/select-field-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1371

EDU-1371 Remove item text from header

---

src/services/room-service.js
src/services/room-service.spec.js
src/stores/document-input-store.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1372

EDU-1372 Delete document inputs when user leaves room

---

src/plugins/plugin-registry.js
src/plugins/whiteboard/whiteboard-display.js
src/plugins/whiteboard/whiteboard-editor.js
src/plugins/whiteboard/whiteboard-icon.js
src/plugins/whiteboard/whiteboard-info.js
src/plugins/whiteboard/whiteboard.yml
src/resources/resources.json
test-app/src/index.js

Closes https://educandu.atlassian.net/browse/EDU-1374

EDU-1374 Prepare whiteboard plugin

---

src/plugins/whiteboard/whiteboard-canvas.js

Closes https://educandu.atlassian.net/browse/EDU-1380

EDU-1380 Clear whiteboard when reseting document input fields

---

src/plugins/whiteboard/whiteboard-canvas.js
src/plugins/whiteboard/whiteboard-toolbar.js
src/plugins/whiteboard/whiteboard.less

Closes https://educandu.atlassian.net/browse/EDU-1381

EDU-1381 Indicate missing fill color in whiteboard toolbar

---

src/plugins/whiteboard/whiteboard-canvas.js

Closes https://educandu.atlassian.net/browse/EDU-1379

EDU-1379 Fix shape change not persisted

---

src/plugins/whiteboard/whiteboard-canvas.js
src/plugins/whiteboard/whiteboard.less

Closes https://educandu.atlassian.net/browse/EDU-1378

EDU-1378 Make whiteboard disable-able

---

src/plugins/whiteboard/whiteboard-canvas.js

Fixes bubu on https://educandu.atlassian.net/browse/EDU-1383

EDU-1383 Prevent an extra onChange call when resetting the whiteboard

---

src/plugins/iframe/iframe-editor.js
src/plugins/iframe/iframe.yml
src/plugins/whiteboard/whiteboard-canvas.js
src/plugins/whiteboard/whiteboard-display.js
src/plugins/whiteboard/whiteboard-editor.js
src/plugins/whiteboard/whiteboard-info.js
src/plugins/whiteboard/whiteboard.less
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1382

EDU-1382 Add border to whiteboard plugin

---

src/components/dashboard/storage-tab.less

Closes https://educandu.atlassian.net/browse/EDU-1384

EDU-1384 Fix mobile glitch on storage tab

---

src/plugins/catalog/catalog-display.js
src/plugins/catalog/catalog-editor.js
src/plugins/catalog/catalog-item-editor.js
src/plugins/catalog/catalog.less
src/plugins/catalog/catalog.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1389

EDU-1389 Adjust catalog plugin

---

src/components/credits-footer.js

Closes https://educandu.atlassian.net/browse/EDU-1386

EDU-1386 Never show license in room document footers

---

src/components/admin/user-accounts-tab.yml
src/components/pages/redaction.yml
src/components/redaction/redaction-tags-tab.yml
src/components/resource-selector/media-library/media-library-file-dropzone.yml
src/components/resource-selector/media-library/media-library-search-screen.yml
src/components/resource-selector/resource-selector.yml
src/components/url-input.yml
src/plugins/audio-waveform/audio-waveform.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1387

EDU-1387 Rename media library translations

---

src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1391

EDU-1391 Support applying all sections when duplicating a document

---

src/components/favorite-star.js
src/components/homepage/homepage-oer-presentation.js
src/components/navigation-desktop.js
src/components/navigation-mobile.js
src/components/registration-form.js
src/server/error-controller.js
src/ui/browser-helper.js
src/ui/hooks.js
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1388

EDU-1388 Do not set a redirect param when logging in from home page

---

src/components/pages/comparison.js
src/components/pages/document.js
src/components/section-display.js
src/components/section-display.less
src/components/sections-display.js

Closes https://educandu.atlassian.net/browse/EDU-1390

EDU-1390 Extend revision view to allow copying of sections

---

src/components/flip-card.js
src/components/flip-card.less
src/components/icons/media-player/stop-icon.js
src/plugins/matching-cards/matching-cards-display.js
src/plugins/matching-cards/matching-cards-tile-display.js
src/plugins/matching-cards/matching-cards.less
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1392

EDU-1392 Adjust matching cards plugin

---

src/components/pages/search.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js
src/components/redaction/redaction-tags-tab.js

Closes https://educandu.atlassian.net/browse/EDU-1399

EDU-1399 Adjust usage of tables with paging to manage the paging state externally

---

src/services/maintenance-service.js
src/services/maintenance-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1398

EDU-1398 Create document-input-media directory on startup

---

src/components/default-page-footer.less
src/components/pages/search.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js
src/components/redaction/redaction-tags-tab.js
src/styles/utilities.less

Closes https://educandu.atlassian.net/browse/EDU-1397

EDU-1397 Fix problem with table page size selector opening under footer and also expanding page height

---

src/components/navigation-desktop.js
src/components/navigation-mobile.js
src/components/pages/index.js
src/components/pages/redaction.js
src/components/pages/search.js
src/components/redaction/constants.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js
src/components/redaction/redaction-tags-tab.js
src/domain/schemas/search-schemas.js
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1394

EDU-1394 Persist search page paging in url

---

src/components/media-player/media-range-selector.js
src/components/media-player/media-range-selector.less
src/components/media-player/timecode-fine-tunning-input.js
src/components/media-player/timecode-fine-tunning-input.less
src/components/media-player/timecode-fine-tunning-input.yml
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-analysis/media-analysis-editor.js
src/resources/resources.json
src/utils/media-utils.js
src/utils/media-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1401

EDU-1401 Change timecode fine tunning approach

---

migrations/educandu-2023-11-02-01-add-allRightsReserved-to-mediaLibraryItems.js
src/api-clients/media-library-api-client.js
src/components/pages/tests.js
src/components/registration-form.js
src/components/resource-selector/media-library/media-library-item-modal.js
src/components/resource-selector/media-library/media-library-metadata-display.js
src/components/resource-selector/media-library/media-library-metadata-form.js
src/components/resource-selector/media-library/media-library-metadata-form.yml
src/components/resource-selector/media-library/media-library-screens.js
src/components/resource-selector/media-library/media-library-upload-screen.js
src/domain/schemas/media-library-item-schemas.js
src/plugins/audio-waveform/audio-waveform-generator-dialog.js
src/resources/common.yml
src/resources/resources.json
src/server/media-library-controller.js
src/services/media-library-service.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1402

EDU-1402 Add allRightsReserved flag to media library items

---

src/components/pages/search.js
src/components/redaction/redaction-documents-tab.js
src/components/redaction/redaction-media-library-tab.js
src/components/redaction/redaction-tags-tab.js

Closes https://educandu.atlassian.net/browse/EDU-1413

EDU-1413 Correct pagination property name

---

src/components/section-display.less
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1414

EDU-1414 Change fix for duplicate document overlay issue in a way that does not break matching cards play

---

src/plugins/whiteboard/whiteboard-toolbar.js

Closes https://educandu.atlassian.net/browse/EDU-1419

EDU-1419 Position whiteboard tooltips to the bottom

---

migrations/educandu-2023-11-06-01-add-dashboardSettings-to-user-collection.js
src/api-clients/user-api-client.js
src/components/dashboard/rooms-tab.js
src/components/dashboard/rooms-tab.less
src/components/dashboard/rooms-tab.yml
src/components/room-card.js
src/components/room-card.yml
src/domain/schemas/user-schemas.js
src/resources/resources.json
src/server/user-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/user-service.js
src/stores/user-store.js

Closes https://educandu.atlassian.net/browse/EDU-1416

EDU-1416 Support hiding/showing rooms on dashboard

---

src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1417

EDU-1417 Make the video overlay more prominent

---

src/components/pages/room.js
src/components/pages/room.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1421

EDU-1421 Rename room document inputs tab

---

migrations/educandu-2023-11-07-01-add-label-to-whiterboard-plugin-sections.js
src/plugins/whiteboard/whiteboard-display.js
src/plugins/whiteboard/whiteboard-editor.js
src/plugins/whiteboard/whiteboard-info.js
src/plugins/whiteboard/whiteboard.less

Closes https://educandu.atlassian.net/browse/EDU-1424

EDU-1424 Add label to whiteboard plugin

---

src/components/pages/document.js
src/components/pages/document.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1422

EDU-1422 Change document page input mode focus header text

---

src/components/room/room-document-inputs.js
src/components/room/room-document-inputs.less

Closes https://educandu.atlassian.net/browse/EDU-1426

EDU-1426 Add filter to document inputs tab on Room page

---

src/plugins/select-field/select-field.less

Closes https://educandu.atlassian.net/browse/EDU-1423

EDU-1423 Align checkboxes and radio buttons with first line

---

src/plugins/whiteboard/whiteboard-toolbar.js

Closes https://educandu.atlassian.net/browse/EDU-1425

EDU-1425 Close color picker popovers after picking in whiteboard plugin toolbar

---

src/components/resource-selector/media-library/media-library-item-modal.js

Closes https://educandu.atlassian.net/browse/EDU-1431

EDU-1431 Clear dialog content when the modal is hidden to prevent playing sound or video

---

src/components/markdown.less
src/plugins/media-analysis/media-analysis.less

Closes https://educandu.atlassian.net/browse/EDU-1433
(Details and screenshots in the JIRA ticket)

EDU-1433 Plugins breaking page width

---

src/components/maintenance/maintenance-documents-tab.js
src/components/maintenance/maintenance-media-library-tab.js
src/components/maintenance/maintenance-tags-tab.js

Closes https://educandu.atlassian.net/browse/EDU-1441

EDU-1441 Show spinner on maintenance page tabs

---

src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/resources/resources.json
src/server/document-controller.js
src/server/document-controller.spec.js
src/server/revision-controller.js
src/server/revision-controller.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1444

EDU-1444 Restrict access to archived documents

---

src/components/media-player/html5-player.js
src/components/media-player/multitrack-media-player.js
src/components/media-player/multitrack-media-player.less
src/components/resource-selector/shared/resource-preview.js
src/components/resource-selector/shared/resource-preview.less

Closes https://educandu.atlassian.net/browse/EDU-1440

EDU-1440 Preloading indicator CDN resources

---

src/components/admin/user-accounts-tab.js
src/components/admin/user-accounts-tab.less
src/components/admin/user-accounts-tab.yml
src/components/pages/dashboard.js
src/components/pages/dashboard.less
src/components/pages/dashboard.yml
src/components/user-role-info.js
src/components/user-role-info.less
src/components/user-role-info.yml
src/resources/common.yml
src/resources/resources.json
src/styles/main.less

Closes https://educandu.atlassian.net/browse/EDU-1452

EDU-1452 Make user role visible

---

src/components/section-display.js

Closes https://educandu.atlassian.net/browse/EDU-1450

EDU-1450 Change key combinations for sections

---

src/components/media-player/media-player.less
src/components/media-player/multitrack-media-player.js
src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis.less
src/plugins/media-analysis/media-analysis.yml
src/resources/resources.json
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1446

EDU-1446 Change media analysis layout

---

src/components/media-player/media-player.js
src/components/request-context.js
src/utils/request-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1455

EDU-1455 Disable fullscreen on Safari version < 17.2

---

migrations/educandu-2023-11-27-01-add-width-to-audio-and-quick-tester-plugins.js
src/plugins/audio/audio-display.js
src/plugins/audio/audio-editor.js
src/plugins/audio/audio-info.js
src/plugins/audio/audio.less
src/plugins/quick-tester/quick-tester-display.js
src/plugins/quick-tester/quick-tester-editor.js
src/plugins/quick-tester/quick-tester-info.js
src/plugins/quick-tester/quick-tester.less
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1454

EDU-1454 Ensure width settings in all plugins

---

migrations/educandu-2023-11-28-01-migrate-media-analysis-to-single-track.js
migrations/educandu-2023-11-30-01-migrate-media-analysis-to-single-track.js
src/components/media-player/multitrack-media-player.js
src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/media-analysis/media-analysis-info.js
src/plugins/media-analysis/media-analysis-info.spec.js
src/plugins/media-analysis/media-analysis-utils.js
src/plugins/media-analysis/media-analysis.less

Closes https://educandu.atlassian.net/browse/EDU-1464

EDU-1464 Migrate media analysis to single track

---

migrations/educandu-2023-11-30-02-add-cdn-resources-to-rooms.js
migrations/educandu-2023-11-30-03-add-cdn-resources-to-settings.js
migrations/educandu-2023-11-30-04-add-cdn-resources-to-users.js
migrations/educandu-2023-11-30-05-clean-up-batches-and-tasks.js
src/components/admin/technical-maintenance-tab.yml
src/components/pages/batches.js
src/domain/constants.js
src/domain/schemas/room-schemas.js
src/domain/schemas/user-schemas.js
src/resources/common.yml
src/resources/resources.json
src/services/batch-service.js
src/services/room-service.js
src/services/room-service.spec.js
src/services/scheduling/batch-task-processors/cdn-resources-consolidation-task-processor.js
src/services/scheduling/batch-task-processors/cdn-resources-consolidation-task-processor.spec.js
src/services/setting-service.js
src/services/user-service.js
src/services/user-service.spec.js
src/stores/room-store.js
src/stores/setting-store.js
src/stores/user-store.js
src/test-helper.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1460

EDU-1460 Collect CDN resources from outside documents

---

src/services/media-library-service.js
src/services/media-library-service.spec.js
src/stores/room-store.js
src/stores/setting-store.js
src/stores/user-store.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1463

EDU-1463 Extend media library item usage determination

---

package.json
src/components/pdf-document.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1481

EDU-1481 Update react-pdf

---

src/plugins/markdown-with-image/markdown-with-image.less

Closes https://educandu.atlassian.net/browse/EDU-1492

EDU-1492 Fix markdown-with-image text flow

---

src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1487

EDU-1487 Do not show audio screen in media analysis

---

src/components/admin/admin-settings-tab.js
src/components/document-comments-panel.js
src/components/document-comments-panel.less
src/components/document-input-section-comments.js
src/components/document-inputs-panel.js
src/components/document-metadata-modal.js
src/components/document-version-history.js
src/components/item-panel.js
src/components/loading-section.js
src/components/maintenance/maintenance-media-library-tab.js
src/components/maintenance/maintenance-tags-tab.js
src/components/media-player/media-range-selector.js
src/components/navigation-desktop.js
src/components/navigation-mobile.js
src/components/navigation-utils.js
src/components/pages/dashboard.js
src/components/spinner.js
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1494

EDU-1494 Revert the rest of the AntD update attempt changes

---

src/components/url-input.js

Closes https://educandu.atlassian.net/browse/EDU-1488

EDU-1488 Prevent sanitizing URLs while typing them

---

src/plugins/combined-multitrack-media/combined-multitrack-media.less
src/plugins/combined-multitrack-media/combined-multitrack-media.yml
src/plugins/multitrack-media/multitrack-media-editor.js
src/plugins/multitrack-media/multitrack-media.less
src/plugins/multitrack-media/multitrack-media.yml
src/resources/resources.json
src/styles/mixins.less

Closes https://educandu.atlassian.net/browse/EDU-1495

EDU-1495 Add disclaimer about track synchrionisation for external sources

---

migrations/educandu-2024-01-09-01-add-allowDragAndDrop-to-file-upload-field-plugin.js
src/plugins/file-upload-field/file-upload-field-display.js
src/plugins/file-upload-field/file-upload-field-editor.js
src/plugins/file-upload-field/file-upload-field-info.js
src/plugins/file-upload-field/file-upload-field.less
src/plugins/file-upload-field/file-upload-field.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1509

EDU-1509 Make drag and drop optional in file upload field plugin

---

src/components/pdf-document.js
src/components/resource-selector/shared/resource-preview.js
src/plugins/pdf-viewer/pdf-viewer-display.js

Closes https://educandu.atlassian.net/browse/EDU-1515

EDU-1515 Different approach to fixing PDF downscaling with the viewport

---

src/components/markdown.less

Closes https://educandu.atlassian.net/browse/EDU-1507

EDU-1507 Fix markdown scrollbars with blockquotes

---

src/components/media-player/youtube-player.js

Closes https://educandu.atlassian.net/browse/EDU-1512
Please see JIRA ticket for comments on this change.

EDU-1512 When buffering youtube before first play, reset start position to cancel out cached position

---

src/components/media-player/track-editor.js
src/plugins/audio/audio-editor.js
src/plugins/ear-training/ear-training-editor.js
src/plugins/image/image-editor.js
src/plugins/markdown-with-image/markdown-with-image-editor.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/video/video-editor.js
src/plugins/whiteboard/whiteboard-editor.js
src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1513

EDU-1513 Fix copyright deletion on focus lost

---

src/components/abc-player.js

Closes https://educandu.atlassian.net/browse/EDU-1523

EDU-1523 Guard against empty ABC code producing no music

---

migrations/educandu-2024-04-04-02-add-documentRatings-collection.js
src/domain/schemas/document-rating-schemas.js
src/server/controller-factory.js
src/server/document-rating-controller.js
src/services/document-rating-service.js
src/stores/collection-specs/document-ratings.js
src/stores/database.js
src/stores/document-rating-store.js
src/stores/document-rating-store.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1528

EDU-1528 Support document ratings in backend

---

migrations/educandu-2024-04-04-01-initial-schema.js
migrations/educandu-2024-04-04-02-add-documentRequests-collection.js
migrations/educandu-2024-04-05-01-add-documentRequests-collection.js
src/domain/constants.js
src/domain/schemas/document-request-schemas.js
src/server/document-controller.js
src/server/document-controller.spec.js
src/services/document-request-service.js
src/services/document-request-service.spec.js
src/stores/collection-specs/document-requests.js
src/stores/database.js
src/stores/document-request-store.js
src/utils/date-utils.js
src/utils/date-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1524

EDU-1524 Collect statistics in documentRequests collection

---

migrations/educandu-2024-04-05-02-add-createdBecause-field-to-document-revisions.js
src/domain/schemas/document-schemas.js
src/domain/validation-constants.js
src/services/client-data-mapping-service.js
src/services/document-service.js

Closes https://educandu.atlassian.net/browse/EDU-1522

EDU-1522 Add createdBecause field to document revisions

---

src/components/icons/icons.js
src/components/locale-context.js
src/components/pages/tests.js
src/components/star-rating.js
src/components/star-rating.less
src/components/star-rating.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1532

EDU-1532 Create star rating component

---

src/components/pages/document.js
src/components/pages/document.less
src/components/star-rating.less
src/server/document-controller.js
src/server/document-controller.spec.js
src/services/document-rating-service.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1529

EDU-1529 Show rating on document page

---

src/api-clients/document-api-client.js
src/api-clients/document-request-api-client.js
src/api-clients/media-library-api-client.js
src/components/icons/icons.js
src/components/maintenance/constants.js
src/components/maintenance/maintenance-documents-tab.js
src/components/maintenance/maintenance-media-library-tab.js
src/components/maintenance/maintenance-statistics-tab.js
src/components/maintenance/maintenance-statistics-tab.less
src/components/maintenance/maintenance-statistics-tab.yml
src/components/maintenance/maintenance-tags-tab.js
src/components/pages/maintenance.js
src/components/pages/maintenance.yml
src/resources/resources.json
src/server/controller-factory.js
src/server/document-controller.js
src/server/document-request-controller.js
src/server/maintenance-controller.js
src/server/media-library-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-request-service.js
src/services/document-service.js
src/stores/document-request-store.js
src/stores/document-request-store.spec.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1525

EDU-1525 Add statistics tab

---

src/components/icons/icons.js
src/components/maintenance/constants.js
src/components/maintenance/maintenance-requests-tab.js
src/components/maintenance/maintenance-requests-tab.less
src/components/maintenance/maintenance-requests-tab.yml
src/components/pages/maintenance.js
src/components/pages/maintenance.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1540

EDU-1540 Rename statistics tab to requests tab

---

src/components/maintenance/maintenance-documents-tab.js
src/components/maintenance/maintenance-tags-tab.js
src/components/pages/tests.js
src/components/resource-info-cell.js
src/components/resource-info-cell.less
src/components/resource-title-cell.js
src/components/star-rating.js
src/components/star-rating.less
src/resources/common.yml
src/resources/resources.json
src/server/document-controller.js
src/services/client-data-mapping-service.js
src/services/document-rating-service.js
src/stores/document-rating-store.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1530

EDU-1530 Show average rating on maintenance page

---

src/api-clients/document-request-api-client.js
src/components/locale-context.js
src/components/maintenance/maintenance-documents-tab.less
src/components/maintenance/maintenance-requests-tab.js
src/components/maintenance/maintenance-requests-tab.less
src/components/maintenance/maintenance-requests-tab.yml
src/components/maintenance/maintenance-tags-tab.less
src/components/pages/maintenance.js
src/domain/schemas/document-request-schemas.js
src/resources/resources.json
src/server/document-request-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-request-service.js
src/services/document-service.js
src/stores/document-request-store.js
src/stores/document-request-store.spec.js
src/ui/default-prop-types.js
src/utils/query-utils.js
src/utils/query-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1534

EDU-1534 Filter requests tab

---

src/components/maintenance/maintenance-requests-tab.js
src/components/maintenance/maintenance-requests-tab.less
src/components/maintenance/maintenance-requests-tab.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1535

EDU-1535 Sort requests data

---

src/api-clients/document-api-client.js
src/components/document-metadata-modal.js
src/components/document-metadata-modal.less
src/components/document-metadata-modal.yml
src/components/icons/icons.js
src/domain/schemas/document-schemas.js
src/domain/validation-constants.js
src/resources/common.yml
src/resources/resources.json
src/server/document-controller.js
src/services/document-service.js
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1544

EDU-1544 Provide metadata change reason

---

src/services/client-data-mapping-service.js

Closes https://educandu.atlassian.net/browse/EDU-1550

EDU-1550 Turn on the light switch

---

src/api-clients/document-api-client.js
src/components/pages/document.js
src/components/pages/document.less
src/components/pages/document.yml
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/server/document-controller.js
src/services/document-service.js

Closes https://educandu.atlassian.net/browse/EDU-1546

EDU-1546 Support extended save of document content

---

src/api-clients/document-api-client.js
src/components/confirmation-dialogs.js
src/components/confirmation-dialogs.yml
src/components/pages/document.js
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/server/document-controller.js
src/services/document-service.js
src/services/document-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1547

EDU-1547 Provide reason upon restoring revision

---

migrations/educandu-2024-04-18-01-clear-documentRatings-collection-once-more.js
src/api-clients/document-ratings-api-client.js
src/components/maintenance/maintenance-documents-tab.js
src/components/pages/document.js
src/components/rating-dialog.js
src/components/rating-dialog.less
src/components/rating-dialog.yml
src/components/resource-info-cell.js
src/components/resource-info-cell.less
src/components/resource-title-cell.js
src/domain/schemas/document-rating-schemas.js
src/resources/common.yml
src/resources/resources.json
src/server/document-rating-controller.js
src/services/client-data-mapping-service.js
src/services/document-rating-service.js
src/stores/document-rating-store.js
src/stores/document-rating-store.spec.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1551

EDU-1551 Rename rating related models and components

---

src/components/document-inputs-panel.js
src/components/document-version-history.js
src/components/document-version-history.yml
src/resources/resources.json
src/styles/history-panel.less

Closes https://educandu.atlassian.net/browse/EDU-1545

EDU-1545 Show revision creation reason in document history panel

---

src/components/maintenance/constants.js
src/components/maintenance/maintenance-document-requests-tab.js
src/components/maintenance/maintenance-document-requests-tab.less
src/components/maintenance/maintenance-document-requests-tab.yml
src/components/pages/maintenance.js
src/components/pages/maintenance.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1555

EDU-1555 Rename requests tab component

---

migrations/educandu-2024-04-19-01-add-documentCategories-collection.js
src/domain/schemas/document-category-schemas.js
src/stores/collection-specs/document-categories.js
src/stores/database.js
src/stores/document-category-store.js

Closes https://educandu.atlassian.net/browse/EDU-1548

EDU-1548 Create document categories collection

---

src/components/icons/icons.js
src/components/maintenance/constants.js
src/components/maintenance/document-category-metadata-modal.js
src/components/maintenance/document-category-metadata-modal.yml
src/components/maintenance/maintenance-document-categories-tab.js
src/components/maintenance/maintenance-document-categories-tab.less
src/components/maintenance/maintenance-document-categories-tab.yml
src/components/pages/maintenance.js
src/components/pages/maintenance.yml
src/components/pages/recent-contributions.js
src/components/resource-selector/resource-selector.js
src/components/url-input.js
src/domain/schemas/document-category-schemas.js
src/domain/validation-constants.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1552

EDU-1552 Add document categories tab

---

src/api-clients/document-category-api-client.js
src/components/maintenance/document-category-metadata-modal.js
src/components/maintenance/document-category-metadata-modal.yml
src/components/maintenance/maintenance-document-categories-tab.js
src/components/url-input.js
src/domain/constants.js
src/domain/schemas/document-category-schemas.js
src/resources/resources.json
src/server/controller-factory.js
src/server/document-category-controller.js
src/services/document-category-service.js
src/stores/document-category-store.js

Closes https://educandu.atlassian.net/browse/EDU-1557

EDU-1557 Support document category creation

---

src/components/pages/batches.js
src/components/pages/batches.yml
src/domain/constants.js
src/resources/resources.json
src/services/batch-service.js
src/services/document-category-service.js
src/services/document-category-service.spec.js
src/services/scheduling/batch-task-processors/cdn-resources-consolidation-task-processor.js
src/services/scheduling/batch-task-processors/cdn-resources-consolidation-task-processor.spec.js
src/stores/document-category-store.js
src/stores/lock-store.js

Closes https://educandu.atlassian.net/browse/EDU-1549

EDU-1549 Manage CDN resources in document categories

---

src/api-clients/document-category-api-client.js
src/components/maintenance/document-category-metadata-modal.js
src/domain/schemas/document-category-schemas.js
src/server/document-category-controller.js
src/services/client-data-mapping-service.js
src/services/document-category-service.js
src/services/document-category-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1560

EDU-1560 Provide document cagetories api endpoints

---

src/api-clients/document-category-api-client.js
src/components/maintenance/document-category-metadata-modal.js
src/components/maintenance/maintenance-document-categories-tab.js
src/components/maintenance/maintenance-document-categories-tab.yml
src/resources/resources.json
src/server/document-category-controller.js
src/services/document-category-service.js

Closes https://educandu.atlassian.net/browse/EDU-1559

EDU-1559 Show existing document categories and support editing

---

src/components/confirmation-dialogs.js
src/components/confirmation-dialogs.yml
src/components/maintenance/maintenance-document-categories-tab.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1558

EDU-1558 Support deleting document category

---

src/components/pages/batches.js
src/components/pages/document-category.js
src/components/pages/document-category.less
src/components/pages/document-category.yml
src/domain/page-name.js
src/domain/page-resolver.js
src/domain/schemas/document-category-schemas.js
src/resources/resources.json
src/server/document-category-controller.js
src/services/client-data-mapping-service.js
src/ui/default-prop-types.js

It's not completely empty like the JIRA ticket says, but shows some bare, un-styled information.
Closes https://educandu.atlassian.net/browse/EDU-1561

EDU-1561 Wire up document category page

---

src/components/document-selector.js
src/components/maintenance/maintenance-document-categories-tab.js
src/components/maintenance/maintenance-document-categories-tab.less
src/components/maintenance/maintenance-document-categories-tab.yml
src/resources/resources.json
src/server/document-category-controller.js
src/services/client-data-mapping-service.js

Closes https://educandu.atlassian.net/browse/EDU-1563

EDU-1563 Support adding documents to a category

---

src/components/maintenance/maintenance-document-categories-tab.js
src/components/maintenance/maintenance-document-categories-tab.yml
src/components/pages/document-category.js
src/components/pages/document-category.less
src/components/pages/document-category.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1564

EDU-1564 Add content to document category page

---

src/components/document-category-display.js
src/components/document-category-display.less
src/components/pages/document.js

Closes https://educandu.atlassian.net/browse/EDU-1565

EDU-1565 Improve document page top section look on mobile

---

src/components/pages/document.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1569

EDU-1569 Correct typo

---

src/components/resource-selector/media-library/media-library-item-modal.js

Closes https://educandu.atlassian.net/browse/EDU-1568

EDU-1568 Fix data mapping in media library item modal

---

src/api-clients/document-api-client.js
src/components/pages/dashboard.js
src/components/pages/user-profile.js
src/components/pages/user-profile.yml
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/server/document-controller.js
src/services/document-service.js
src/stores/document-store.js

Closes https://educandu.atlassian.net/browse/EDU-1572

EDU-1572 Documents on user profile

---

src/components/maintenance/maintenance-documents-tab.js

Closes https://educandu.atlassian.net/browse/EDU-1577

EDU-1577 Always show ratings on the maintenance page's documents tab

---

src/components/maintenance/maintenance-document-requests-tab.js
src/components/maintenance/maintenance-document-requests-tab.less

Closes https://educandu.atlassian.net/browse/EDU-1570

EDU-1570 Show sums per request column

---

src/components/admin/admin-settings-tab.js
src/components/admin/admin-settings-tab.yml
src/components/navigation-desktop.js
src/components/navigation-mobile.js
src/components/navigation-utils.js
src/resources/resources.json
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1574

EDU-1574 Support option to set menu entry for document categories page

---

src/components/document-rating.js
src/components/document-rating.less
src/components/pages/document.js
src/components/pages/document.yml
src/components/pages/tests.js
src/components/rating-dialog.js
src/components/rating-dialog.less
src/components/rating-dialog.yml
src/components/resource-info-cell.js
src/components/star-rating.js
src/components/star-rating.less
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1578

EDU-1578 Show rating details

---

src/components/content-management/content-management-document-requests-tab.js
src/components/document-comments-panel.js
src/components/document-metadata-modal.js
src/components/pages/document.js
src/components/resource-selector/media-library/media-library-search-screen.js
src/domain/permissions.js
src/domain/permissions.spec.js
src/server/document-category-controller.js
src/server/document-comment-controller.js
src/server/document-controller.js
src/server/document-request-controller.js
src/server/media-library-controller.js
src/services/document-service.js
src/utils/document-utils.js
src/utils/revision-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1603

EDU-1603 Split up main maintenance permission

---

src/components/content-management/content-management-media-library-tab.js
src/components/document-metadata-modal.js
src/components/document-metadata-modal.yml
src/components/pages/content-management.js
src/components/pages/content-management.yml
src/components/user-role-info.yml
src/domain/permissions.js
src/domain/permissions.spec.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1604

EDU-1604 Differentiate editor role from maintainer role

---

src/components/resource-selector/media-library/media-library-edit-screen.js
src/components/resource-selector/media-library/media-library-item-modal.js
src/components/resource-selector/room-media/room-media-preview-modal.js
src/components/resource-selector/room-media/room-media-upload-modal.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/components/resource-selector/room-media/room-media-upload-screen.less
src/components/resource-selector/room-media/room-media-upload-screen.yml
src/components/resource-selector/shared/resource-preview-screen.js
src/components/resource-selector/shared/resource-preview-with-metadata.js
src/components/resource-selector/shared/resource-preview-with-metadata.less
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1612

EDU-1612 Show preview in room media upload screen

---

src/components/resource-selector/room-media/room-media-screens.js
src/components/resource-selector/room-media/room-media-upload-modal.js
src/components/resource-selector/room-media/room-media-upload-screen.js

Closes https://educandu.atlassian.net/browse/EDU-1622

EDU-1622 Fix selection lost in multi-upload files in rooms

---

src/components/resource-selector/media-library/media-library-files-dropzone.js
src/components/resource-selector/media-library/media-library-items-modal.js
src/components/resource-selector/media-library/media-library-screens.js
src/components/resource-selector/media-library/media-library-upload-screen.js
src/components/resource-selector/room-media/room-media-screens.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/components/resource-selector/room-media/room-media-upload-screen.yml
src/components/resource-selector/shared/constants.js
src/components/resource-selector/shared/files-upload-viewer.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1618

EDU-1618 Support multi select preview and streamline multi-upload experience

---

src/components/content-management/content-management-media-library-tab.js
src/components/resource-selector/media-library/media-library-items-modal.js
src/components/resource-selector/media-library/media-library-upload-screen.js

Closes https://educandu.atlassian.net/browse/EDU-1623

EDU-1623 Show uploaded files on Content Management page modal

---

src/components/resource-selector/media-library/media-library-files-dropzone.js
src/components/resource-selector/media-library/media-library-upload-screen.js
src/components/resource-selector/room-media/room-media-upload-screen.js
src/components/resource-selector/shared/files-upload-viewer.js

Closes https://educandu.atlassian.net/browse/EDU-1625

EDU-1625 Fix case of no preview visible

---

src/plugins/diagram-net/diagram-net-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1628

EDU-1628 Fix problem with dialog not rendered correctly in diagram plugin

---

src/plugins/whiteboard/whiteboard-canvas.js

Closes https://educandu.atlassian.net/browse/EDU-1631

EDU-1631 Fix whiteboard freedrawing mode

---

src/components/content-management/content-management-documents-tab.js
src/components/content-management/content-management-documents-tab.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1635

EDU-1635 Extend filter matching on Content Management page, Documents tab

---

migrations/educandu-2024-10-28-01-add-multitrackPlayerType-to-combined-multitrack-media-plugin.js
src/components/icons/icons.js
src/components/media-player/default-multitrack-media-player.js
src/components/media-player/default-multitrack-media-player.yml
src/components/media-player/precise-multitrack-media-player.js
src/components/media-player/precise-multitrack-media-player.yml
src/plugins/combined-multitrack-media/combined-multitrack-media-display.js
src/plugins/combined-multitrack-media/combined-multitrack-media-editor.js
src/plugins/combined-multitrack-media/combined-multitrack-media-utils.js
src/plugins/combined-multitrack-media/combined-multitrack-media.less
src/plugins/multitrack-media/multitrack-media-display.js
src/plugins/multitrack-media/multitrack-media-editor.js
src/resources/resources.json
src/styles/multitrack-media-player.less

Closes https://educandu.atlassian.net/browse/EDU-1638

EDU-1638 Integrate precise player in combined multitrack plugin

---

src/domain/multipart-middleware.js
src/stores/s3-client.js

Closes https://educandu.atlassian.net/browse/EDU-1651

EDU-1651 Introduce middleware that corrects multer-s3 bug

---

src/components/locale-context.js
src/components/pages/index.js
src/components/pages/index.less
src/components/pages/index.yml
src/resources/resources.json
src/server/index-controller.js
src/services/document-service.js
src/services/media-library-service.js
src/stores/document-store.js
src/stores/media-library-item-store.js

Closes https://educandu.atlassian.net/browse/EDU-1641

EDU-1641 Add info text to homepage

---

src/domain/permissions.js
src/domain/permissions.spec.js
src/server/user-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
vitest.config.js

Closes https://educandu.atlassian.net/browse/EDU-1654

EDU-1654 Hide user email addresses from non-admin roles

---

src/api-clients/user-api-client.js
src/components/favorite-toggle.js
src/components/icons/icons.js
src/components/pages/room.js
src/components/pages/room.less
src/components/pages/user-profile.js
src/components/pages/user-profile.less
src/components/pages/user-profile.yml
src/domain/schemas/user-schemas.js
src/resources/resources.json
src/server/user-controller.js
src/server/user-controller.spec.js
src/services/mail-service.js
src/services/mail-service.yml

Closes https://educandu.atlassian.net/browse/EDU-1644

EDU-1644 Support sending contact requests

---

migrations/educandu-2024-11-08-01-add-allowContactRequestEmails-to-users-collection.js
src/api-clients/user-api-client.js
src/components/dashboard/settings-tab.js
src/components/dashboard/settings-tab.yml
src/components/document-metadata-modal.yml
src/components/icons/icons.js
src/components/resource-selector/media-library/media-library-metadata-form.yml
src/components/room/room-members.yml
src/domain/schemas/user-schemas.js
src/resources/resources.json
src/server/user-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/user-service.js
src/services/user-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1645

EDU-1645 Support contact requests opt-out

---

migrations/educandu-2024-11-08-01-add-allowContactRequestEmails-to-users-collection.js
src/api-clients/user-api-client.js
src/components/dashboard/settings-tab.js
src/components/dashboard/settings-tab.yml
src/components/document-metadata-modal.yml
src/components/icons/icons.js
src/components/pages/user-profile.js
src/components/pages/user-profile.yml
src/components/resource-selector/media-library/media-library-metadata-form.yml
src/components/room/room-members.yml
src/domain/schemas/user-schemas.js
src/resources/resources.json
src/server/user-controller.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/user-service.js
src/services/user-service.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1646
**Branched out of** https://github.com/educandu/educandu/pull/1206

EDU-1646 Use contact request opt out setting

---

src/api-clients/document-api-client.js
src/components/pages/statistics.js
src/components/statistics/statistics-document-requests-tab.less
src/components/statistics/statistics-user-contributions-tab.js
src/components/statistics/statistics-user-contributions-tab.less
src/components/statistics/statistics-user-contributions-tab.yml
src/domain/schemas/document-schemas.js
src/resources/resources.json
src/server/document-controller.js
src/services/client-data-mapping-service.js
src/services/document-service.js
src/stores/document-revision-store.js
src/stores/document-store.js

Closes https://educandu.atlassian.net/browse/EDU-1656

EDU-1656 Fill user contributions tab

---

migrations/educandu-2024-11-12-01-add-searchTags-to-documents-and-document-revisions.js
migrations/educandu-2024-11-12-02-add-searchTags-to-media-library-items.js
src/domain/schemas/document-schemas.js
src/domain/schemas/media-library-item-schemas.js
src/services/document-service.js
src/services/media-library-service.js
src/stores/collection-specs/documents.js
src/stores/collection-specs/media-library-items.js
src/stores/media-library-item-store.js
src/test-helper.js
src/utils/string-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1660

EDU-1660 Add searchTags alongside tags

---

migrations/educandu-2024-11-12-01-add-searchTags-to-documents-and-document-revisions.js
migrations/educandu-2024-11-12-02-add-searchTags-to-media-library-items.js
package.json
src/services/document-service.js
src/services/media-library-service.js
src/test-helper.js
src/utils/string-utils.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1664

EDU-1664 Create searchTags with transliterate instead of slugify

---

migrations/educandu-2024-11-14-01-add-searchTokens-to-documents-and-document-revisions.js
migrations/educandu-2024-11-14-02-add-searchTokens-to-media-library-items.js
src/domain/schemas/document-schemas.js
src/domain/schemas/media-library-item-schemas.js
src/server/media-library-controller.js
src/server/search-controller.js
src/server/search-controller.spec.js
src/services/document-service.js
src/services/media-library-service.js
src/services/media-library-service.spec.js
src/stores/collection-specs/documents.js
src/stores/collection-specs/media-library-items.js
src/stores/document-store.js
src/stores/media-library-item-store.js
src/test-helper.js
src/utils/query-utils.js
src/utils/query-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1661

EDU-1661 search in search tags

---

src/components/content-management/content-management-documents-tab.js
src/components/document-rating.less
src/components/pages/search.js
src/components/resource-info-cell.js
src/components/resource-info-cell.less
src/server/search-controller.js
src/server/search-controller.spec.js
src/services/client-data-mapping-service.js
src/services/client-data-mapping-service.spec.js
src/services/document-rating-service.js
src/stores/document-rating-store.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1662

EDU-1662 Enrich search results list

---

src/components/pages/index.yml
src/components/pages/search.js
src/components/pages/search.less
src/components/pages/search.yml
src/components/resource-type-cell.less
src/components/tag-selector.js
src/components/tag-selector.less
src/domain/schemas/search-schemas.js
src/resources/resources.json
src/styles/global-variables.less
src/styles/tag.less
src/utils/routes.js

Closes https://educandu.atlassian.net/browse/EDU-1663

EDU-1663 Add extra filter to search results page

---

package.json
src/components/abc-input.js
src/components/abc-input.less
src/components/abc-input.yml
src/components/icons/icons.js
src/components/markdown-help.less
src/components/markdown-input.js
src/components/markdown-input.yml
src/components/markdown-resource-selector.less
src/plugins/abc-notation/abc-notation-editor.js
src/plugins/ear-training/ear-training-editor.js
src/resources/common.yml
src/resources/resources.json
src/styles/mixins.less
src/ui/error-helper.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1682

EDU-1682 Extract ABC editor and use ABC tools

---

src/components/icons/icons.js
src/components/pages/document.js
src/components/room/room-documents.js

Closes https://educandu.atlassian.net/browse/EDU-1676

EDU-1676 Support publishing from document page

---

src/components/dashboard/documents-tab.js
src/components/dashboard/documents-tab.less
src/components/dashboard/documents-tab.yml
src/components/pages/dashboard.js
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1677

EDU-1677 Remove direct way of creating a public document

---

src/components/document-metadata-modal.js
src/components/document-metadata-modal.less
src/components/document-metadata-modal.yml
src/components/pages/room.js
src/components/room/room-documents.js
src/resources/resources.json
src/server/room-controller.js
src/server/room-controller.spec.js
src/services/document-service.js
src/services/user-service.spec.js
src/stores/document-store.js
src/ui/default-prop-types.js

Closes https://educandu.atlassian.net/browse/EDU-1675

EDU-1675 Show publishing conditions in modal dialog

---

package.json
src/components/abc-input.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1684

EDU-1684 Update ABC tools and make code synchronous

---

src/components/document-metadata-modal.js
src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1699

EDU-1699 Fix room resources count in document metadata modal

---

src/services/document-service.js

Closes https://educandu.atlassian.net/browse/EDU-1710

EDU-1710 Truncate validation errors to have minimum payload

---

src/services/document-category-service.js
src/services/room-service.js
src/services/section-helper.js
src/services/setting-service.js
src/services/user-service.js
src/utils/cdn-resource-utils.js
src/utils/cdn-resource-utils.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1711

EDU-1711 Remove URL encoding from CDN resources

---

src/services/media-library-service.js
src/services/media-library-service.spec.js
src/stores/document-category-store.js
src/test-helper.js

Closes https://educandu.atlassian.net/browse/EDU-1712

EDU-1712 Respect document categories CDN resources

---

migrations/educandu-2025-03-28-01-add-mediaTrashItems-collection.js
src/domain/schemas/media-trash-item-schemas.js
src/server/media-library-controller.js
src/services/maintenance-service.js
src/services/maintenance-service.spec.js
src/services/media-library-service.js
src/services/media-library-service.spec.js
src/stores/collection-specs/media-trash-items.js
src/stores/database.js
src/stores/media-library-item-store.js
src/stores/media-trash-item-store.js
src/utils/storage-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1713

EDU-1713 introduce media library item trash

---

README.md
src/bootstrap/server-config.js
src/domain/constants.js
src/services/media-trash-service.js
src/services/scheduling/batch-task-processors/task-processor.js
src/services/scheduling/job-scheduler.js
src/services/scheduling/jobs/cleanup-media-trash-job.js
src/stores/media-trash-item-store.js

Closes https://educandu.atlassian.net/browse/EDU-1716

EDU-1716 Periodically cleanup media trash

---

src/components/media-player/media-player-controls.yml
src/components/pages/room.js
src/components/pages/room.yml
src/components/room/room-document-inputs.js
src/components/room/room-document-inputs.yml
src/components/room/room-media.js
src/components/room/room-media.less
src/components/room/room-media.yml
src/resources/common.yml
src/resources/resources.json
src/server/room-controller.js
src/server/room-controller.spec.js

Closes https://educandu.atlassian.net/browse/EDU-1717

EDU-1717 Add new room media tab

---

migrations/educandu-2025-04-02-01-add-hover-and-reveal-action-in-image-plugin.js
package.json
src/plugins/image/constants.js
src/plugins/image/image-display.js
src/plugins/image/image-editor.js
src/plugins/image/image-info.js
src/plugins/image/image-utils.js
src/plugins/image/image.less
src/plugins/image/image.yml
src/resources/resources.json
src/services/document-service.spec.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1719

EDU-1719 Add new hover and reveal actions to image plugin

---

src/plugins/pdf-viewer/pdf-viewer-display.js
src/plugins/pdf-viewer/pdf-viewer.less
src/plugins/pdf-viewer/pdf-viewer.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1718

EDU-1718 Enable PDF download in PDF plugin

---

src/components/media-library-item-cache.js
src/utils/source-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1721

EDU-1721 Create media library item cache

---

src/plugins/catalog/catalog-item-editor.js

Closes https://educandu.atlassian.net/browse/EDU-1725

EDU-1725 Add missing link button in markdown field

---

src/api-clients/media-library-api-client.js
src/components/icons/icons.js
src/components/media-player/media-hooks.js
src/components/media-player/media-info-dialog.js
src/components/media-player/media-info-dialog.less
src/components/media-player/media-info-dialog.yml
src/components/media-player/media-player-controls.js
src/components/media-player/media-player.js
src/components/resource-selector/media-library/media-library-metadata-display.js
src/components/resource-selector/media-library/media-library-metadata-display.yml
src/plugins/audio/audio-display.js
src/plugins/ear-training/ear-training-display.js
src/plugins/interactive-media/interactive-media-display.js
src/plugins/interactive-media/interactive-media-editor.js
src/plugins/media-analysis/media-analysis-display.js
src/plugins/media-analysis/media-analysis-editor.js
src/plugins/media-slideshow/media-slideshow-display.js
src/plugins/media-slideshow/media-slideshow-editor.js
src/plugins/video/video-display.js
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1722

EDU-1722 Add media info button to single track media players

---

migrations/educandu-2025-04-09-01-add-index-for-url-on-mediaLibraryItems-collection.js
src/stores/collection-specs/media-library-items.js

Closes https://educandu.atlassian.net/browse/EDU-1726

EDU-1726 Add index for url on mediaLibraryItems collection

---

src/styles/utilities.less

Closes https://educandu.atlassian.net/browse/EDU-1727

EDU-1727 Restrict modals on mobile to 90% width

---

src/components/media-player/media-player-controls.js

Closes https://educandu.atlassian.net/browse/EDU-1729

EDU-1729 Make play and pause button of media player bigger

---

README.md
migrations/educandu-2025-04-10-01-add-searchRequests-collection.js
src/api-clients/search-request-api-client.js
src/bootstrap/server-config.js
src/domain/schemas/search-request-schemas.js
src/server/search-controller.js
src/server/search-controller.spec.js
src/server/search-request-controller.js
src/services/search-request-service.js
src/stores/collection-specs/search-requests.js
src/stores/database.js
src/stores/search-request-store.js

Closes https://educandu.atlassian.net/browse/EDU-1731

EDU-1731 Persist search requests

---

src/components/pages/statistics.js
src/components/pages/statistics.yml
src/components/statistics/constants.js
src/components/statistics/statistics-search-requests-tab.js
src/components/statistics/statistics-search-requests-tab.less
src/components/statistics/statistics-search-requests-tab.yml
src/resources/resources.json
src/server/controller-factory.js
src/server/search-request-controller.js
src/stores/search-request-store.js
src/utils/query-utils.js
src/utils/string-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1732

EDU-1732 Create search requests tab

---

package.json
src/plugins/whiteboard/whiteboard-canvas.js
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1733

EDU-1733 Pin last working fabric version

---

src/components/credits-footer.js
src/components/credits-footer.yml
src/components/url-input.js
src/components/url-input.yml
src/resources/common.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1734

EDU-1734 Change credit footer label text

---

src/components/pages/search.js
src/components/pages/search.yml
src/resources/resources.json

Closes https://educandu.atlassian.net/browse/EDU-1735

EDU-1706 Change empty data text in search result table

---

src/plugins/catalog/catalog.less
src/styles/global-variables.less

Closes https://educandu.atlassian.net/browse/EDU-1736

EDU-1736 Darken description color in catalog plugin

---

src/components/extended-aspect-ratio-picker.js
src/components/extended-aspect-ratio-picker.less
src/domain/constants.js
src/plugins/whiteboard/whiteboard-display.js
src/plugins/whiteboard/whiteboard-editor.js
src/plugins/whiteboard/whiteboard-info.js
src/utils/aspect-ratio-utils.js

Closes https://educandu.atlassian.net/browse/EDU-1737

EDU-1737 Extend available aspect ratios for whiteboards

---

gulpfile.js
src/common/logger.js
src/test-setup.js

Closes https://educandu.atlassian.net/browse/EDU-1738

EDU-1738 Set default log level to info

---

migrations/educandu-2025-04-22-01-set-reveal-action-in-all-image-plugins-to-switch.js

Closes https://educandu.atlassian.net/browse/EDU-1740

Set reveal action for reveal effect in image plugins to switch

---

package.json
yarn.lock

Closes https://educandu.atlassian.net/browse/EDU-1746

EDU-1746 Update dev-tools to v14.2.0
