educandu/educandu

- README.md
- migrations/2021-11-05-01-add-archived-flag.js
- src/components/pages/docs.js
- src/domain/schemas/document-schemas.js
- src/services/document-service.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-42
> EDU-42 Add archived flag to documents

- src/components/link-popover.js
- src/components/page.js
- src/components/page.less
Closes https://educandu.atlassian.net/browse/EDU-55
> EDU-55 Reorganize header menus

- migrations/2021-11-09-01-clean-up-settings.js
- src/components/link-popover.js
- src/components/pages/index.js
- src/components/pages/index.yml
- src/components/settings/home-languages-settings.js
- src/components/settings/home-languages-settings.yml
- src/resources/resources.json
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-53
> Feature/EDU-53 Make search box independent from settings

- src/components/pages/index.js
- src/components/pages/search.js
Resolves: https://educandu.atlassian.net/browse/EDU-96
> EDU-96 Prefill filters on search results

- README.md
- src/bootstrap/server-config.js
- src/test-helper.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-102
> EDU-102 Add import config

- src/services/document-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-108
> EDU-108 Fix duplicate key issue

- README.md
- package.json
- src/bootstrap/server-config.js
- src/components/link-popover.js
- src/components/restricted.js
- src/domain/api-key-strategy.js
- src/domain/built-in-users.js
- src/domain/needs-permission-middleware.js
- src/domain/permissions.js
- src/domain/permissions.spec.js
- src/domain/private-data.js
- src/server/controller-factory.js
- src/server/user-controller.js
- src/ui/hooks.js
- test-app/index.js
- yarn.lock
Resolves [EDU-106](https://educandu.atlassian.net/browse/EDU-106)
> EDU-106 Enable API key authentication

- src/components/pages/doc.js
- src/domain/permissions.js
Closes https://educandu.atlassian.net/browse/EDU-117
> EDU-117 Fix showing revisions slider for non admin users

- package.json
- src/bootstrap/server-bootstrapper.js
- src/domain/api-key-strategy.js
- src/server/export-controller.js
- src/server/import-controller.js
- src/services/export-api-client.js
- src/services/import-service.js
- src/services/import-service.spec.js
- src/stores/database.js
- test-app/index.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-122
> EDU-122 set up database schema hash

- migrations/educandu-2021-11-24-01-create-task-processing-collections.js
- src/common/constants.js
- src/components/pages/import.js
- src/domain/schemas/document-schemas.js
- src/domain/schemas/import-schemas.js
- src/server/import-controller.js
- src/services/import-api-client.js
- src/services/import-service.js
- src/services/import-service.spec.js
- src/stores/batch-lock-store.js
- src/stores/batch-store.js
- src/stores/collection-specs/batch-locks.js
- src/stores/collection-specs/batches.js
- src/stores/collection-specs/task-locks.js
- src/stores/collection-specs/tasks.js
- src/stores/database.js
- src/stores/lock-store-base.js
- src/stores/store-base.js
- src/stores/task-lock-store.js
- src/stores/task-store.js
- src/stores/transaction-runner.js
The "think hard about the indices" part I left for the story where we need indices, because I might think hard but wrong in advance :-)
> EDU-123 Persist batch and tasks

- README.md
- src/bootstrap/server-config.js
- src/common/constants.js
- src/components/page.js
Closes https://educandu.atlassian.net/browse/EDU-132
> EDU-132 Add feature disabling logic and suport for disabling import

- README.md
- migrations/educandu-2021-11-29-01-migrate-email-provider-index.js
- src/bootstrap/server-config.js
- src/components/pages/import.js
- src/domain/schemas/export-schemas.js
- src/domain/schemas/import-schemas.js
- src/server/client-data-mapper.js
- src/server/export-controller.js
- src/server/import-controller.js
- src/services/batch-processor.js
- src/services/document-import-task-processor.js
- src/services/export-api-client.js
- src/services/export-service.js
- src/services/import-api-client.js
- src/services/import-service.js
- src/services/import-service.spec.js
- src/services/task-processor.js
- src/services/user-service.js
- src/stores/collection-specs/users.js
- src/utils/urls.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-126
> EDU-126 Document import task processor

- src/services/batch-processor.js
- src/services/batch-processor.spec.js
- src/services/task-processor.js
- src/services/task-processor.spec.js
Closes https://educandu.atlassian.net/browse/EDU-136
> EDU-136 Test batch and task processors

- src/domain/schemas/export-schemas.js
- src/server/export-controller.js
- src/services/document-import-task-processor.js
- src/services/export-api-client.js
- src/services/export-service.js
- src/services/export-service.spec.js
Resolves: https://educandu.atlassian.net/browse/EDU-142
> EDU-142 Exclude imported revision from document export

- src/server/export-controller.js
- src/services/export-service.js
- src/services/export-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-143
> EDU-143 Return cdnRootUrl with document export

- src/server/import-controller.js
Closes: https://educandu.atlassian.net/browse/EDU-146
> EDU-146 Fix payload too large issue

- src/components/pages/users.js
- src/components/pages/users.yml
- src/components/user-role-tag-editor.js
- src/resources/resources.json
- src/server/user-request-handler.js
- src/server/user-request-handler.spec.js
- src/services/user-service.js
Resolves https://educandu.atlassian.net/browse/EDU-140
> EDU-140 Show external users in separate tab

- src/components/pages/import-batch-view.js
- src/server/import-controller.js
- src/services/import-api-client.js
Closes: https://educandu.atlassian.net/browse/EDU-145
> EDU-145 Add polling on batch view

- jest.config.js
- migrations/educandu-2021-12-03-add-document-origin-url.js
- src/repositories/aws-sdk-s3-client.js
- src/repositories/cdn.js
- src/repositories/minio-s3-client.js
- src/server/document-controller.js
- src/services/document-import-task-processor.js
- src/services/document-import-task-processor.spec.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/services/task-processor.js
- src/services/task-processor.spec.js
- src/stores/store-base.js
- src/test-helper.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-139
> EDU-139 implement document import task processor part 2

- package.json
- src/components/pages/import-batch-creation.js
- src/components/pages/search.js
- src/server/document-controller.js
- src/utils/urls.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-147
Bundle size before: 3254.89 kB
Bundle size after: 2738.75 kB
> EDU-147 Remove urlencode package

- src/services/document-service.js
- src/stores/database.js
Fixes https://educandu.atlassian.net/browse/EDU-153
> EDU-153 Prevent external documents being edited and fix db hash generation

- src/components/pages/edit-doc.js
Closes https://educandu.atlassian.net/browse/EDU-144
> EDU-144 Change back button on edit-doc page to cancel

- package.json
- src/common/priority-queue.js
- src/components/pages/import-batch-view.js
- src/server/export-controller.js
- src/services/batch-processor.js
- src/services/task-processor.js
- src/services/task-processor.spec.js
- src/services/task-scheduler.js
- src/ui/default-prop-types.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-154
> EDU-154 Correct task processing error handling

- package.json
- src/repositories/cdn.js
- src/services/document-import-task-processor.js
- yarn.lock
Closes: https://educandu.atlassian.net/browse/EDU-152
> EDU-152 error in document import

- gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-160
> EDU-160 Add confirmation to migration task

- gulpfile.js
- package.json
- src/repositories/cdn.js
- src/services/cdn-api-client.js
- src/services/document-api-client.js
- src/services/export-api-client.js
- src/services/http-client.js
- src/services/import-api-client.js
- src/services/setting-api-client.js
- src/services/user-api-client.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-155
Due to the fact that this ticket required multiple possibly breaking changes, I would suggest we hold off on merging until the Import epic is on ELMU and OMA staging.
> EDU-155 Replace superagent with axios

- src/components/pages/search.js
- src/server/document-controller.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/ui/default-prop-types.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-151
> EDU-151 Introduce minus operator in search

- migrations/automatic/educandu-2021-12-08-01-migrate-settings-to-new-format.js
Closes: https://educandu.atlassian.net/browse/EDU-174
> EDU-174 Fix null pointer exception on settings migration

- src/components/pages/import-batches.js
- src/components/pages/import-batches.yml
- src/resources/resources.json
Closes: https://educandu.atlassian.net/browse/EDU-161
> EDU-161 Add message for missing import sources

- gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-173
> EDU-173 Wait for child process to exit when stopping gulp

- src/components/pages/docs.js
- src/components/pages/docs.yml
- src/resources/resources.json
- src/server/document-controller.js
Closes:  https://educandu.atlassian.net/browse/EDU-180
> EDU-180 Fix viewing documents that do not have slugs

- migrations/automatic/educandu-2021-12-10-01-add-import-related-indexes.js
- src/stores/collection-specs/tasks.js
Closes: https://educandu.atlassian.net/browse/EDU-166
I've added only this index since this is the only query we have so far that takes a long time. Other indexes I considered:
task.processed (no query so far)
task.taskType (no use case)
batches.batchType (we only have one type of batch so far)
> EDU-166 Add Import indexes

- src/services/document-service.js
- src/services/document-service.spec.js
- src/test-helper.js
Closes https://educandu.atlassian.net/browse/EDU-175
> EDU-175 Update CDN resources after hard-deleting revision content

- README.md
- src/bootstrap/server-config.js
- src/components/cookie-consent-drawer.js
- src/components/cookie-consent-drawer.less
- src/components/cookie-consent-drawer.yml
- src/components/default-page-template.js
- src/resources/common.yml
- src/resources/resources.json
- src/styles/main.less
- src/ui/default-prop-types.js
- test-app/index.js
Closes: https://educandu.atlassian.net/browse/EDU-178
> EDU-178 Add cookie consent drawer

- migrations/manual/educandu-2021-12-14-01-migrate-cdn-resources-once-more.js
- migrations/manual/educandu-2021-12-14-01-migrate-cdn-resources-once-more.spec.js
Closes https://educandu.atlassian.net/browse/EDU-182
> EDU-182 Add migration script for regenerating cdnResources

- migrations/automatic/educandu-2021-12-15-01-migrate-settings-to-new-format-once-more.js
- migrations/manual/educandu-2021-12-13-01-make-cdn-urls-generic.js
- migrations/manual/educandu-2021-12-13-01-make-cdn-urls-generic.spec.js
- migrations/manual/educandu-2021-12-14-01-migrate-cdn-resources-once-more.js
These are the scripts changes we already ran from local.
> HOTFIX Correct migration scripts

- src/plugins/annotation/annotation.less
- src/plugins/annotation/markdown.less
- src/plugins/markdown/markdown.less
- src/styles/main.less
Closes: https://educandu.atlassian.net/browse/EDU-191
> EDU-191 Fix image width in markdown

- src/services/import-service.spec.js
Fixes https://educandu.atlassian.net/browse/EDU-194
> EDU-194 Wait for code to finish before exiting the test

- migrations/manual/educandu-2021-12-16-01-make-cdn-urls-generic-in-annotations.js
- migrations/manual/educandu-2021-12-16-01-make-cdn-urls-generic-in-annotations.spec.js
- migrations/manual/educandu-2021-12-16-02-migrate-cdn-resources-due-to-annotations.js
- migrations/manual/educandu-2021-12-16-02-migrate-cdn-resources-due-to-annotations.spec.js
- src/plugins/annotation/display/annotation-display.js
- src/plugins/annotation/info.js
Closes https://educandu.atlassian.net/browse/EDU-190
> EDU-190 Migrate CDN URLs in annotations

- gulpfile.js
- jest.config.js
Closes https://educandu.atlassian.net/browse/EDU-188
> EDU-188 Log skipped migrations

- src/components/pages/edit-doc.js
Closes https://educandu.atlassian.net/browse/EDU-202
> EDU-202 Fix error duplicating document sections

- dev/helpers.js
- dev/minio-helper.js
Closes https://educandu.atlassian.net/browse/EDU-201
> EDU-201 Fix socket hangup

- package.json
- src/server/cdn-controller.js
- src/utils/file-name-helper.js
- src/utils/file-name-helper.spec.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-192
> EDU-192 Escape non-url-characters in file upload

- src/bootstrap/server-config.js
- src/common/constants.js
- src/components/document-import-table.js
- src/components/document-import-table.yml
- src/components/pages/docs.js
- src/components/pages/docs.yml
- src/components/pages/import-batch-view.js
- src/components/pages/import-batch-view.yml
- src/components/pages/import-batches.js
- src/components/pages/import-batches.yml
- src/components/pages/my-space.js
- src/components/pages/my-space.yml
- src/components/pages/search.js
- src/components/pages/search.yml
- src/components/pages/users.js
- src/components/pages/users.yml
- src/components/rooms-tab.js
- src/components/rooms-tab.less
- src/components/rooms-tab.yml
- src/resources/common.yml
- src/resources/resources.json
- src/server/room-controller.js
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-165
> EDU-165 Add rooms tab

- src/domain/schemas/document-schemas.js
- src/domain/schemas/export-schemas.js
- src/domain/schemas/import-schemas.js
- src/domain/schemas/rooms-schemas.js
- src/domain/schemas/rooms-schemas.spec.js
- src/domain/schemas/shared-schemas.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/mail-service.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-168
> EDU-168 Add endpoint for creating invitations and sending the link

- src/components/pages/room.js
- src/components/pages/room.yml
- src/domain/page-name.js
- src/domain/page-resolver.js
- src/domain/permissions.js
- src/domain/schemas/rooms-schemas.js
- src/resources/page-names.yml
- src/resources/resources.json
- src/server/client-data-mapper.js
- src/server/client-data-mapper.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/ui/default-prop-types.js
Closes: https://educandu.atlassian.net/browse/EDU-196
> EDU-196 room details page

- src/components/pages/docs.js
- src/components/pages/docs.less
- src/components/room-creation-modal.js
- src/components/room-creation-modal.yml
- src/components/rooms-tab.js
- src/components/rooms-tab.less
- src/components/rooms-tab.yml
- src/resources/common.yml
- src/resources/resources.json
- src/services/room-api-client.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-205
> EDU-205 Add button to create room

- src/server/cdn-controller.js
- src/server/document-controller.js
- src/server/export-controller.js
- src/server/i18n-controller.js
- src/server/import-controller.js
- src/server/index-controller.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/server/settings-controller.js
- src/server/user-agent-controller.js
- src/server/user-controller.js
Closes https://educandu.atlassian.net/browse/EDU-213
> EDU-213 Streamline controllers

- src/bootstrap/server-config.js
- src/server/user-controller.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-217
> EDU-217 Create optional config entry for session cookie domain

- src/components/default-page-template.js
Closes https://educandu.atlassian.net/browse/EDU-203
> EDU-203 Show help page to all users

- migrations/automatic/educandu-2021-12-28-01-remove-duplicate-tags.js
Closes https://educandu.atlassian.net/browse/EDU-157
> EDU-157 Migrate duplicate tags

- src/server/document-controller.js
Closes: https://educandu.atlassian.net/browse/EDU-233
> EDU-233 Allow unauthenticated users to view docs

- README.md
- src/bootstrap/server-config.js
- src/components/pages/my-space.js
- src/domain/constants.js
- src/server/my-space-controller.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/ui/default-prop-types.js
- test-app/index.js
Closes: https://educandu.atlassian.net/browse/EDU-221
I've updated this OMA story with the necessary changes and octopus:
https://educandu.atlassian.net/browse/OMA-25
I've update this ELMU story (octopus will be updated then)
https://educandu.atlassian.net/browse/ELMU-28
> EDU-221 Introduce areRoomsEnabled config

- migrations/automatic/educandu-2022-01-04-01-create-lessons-collection.js
- src/domain/schemas/document-schemas.js
- src/domain/schemas/document-schemas.spec.js
- src/domain/schemas/lesson-schemas.js
- src/domain/schemas/lesson-schemas.spec.js
- src/domain/schemas/shared-schemas.js
- src/domain/schemas/shared-schemas.spec.js
- src/stores/collection-specs/lessons.js
- src/stores/database.js
- src/stores/lesson-store.js
- src/stores/lesson-store.spec.js
Closes: https://educandu.atlassian.net/browse/EDU-232
> EDU-232 Add lessons collection

- src/server/user-controller.js
Closes https://educandu.atlassian.net/browse/EDU-234
> EDU-234 Change session cookie name

- migrations/automatic/educandu-2022-01-04-02-change-user-indices.js
- src/services/user-service.js
- src/stores/collection-specs/users.js
Closes https://educandu.atlassian.net/browse/EDU-215
> EDU-215 Make user emails unique

- src/components/default-page-template.js
- src/services/document-service.js
- src/ui/global-alerts.js
Closes https://educandu.atlassian.net/browse/EDU-237
> EDU-237 Fix validation error

- src/components/pages/room.js
- src/components/pages/room.less
- src/components/pages/room.yml
- src/resources/resources.json
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/lesson-service.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-231
> EDU-231 Change room page layout

- gulpfile.js
- package.json
- src/server/room-controller.js
- src/server/room-controller.spec.js
- test-app/index.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-236
> EDU-236 Use Lambda@Edge dev server locally

- src/components/pages/doc.js
- src/components/pages/edit-doc.js
Closes https://educandu.atlassian.net/browse/EDU-240
> EDU-240 Fix duplicate alerts on document pages

- src/api-clients/room-api-client.js
- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/pages/room.js
- src/components/pages/room.yml
- src/domain/permissions.js
- src/domain/schemas/rooms-schemas.js
- src/resources/resources.json
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/mail-service.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/ui/default-prop-types.js
Closes: https://educandu.atlassian.net/browse/EDU-199
For testing I suggest that after going through the invitation process, you save your room collection and reintroduce it.
> EDU-199 Add room deletion

- src/components/rooms-tab.js
Closes: https://educandu.atlassian.net/browse/EDU-199
> EDU-199 Fix permissions CREATE_ROOM to OWN_ROOM

- src/components/document-metadata-editor.js
Closes https://educandu.atlassian.net/browse/EDU-248
> EDU-248 Change document-metadata-editor into a functional component

- src/server/user-agent-controller.js
Closes https://educandu.atlassian.net/browse/EDU-257
> EDU-257 Improve redirect log message

- src/components/pages/lesson.js
- src/components/pages/lesson.less
- src/components/pages/room.js
- src/domain/page-name.js
- src/domain/page-resolver.js
- src/domain/schemas/document-schemas.js
- src/domain/schemas/lesson-schemas.js
- src/domain/schemas/room-schemas.js
- src/domain/schemas/room-schemas.spec.js
- src/resources/page-names.yml
- src/resources/resources.json
- src/server/controller-factory.js
- src/server/document-controller.js
- src/server/lesson-controller.js
- src/server/room-controller.js
- src/services/lesson-service.js
- src/styles/main.less
- src/utils/urls.js
- src/utils/urls.spec.js
Closes https://educandu.atlassian.net/browse/EDU-245
> EDU-245 Add empty lesson page

- package.json
- src/components/color-picker.js
- src/ui/color-helper.js
- yarn.lock
Closes: https://educandu.atlassian.net/browse/EDU-259
> EDU-259 Remove color js

- src/domain/schemas/import-schemas.js
Closes https://educandu.atlassian.net/browse/EDU-261
> EDU-261 Correct import document schema

- src/api-clients/lesson-api-client.js
- src/components/document-import-table.js
- src/components/document-import-table.yml
- src/components/document-metadata-editor.js
- src/components/document-metadata-editor.yml
- src/components/language-context.js
- src/components/lesson-creation-modal.js
- src/components/lesson-creation-modal.yml
- src/components/localization/language-select.js
- src/components/pages/doc.js
- src/components/pages/doc.yml
- src/components/pages/docs.js
- src/components/pages/docs.yml
- src/components/pages/room.js
- src/components/pages/search.js
- src/components/pages/search.yml
- src/components/settings/special-page-settings.js
- src/components/settings/special-page-settings.yml
- src/domain/schemas/lesson-schemas.js
- src/plugins/annotation/annotation.yml
- src/plugins/annotation/editing/annotation-editor.js
- src/plugins/ear-training/ear-training.yml
- src/plugins/ear-training/editing/ear-training-editor.js
- src/resources/common.yml
- src/resources/resources.json
- src/server/lesson-controller.js
- src/services/lesson-service.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-246
> EDU-246 Add new lesson button

- src/components/document-creation-modal.js
- src/components/document-creation-modal.yml
- src/components/pages/docs.js
- src/components/pages/settings.js
- src/components/pages/settings.yml
- src/resources/resources.json
- src/server/document-controller.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-241
> EDU-241 Set up document blueprint

- src/components/pages/index.js
- src/components/pages/index.less
- src/components/pages/settings.js
- src/components/pages/settings.less
- src/components/pages/settings.yml
- src/components/settings/special-page-settings.js
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-244
> EDU-244 Add homepage info section

- src/server/page-renderer.js
Closes https://educandu.atlassian.net/browse/EDU-265
> EDU-265 Add cache headers to HTML pages and remove client side hook

- src/server/client-data-mapper.js
- src/server/client-data-mapper.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/ui/default-prop-types.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-239
> EDU-239 Fix prop types warnings

- package.json
- src/components/language-context.js
- src/services/room-service.js
- src/services/user-service.js
- src/stores/document-lock-store.js
- src/stores/lock-store-base.js
- src/stores/maintenance-lock-store.js
- src/stores/task-lock-store.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-263
> EDU-263 Use moment instead of date-fns

- dev/docker-container.js
- src/api-clients/search-api-client.js
- src/components/document-import-table.js
- src/components/document-metadata-editor.js
- src/components/language-flag-and-name.js
- src/components/localization/country-flag-and-name.less
- src/components/localization/language-select.js
- src/components/pages/browser-not-supported.js
- src/components/pages/docs.js
- src/components/pages/index.js
- src/components/pages/index.less
- src/components/pages/index.yml
- src/components/pages/search.js
- src/components/pages/search.less
- src/components/search-bar.js
- src/components/search-bar.less
- src/components/search-bar.yml
- src/components/settings/footer-links-settings.js
- src/components/settings/special-page-settings.js
- src/components/ui-language-dialog.js
- src/domain/schemas/document-schemas.js
- src/domain/schemas/search-schemas.js
- src/resources/resources.json
- src/server/controller-factory.js
- src/server/document-controller.js
- src/server/search-controller.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/styles/main.less
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-266
> EDU-266 Execute search after loading search page

- src/components/cookie-consent-drawer.js
- src/components/cookie-consent-drawer.less
- src/components/cookie-consent-drawer.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-271
> EDU-271 Redesign cookie consent drawer

- src/common/github-flavored-markdown.js
Closes https://educandu.atlassian.net/browse/EDU-279
> EDU-279 Optimize markdown features for performance

- migrations/educandu-2022-01-23-01-add-room-description.js
- src/api-clients/room-api-client.js
- src/components/markdown-textarea.js
- src/components/markdown-textarea.less
- src/components/pages/room-membership-confirmation.js
- src/components/pages/room.js
- src/components/pages/room.less
- src/components/pages/settings.js
- src/components/pages/settings.less
- src/components/room-creation-modal.js
- src/components/room-metadata-form.js
- src/components/rooms-tab.js
- src/domain/schemas/lesson-schemas.js
- src/domain/schemas/room-schemas.js
- src/resources/common.yml
- src/resources/resources.json
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/styles/main.less
- src/ui/default-prop-types.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-277
> EDU-277 Add room description

- README.md
- gulpfile.js
- src/bootstrap/server-config.js
- src/components/markdown.less
- src/components/pages/settings.yml
- src/resources/resources.json
- src/server/user-controller.js
- src/styles/elements.less
- src/styles/global-variables.less
- src/test-helper.js
- src/utils/request-helper.js
- test-app/index.js
Closes https://educandu.atlassian.net/browse/EDU-285
> EDU-285 Adjust various UI issues and make session cookie domain optional

- src/components/pages/room-membership-confirmation.js
- src/components/pages/room-membership-confirmation.less
- src/components/pages/room-membership-confirmation.yml
Closes https://educandu.atlassian.net/browse/EDU-275
> EDU-275 Remove disclaimer when joining a room

- src/components/pages/register.js
Closes https://educandu.atlassian.net/browse/EDU-297
> EDU-297 Fix registration validation for existing username/email

- src/components/credits-footer.js
- src/components/pages/settings.js
- src/components/pages/settings.yml
- src/components/settings/license-settings.js
- src/plugins/iframe/editing/iframe-editor.js
- src/plugins/iframe/iframe.yml
- src/resources/common.yml
- src/resources/resources.json
- src/ui/default-prop-types.js
- src/ui/validation.js
Closes https://educandu.atlassian.net/browse/EDU-286
> EDU-286 Make license configurable through settings

- src/components/pages/room.js
Closes https://educandu.atlassian.net/browse/EDU-295
> EDU-295 Remove tabs on room page for non owners

- src/components/pages/reset-password.yml
- src/components/password-input.js
- src/components/password-input.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-287
> EDU-287 Correct typos

- src/components/language-context.js
Closes https://educandu.atlassian.net/browse/EDU-299
> EDU-299 Inconsistent UI language

- src/components/grid-selector.js
- src/components/grid-selector.less
- src/components/pages/edit-doc.js
- src/components/plugin-selector-dialog.js
- src/components/plugin-selector-dialog.yml
- src/components/ui-language-dialog.less
- src/plugins/abc-notation/info.js
- src/plugins/anavis/info.js
- src/plugins/annotation/info.js
- src/plugins/audio/info.js
- src/plugins/diagram-net/info.js
- src/plugins/ear-training/ear-training.yml
- src/plugins/ear-training/info.js
- src/plugins/iframe/info.js
- src/plugins/image-tiles/info.js
- src/plugins/image/info.js
- src/plugins/interval-trainer/info.js
- src/plugins/markdown/info.js
- src/plugins/quick-tester/info.js
- src/plugins/video/info.js
- src/resources/resources.json
- src/styles/global-variables.less
- src/styles/main.less
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-290
> EDU-290 Create plugin selector dialog

- src/components/pages/register.js
Closes https://educandu.atlassian.net/browse/EDU-300
> EDU-300 Fix terms and conditions link

- src/components/cookie-consent-drawer.js
Closes https://educandu.atlassian.net/browse/EDU-298
> EDU-298 Prevent keyboard input while cookie drawer is visible

- src/api-clients/lesson-api-client.js
- src/components/edit-control-panel.less
- src/components/lesson-metadata-modal.js
- src/components/markdown-textarea.less
- src/components/pages/edit-doc.js
- src/components/pages/lesson.js
- src/components/plugin-selector-dialog.js
- src/components/section-display-new.js
- src/components/section-display-new.less
- src/components/sections-display-new.js
- src/domain/schemas/document-schemas.js
- src/domain/schemas/lesson-schemas.js
- src/domain/schemas/shared-schemas.js
- src/server/client-data-mapper.js
- src/server/client-data-mapper.spec.js
- src/server/lesson-controller.js
- src/server/lesson-controller.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/lesson-service.js
- src/styles/antd-overrides.less
- src/styles/global-variables.less
- src/styles/main.less
- src/styles/utilities.less
- src/utils/array-utils.js
- src/utils/array-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-292
> EDU-292 Create inline editor component

- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/edit-control-panel.js
- src/components/edit-control-panel.less
- src/components/edit-control-panel.yml
- src/components/pages/lesson.js
- src/plugins/iframe/editing/iframe-editor.js
- src/resources/common.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-294
> EDU-294 Handle dirty/valid state in lessons page

- src/components/pages/lesson.js
- src/components/pages/room.js
- src/server/lesson-controller.js
- src/server/lesson-controller.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-301
> EDU-301 Redirect room and lesson pages when session expired

- src/components/edit-control-panel.js
- src/components/edit-control-panel.less
- src/components/pages/lesson.js
- src/components/pages/settings.js
Closes https://educandu.atlassian.net/browse/EDU-289
> EDU-289 Use edit control panel on settings page

- src/components/pages/lesson.js
- src/components/pages/lesson.less
- src/server/lesson-controller.js
- src/server/lesson-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-307
> EDU-307 Add breadcrumbs to lesson page

- src/components/pages/doc-new.js
- src/components/section-display-new.js
- src/components/section-display-new.less
- src/components/sections-display-new.js
- src/styles/global-variables.less
Closes https://educandu.atlassian.net/browse/EDU-309
> EDU-309 Add apply discard section overlay

- src/server/client-data-mapper.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-314
> EDU-314 Map section.deletedOn and document.createdOn from/to date

- src/components/lesson-metadata-modal.js
- src/components/pages/lesson.js
- src/components/pages/room.js
- src/domain/constants.js
- src/server/lesson-controller.js
- src/utils/urls.js
- src/utils/urls.spec.js
Closes https://educandu.atlassian.net/browse/EDU-311
> EDU-311 Add view query param to lesson page

- migrations/educandu-2022-02-02-01-migrate-empty-doc-titles.js
Closes https://educandu.atlassian.net/browse/EDU-313
> EDU-313 Ensure documents and revisions do not have empty titles

- src/components/credits-footer.js
- src/utils/request-helper.js
Closes https://educandu.atlassian.net/browse/EDU-316
> EDU-316 Use fixed request timestamp

- src/plugins/image-tiles/display/image-tiles-display.js
- src/utils/urls.js
- src/utils/urls.spec.js
Closes https://educandu.atlassian.net/browse/EDU-315
> EDU-315 Do not double encode key+slug combinations

- package.json
- src/components/lesson-metadata-modal.js
- src/components/lesson-metadata-modal.less
- src/components/lesson-metadata-modal.yml
- src/components/pages/lesson.js
- src/components/pages/room.js
- src/resources/common.yml
- src/resources/resources.json
- src/styles/main.less
- src/styles/mixins.less
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-312
> EDU-312 Enable batch lesson creation

- src/common/cookie.js
- src/common/logger.js
- src/components/cookie-consent-drawer.js
- src/components/locale-context.js
- src/domain/constants.js
- src/resources/ui-language.js
- src/server/i18n-controller.js
- src/ui/global-alerts.js
Fixes https://educandu.atlassian.net/browse/EDU-324
> EDU-324 Consolidate cookie creation on server and client

- src/components/pages/doc.js
- src/components/pages/lesson.js
- src/components/pages/room.js
Closes https://educandu.atlassian.net/browse/EDU-317
> EDU-317 Reflect slug changes in the URL

- src/services/document-service.js
- src/services/document-service.spec.js
- src/services/section-helper.js
- src/services/section-helper.spec.js
- src/utils/clone-deep.js
- src/utils/clone-deep.spec.js
Fixes https://educandu.atlassian.net/browse/EDU-320
> EDU-320 Fix error when restoring sections after they were hard-deleted

- src/common/github-flavored-markdown.js
- src/common/github-flavored-markdown.spec.js
- src/services/document-service.js
Closes https://educandu.atlassian.net/browse/EDU-318
> EDU-318 Filter out empty resources

- migrations/educandu-2022-02-07-01-delete-orphaned-lessons.js
- src/services/room-service.js
- src/services/room-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-327
> EDU-327 Delete lessons when deleting a room

- src/components/confirmation-dialogs.js
- src/components/pages/doc.js
Closes https://educandu.atlassian.net/browse/EDU-278
> EDU-278 Fix textarea cursor jumping in confirmation dialog

- migrations/educandu-2022-02-08-01-add-quick-tester-tests-order.js
- src/plugins/ear-training/display/ear-training-display.js
- src/plugins/ear-training/ear-training.yml
- src/plugins/ear-training/editing/ear-training-editor.js
- src/plugins/ear-training/editing/ear-training-sound-editor.js
- src/plugins/ear-training/info.js
- src/plugins/quick-tester/constants.js
- src/plugins/quick-tester/display/quick-tester-display.js
- src/plugins/quick-tester/editing/quick-tester-editor.js
- src/plugins/quick-tester/info.js
- src/plugins/quick-tester/quick-tester.less
- src/plugins/quick-tester/quick-tester.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-323
> EDU-323 Fix bugs in quick tester and ear training editors

- src/components/section-display.js
- src/components/settings/footer-links-settings.yml
- src/plugins/editor-factory.js
- src/plugins/info-factory.js
- src/plugins/plugin-factory-base.js
- src/plugins/renderer-factory.js
- src/resources/common.yml
- src/resources/resources.json
- src/services/document-service.js
Closes https://educandu.atlassian.net/browse/EDU-319
> EDU-319 Mitigate missing plugin types (wherever possible)

- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/user-locked-out-state-editor.js
- src/components/user-role-tag-editor.js
- src/plugins/abc-notation/display/abc-notation-display.js
- src/plugins/abc-notation/editing/abc-notation-editor.js
- src/plugins/anavis/display/anavis-display.js
- src/plugins/anavis/editing/anavis-editor.js
- src/plugins/audio/display/audio-display.js
- src/plugins/audio/editing/audio-editor.js
- src/plugins/diagram-net/editing/diagram-net-editor.js
- src/plugins/ear-training/display/ear-training-display.js
- src/plugins/ear-training/editing/ear-training-editor.js
- src/plugins/ear-training/editing/ear-training-sound-editor.js
- src/plugins/iframe/editing/iframe-editor.js
- src/plugins/image-tiles/display/image-tiles-display.js
- src/plugins/image-tiles/editing/image-tiles-editor.js
- src/plugins/image-tiles/editing/tile-editor.js
- src/plugins/image/display/image-display.js
- src/plugins/image/editing/image-editor.js
- src/plugins/interval-trainer/display/interval-trainer-display.js
- src/plugins/interval-trainer/display/soundfont-provider.js
- src/plugins/interval-trainer/editing/interval-trainer-editor.js
- src/plugins/quick-tester/editing/quick-tester-editor.js
- src/plugins/video/display/video-display.js
- src/plugins/video/editing/video-editor.js
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-329
> EDU-329 Convert plugins to functional components

- src/plugins/ear-training/editing/ear-training-sound-editor.js
Fixes https://educandu.atlassian.net/browse/EDU-334
> EDU-334 Fix sound source editor in ear training editor

- src/plugins/anavis/editing/anavis-editor.js
Fixes https://educandu.atlassian.net/browse/EDU-332
> EDU-332 Fix non-working arrow and delete buttons in anavis editor

- src/components/locale-context.js
- src/components/page-name-context.js
- src/components/repository-browser.js
- src/components/request-context.js
- src/components/settings-context.js
- src/components/user-context.js
Closes https://educandu.atlassian.net/browse/EDU-335
> EDU-335 Reduce context injection to repository-browser only

- src/components/edit-control-panel.js
Closes https://educandu.atlassian.net/browse/EDU-336
> EDU-336 Set loading state on edit control panel save button

- src/components/lesson-metadata-modal.js
Closes https://educandu.atlassian.net/browse/EDU-338
> EDU-338 Allow creating lessons scheduled in the past

- migrations/educandu-2022-02-11-01-remove-empty-cdn-resources.js
Closes https://educandu.atlassian.net/browse/EDU-342
> EDU-342 Remove empty CDN resources

- .github/workflows/verify.yml
- gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-341
> EDU-341 Upgrade to mongodb 5.0.6

- src/services/user-service.js
Closes https://educandu.atlassian.net/browse/EDU-345
> EDU-345 Fix external username overlap on registration

- src/components/credits-footer.js
Closes https://educandu.atlassian.net/browse/EDU-344
> EDU-344 Update slug in credits footer

- src/components/credits-footer.js
Fixes https://educandu.atlassian.net/browse/EDU-359
> EDU-359 Break URLs in credit footer at any beginning word

- migrations/educandu-2022-02-15-01-add-storage-plans.js
- src/stores/batch-lock-store.js
- src/stores/collection-specs/storage-plans.js
- src/stores/database.js
- src/stores/storage-plan-store.js
Closes https://educandu.atlassian.net/browse/EDU-350
> EDU-350 Introduce storage plan collection

- src/components/cdn-file-picker.js
- src/components/pages/doc.js
- src/components/pages/lesson.js
- src/components/pages/revision.js
- src/components/repository-browser.js
- src/components/repository-browser.less
- src/components/section-display.js
- src/components/sections-display.js
- src/plugins/anavis/editing/anavis-editor.js
- src/plugins/audio/editing/audio-editor.js
- src/plugins/ear-training/editing/ear-training-editor.js
- src/plugins/ear-training/editing/ear-training-sound-editor.js
- src/plugins/image-tiles/editing/image-tiles-editor.js
- src/plugins/image-tiles/editing/tile-editor.js
- src/plugins/image/editing/image-editor.js
- src/plugins/video/editing/video-editor.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-352
> EDU-352 Wrap CDN props in public storage object

- migrations/educandu-2022-02-16-01-add-storage-to-users.js
- src/api-clients/user-api-client.js
- src/components/pages/users.js
- src/components/pages/users.less
- src/components/pages/users.yml
- src/components/restricted.js
- src/domain/schemas/user-schemas.js
- src/domain/storage.js
- src/resources/resources.json
- src/server/client-data-mapper.js
- src/server/client-data-mapper.spec.js
- src/server/user-controller.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-351
> EDU-351 Add storage plan to users

- gulpfile.js
- src/components/audio-player.js
- src/components/cdn-file-picker.js
- src/components/container-context.js
- src/components/pages/lesson.js
- src/components/repository-browser.js
- src/components/repository-browser.yml
- src/components/section-display.js
- src/components/sections-display.js
- src/plugins/anavis/editing/anavis-editor.js
- src/plugins/audio/editing/audio-editor.js
- src/plugins/ear-training/editing/ear-training-editor.js
- src/plugins/ear-training/editing/ear-training-sound-editor.js
- src/plugins/image-tiles/editing/image-tiles-editor.js
- src/plugins/image-tiles/editing/tile-editor.js
- src/plugins/image/editing/image-editor.js
- src/plugins/video/editing/video-editor.js
- src/resources/resources.json
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-353
> EDU-353 Pass privateStorage down to repository browser

- src/components/repository-browser.js
- src/domain/schemas/cdn-schemas.js
- src/server/cdn-controller.js
- src/server/cdn-controller.spec.js
- src/services/cdn-service.js
- src/services/cdn-service.spec.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/ui/path-helper.js
- src/ui/path-helper.spec.js
Closes https://educandu.atlassian.net/browse/EDU-354
> EDU-354 Handle cdn upload and delete

- src/components/credits-footer.js
Closes https://educandu.atlassian.net/browse/EDU-366
> EDU-366 Rework regex containing lookbehind due to Safari not supporting

- src/components/repository-browser.js
Closes https://educandu.atlassian.net/browse/EDU-364
> EDU-364 Fix CDN infinite upload after session expired

- migrations/educandu-2022-02-15-01-add-storage-plans.js
- src/components/pages/my-space.js
- src/components/pages/users.js
- src/domain/storage.js
- src/server/client-data-mapper.js
- src/server/client-data-mapper.spec.js
- src/services/cdn-service.js
- src/services/cdn-service.spec.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-362
> EDU-362 Rename storage fields

- migrations/educandu-2022-02-22-01-add-non-empty-storage-to-users.js
- src/components/pages/lesson.js
- src/components/pages/my-space.js
- src/components/pages/users.js
- src/domain/storage.js
- src/server/client-data-mapper.js
- src/server/my-space-controller.js
- src/services/cdn-service.js
- src/services/user-service.js
Closes https://educandu.atlassian.net/browse/EDU-360
> EDU-360 Change user default storage from null to object with default data

- src/components/login.js
- src/ui/browser-helper.js
Fixes https://educandu.atlassian.net/browse/EDU-377
> EDU-377 Make the login page always redirect back to the current URL

- jest.config.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/stores/room-invitation-store.js
- src/stores/room-store.js
- src/stores/room-store.spec.js
Closes https://educandu.atlassian.net/browse/EDU-369
> EDU-369 Push data access logic in room service down to room (invitation) store

- src/components/section-display.js
- src/components/section-display.less
- src/components/storage-file-picker.js
- src/components/storage-file-picker.less
- src/resources/common.yml
- src/resources/resources.json
- src/styles/main.less
- src/ui/browser-helper.js
Closes https://educandu.atlassian.net/browse/EDU-371
> EDU-371 Do not propagate click on storage file picker

- src/server/user-controller.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-378
> EDU-378 Redirect from pages that should only be reachable when authenticated (or not)

- src/server/document-controller.js
- src/server/educandu-server.js
- src/server/import-controller.js
- src/server/lesson-controller.js
- src/server/room-controller.js
- src/server/storage-controller.js
- src/server/storage-controller.spec.js
- src/server/user-controller.js
- src/server/user-controller.spec.js
Fixes https://educandu.atlassian.net/browse/EDU-373
> EDU-373 Always return a response body with DELETE requests

- src/components/login-form.js
Fixes https://educandu.atlassian.net/browse/EDU-375
> EDU-375 Make enter submit password confirm dialog

- src/common/logger.js
Closes https://educandu.atlassian.net/browse/EDU-380
> EDU-380 Use CSS coloring in browser console logging

- src/domain/needs-permission-middleware.js
- src/server/document-controller.js
- src/server/error-controller.js
Fixes https://educandu.atlassian.net/browse/EDU-372
> EDU-372 Ensure user permissions on doc page per view mode

- src/services/export-service.js
- src/services/export-service.spec.js
- src/stores/document-store.js
Closes https://educandu.atlassian.net/browse/EDU-379
> EDU-379 Remove export-service dependency on document-service

- src/server/lesson-controller.js
- src/server/lesson-controller.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/server/storage-controller.js
- src/server/storage-controller.spec.js
- src/services/lesson-service.js
- src/services/mail-service.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/stores/lesson-store.js
- src/stores/lesson-store.spec.js
- src/stores/lock-store.js
- src/ui/path-helper.js
Closes https://educandu.atlassian.net/browse/EDU-363
> EDU-363 Remove service to service dependencies involving storage

- src/components/pages/room.js
- src/components/room-invitation-creation-modal.js
Fixes https://educandu.atlassian.net/browse/EDU-381
> EDU-381 Add newly created invitations without page reload

- src/bootstrap/client-bootstrapper.js
- src/components/pages/my-space.js
- src/components/pages/my-space.less
- src/components/pages/my-space.yml
- src/components/root.js
- src/components/storage-browser.js
- src/components/storage-browser.less
- src/components/storage-browser.yml
- src/components/storage-plan-context.js
- src/components/used-storage.js
- src/components/used-storage.less
- src/components/used-storage.yml
- src/resources/resources.json
- src/server/my-space-controller.js
- src/server/page-renderer.js
- src/server/storage-controller.js
- src/server/storage-controller.spec.js
- src/server/user-controller.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-357
> EDU-357 Show used bytes in storage browser

- package.json
- src/components/storage-browser.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-382
> EDU-382 Support debounced multi file upload through storage browser

- src/components/storage-file-picker.js
- src/components/storage-file-picker.less
- src/styles/main.less
Fixes https://educandu.atlassian.net/browse/EDU-385
> EDU-385 Fix file browser scroll bar

- src/domain/built-in-users.js
Closes https://educandu.atlassian.net/browse/EDU-386
> EDU-386 Fix import error

- src/stores/database.js
Closes https://educandu.atlassian.net/browse/EDU-343
> EDU-343 Use MongoDB stable API

- src/server/lesson-controller.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/document-regeneration-task-processor.spec.js
- src/services/document-service.spec.js
- src/services/room-service.spec.js
- src/stores/lesson-store.spec.js
Closes https://educandu.atlassian.net/browse/EDU-384
> EDU-384 Fix room page 500 error

- migrations/educandu-2022-02-25-01-add-password-reset-expiry-index.js
- src/stores/collection-specs/password-reset-requests.js
Fixes https://educandu.atlassian.net/browse/EDU-391
> EDU-391 Fix passwordResetRequests indexes

- src/components/pages/docs.js
- src/utils/string-utils.js
- src/utils/string-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-390
> EDU-390 Shorten document description tooltip text

- README.md
- src/bootstrap/client-bootstrapper.js
- src/bootstrap/server-config.js
- src/components/default-page-footer.js
- src/components/default-page-footer.less
- src/components/default-page-header.js
- src/components/default-page-header.less
- src/components/default-page-template.js
- src/components/default-page-template.less
- src/components/default-site-logo.less
- src/components/pages/index.js
- src/components/pages/index.less
- src/components/root.js
- src/domain/page-resolver.js
- src/domain/page-resolver.spec.js
- src/server/page-renderer.js
- src/styles/main.less
- src/test-helper.js
- test-app/src/bundles/bundle-config.js
- test-app/src/bundles/home-page-template.js
- test-app/src/bundles/home-page-template.less
- test-app/src/main.less
Closes https://educandu.atlassian.net/browse/EDU-388
> EDU-388 Support home page template injection

- src/services/export-service.js
- src/services/export-service.spec.js
- src/stores/document-revision-store.js
- src/stores/document-store.js
Closes https://educandu.atlassian.net/browse/EDU-393
> EDU-393 Fix documents import

- src/services/batch-processor.js
- src/services/batch-processor.spec.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/services/import-service.js
- src/services/import-service.spec.js
- src/services/setting-service.js
- src/services/task-processor.js
- src/services/task-processor.spec.js
- src/stores/batch-store.js
- src/stores/lock-store.js
- src/stores/order-store-base.js
- src/stores/setting-store.js
- src/stores/task-store.js
Closes https://educandu.atlassian.net/browse/EDU-392
> EDU-392 Remove store base inheritance from non document stores

- src/components/storage-browser.js
Closes https://educandu.atlassian.net/browse/EDU-395
> EDU-395 Fix public CDN upload

- src/components/document-import-table.js
- src/components/localization/language-flag-and-name.js
- src/components/localization/language-icon.js
- src/components/localization/language-icon.less
- src/components/localization/language-select.js
- src/components/pages/docs.js
- src/components/pages/search.js
- src/components/settings/footer-links-settings.js
- src/components/settings/special-page-settings.js
- src/components/ui-language-dialog.js
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-400
and looks like this:
> EDU-400 Change language flags for content language

- src/components/login.js
- src/components/profile-tab.js
- src/styles/avatar.less
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-407
> EDU-407 Make profile picture round

- src/components/storage-browser.js
Closes https://educandu.atlassian.net/browse/EDU-411
> EDU-422 Fix search field focus lost issue

- src/components/account-tab.js
- src/components/link-popover.less
- src/components/pages/users.js
- src/styles/antd-overrides.less
- src/styles/global-variables.less
Closes https://educandu.atlassian.net/browse/EDU-403
> EDU-403 Change links styling

- package.json
- src/components/pages/docs.js
- src/components/pages/search.js
- src/components/table.js
- src/components/table.less
- src/components/table.yml
- src/resources/resources.json
- src/styles/antd-overrides.less
- src/styles/global-variables.less
- src/styles/main.less
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-402
> EDU-402 Create a custom table component wrapping Antd table

- src/components/delete-button.js
- src/components/delete-button.less
- src/components/icons/general/upload-icon.js
- src/components/import-type-icon.js
- src/components/pages/room.js
- src/components/pages/room.less
- src/components/settings/default-tags-settings.js
- src/components/settings/settings-documents-table.js
- src/components/storage-browser.js
- src/components/storage-browser.less
- src/plugins/anavis/anavis.less
- src/plugins/anavis/editing/anavis-editor.js
- src/plugins/ear-training/editing/ear-training-editor.js
- src/plugins/image-tiles/editing/image-tiles-editor.js
- src/plugins/quick-tester/editing/quick-tester-editor.js
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-412
> EDU-412 Replace antd icons with equivalents

- src/components/control-panel.less
- src/components/credits-footer.less
- src/components/default-site-logo.less
- src/components/error-page.less
- src/components/link-popover.less
- src/components/localization/language-icon.less
- src/components/markdown-textarea.less
- src/components/markdown.less
- src/components/media-control.less
- src/components/metadata-title.less
- src/components/pages/room.less
- src/components/pages/search.less
- src/components/section-display.less
- src/components/table.less
- src/plugins/anavis/anavis.less
- src/plugins/iframe/iframe.less
- src/plugins/quick-tester/display/quick-tester-display.js
- src/plugins/quick-tester/quick-tester.less
- src/styles/antd-style-overrides.less
- src/styles/antd-variable-overrides.less
- src/styles/avatar.less
- src/styles/global-variables.less
- src/styles/mixins.less
- src/styles/panel.less
- src/styles/tag.less
- test-app/src/bundles/home-page-template.less
- test-app/src/bundles/page-template.js
- test-app/src/bundles/site-logo.less
- test-app/src/main.less
Closes https://educandu.atlassian.net/browse/EDU-415
> EDU-415 Consolidate color palette

- src/components/pages/users.js
- src/components/used-storage.js
- src/components/used-storage.yml
- src/domain/schemas/user-schemas.js
- src/resources/resources.json
- src/services/user-service.js
- src/services/user-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-420
> EDU-420 Allow unassigning storage plans

- src/components/table.less
- src/styles/antd-style-overrides.less
- src/styles/antd-variable-overrides.less
- src/styles/global-variables.less
Closes https://educandu.atlassian.net/browse/EDU-436
> EDU-436 Consolidate and fix disabled control styles

- src/components/document-import-table.js
- src/components/document-selector.js
- src/components/localization/language-select.js
- src/components/pages/docs.js
- src/components/pages/search.js
- src/components/pages/settings.js
- src/components/pages/users.js
- src/components/rooms-tab.js
- src/components/settings/settings-documents-table.js
- src/components/settings/special-page-settings.js
- src/components/storage-browser.js
Closes https://educandu.atlassian.net/browse/EDU-435
> EDU-435 Sort case insensitive for non-technical string values

- migrations/educandu-2022-03-11-01-add-document-key-index.js
- src/components/favorites-tab.js
- src/components/favorites-tab.less
- src/components/favorites-tab.yml
- src/components/pages/dashboard.js
- src/components/pages/dashboard.yml
- src/resources/common.yml
- src/resources/resources.json
- src/server/dashboard-controller.js
- src/services/client-data-mapping-service.js
- src/services/dashboard-service.js
- src/services/dashboard-service.spec.js
- src/stores/collection-specs/documents.js
- src/stores/document-store.js
- src/stores/lesson-store.js
- src/stores/room-store.js
- src/styles/main.less
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-428
and looks like
> EDU-428 Add favorites tab to dashboard

- src/components/pages/doc.js
- src/server/document-controller.js
- src/services/document-service.js
Closes https://educandu.atlassian.net/browse/EDU-437
> EDU-437 Update doc state when hard deleting sections

- src/components/section-display.less
Closes https://educandu.atlassian.net/browse/EDU-451
> EDU-451 Show default sections' content semi-transparently

- src/plugins/image/constants.js
- src/plugins/image/display/image-display.js
- src/plugins/image/editing/image-editor.js
- src/plugins/image/image.yml
- src/plugins/image/utils.js
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-448
> EDU-448 Show warning for small images

- src/components/pages/search.js
- src/components/tag-selector.js
Closes https://educandu.atlassian.net/browse/EDU-443
> EDU-443 Order tags alphabetically

- src/components/document-info-cell.js
- src/components/document-info-cell.less
- src/components/document-info-cell.yml
- src/components/pages/docs.js
- src/components/pages/docs.less
- src/components/pages/docs.yml
- src/components/pages/search.js
- src/components/pages/search.less
- src/components/pages/search.yml
- src/components/search-bar.js
- src/components/search-bar.yml
- src/resources/common.yml
- src/resources/resources.json
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-434
and looks like:
> EDU-434 Update documents page table

- migrations/educandu-2022-03-28-01-update-video-sections-content.js
- src/plugins/video/display/video-display.js
- src/plugins/video/editing/video-editor.js
- src/plugins/video/info.js
- src/plugins/video/info.spec.js
- src/plugins/video/video.yml
- src/resources/resources.json
- src/services/document-import-task-processor.spec.js
- src/services/document-service.spec.js
- src/ui/mime-type-helper.js
Closes https://educandu.atlassian.net/browse/EDU-450
On a Prod dump, the report was:
```
Updated 17 lessons, 285 documents, 5052 documentRevisions
info [2022-03-28T18:03:28.041Z] [/src/stores/database.js] {
event: 'migrated',
name: 'educandu-2022-03-28-01-update-video-sections-content',
durationSeconds: 18.555
}
```
> EDU-450 Support uploading video image poster

- src/components/section-display.js
Closes https://educandu.atlassian.net/browse/EDU-454
> EDU-454 Disable edit shortcut for hard deleted sections

- src/plugins/pdf-viewer/display/pdf-viewer-display.js
Closes https://educandu.atlassian.net/browse/EDU-457
> EDU-457 Send session cookie when fetching PDFs from private storage

- migrations/educandu-2022-03-30-01-add-render-media-to-quick-tester-sections-content.js
- src/plugins/quick-tester/display/quick-tester-display.js
- src/plugins/quick-tester/editing/quick-tester-editor.js
- src/plugins/quick-tester/info.js
- src/plugins/quick-tester/quick-tester.less
- src/plugins/quick-tester/quick-tester.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-456
> EDU-456 Render questions and answers in quick tester as Markdown with media

- src/api-clients/user-api-client.js
- src/components/confirmation-dialogs.js
- src/components/login-form.js
- src/components/login-form.yml
- src/components/pages/login.js
- src/components/pages/login.less
- src/components/pages/login.yml
- src/domain/schemas/user-schemas.js
- src/resources/resources.json
- src/server/user-controller.js
- src/services/user-service.js
- src/stores/user-store.js
- src/stores/user-store.spec.js
Closes https://educandu.atlassian.net/browse/EDU-458
> EDU-458 Allow login with email address or username

- src/components/pages/reset-password.js
Closes https://educandu.atlassian.net/browse/EDU-461
> EDU-461 Fix link to login page after password reset

- src/components/storage-browser.js
- src/components/storage-browser.less
- src/components/storage-browser.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-460
> EDU-460 Add warning when saving to public storage from private rooms

- gulpfile.js
- src/bootstrap/server-config.js
- src/components/admin/tests-tab.js
- src/components/pages/admin.js
- src/components/pages/admin.yml
- src/components/timeline.js
- src/components/timeline.less
- src/resources/resources.json
- src/styles/global-variables.less
- src/styles/main.less
- src/ui/browser-helper.js
- src/utils/array-utils.js
- src/utils/array-utils.spec.js
- test-app/src/index.js
- test-app/src/main.less
Closes https://educandu.atlassian.net/browse/EDU-455
and can be tested locally on the admin page -> tests tab.
> EDU-455 Create timeline component

- src/components/storage-browser.js
- src/components/storage-browser.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-464
> EDU-464 Add upload limit tooltip

- src/components/delete-button.js
- src/components/lesson-metadata-modal.js
- src/components/pages/doc.js
- src/components/pages/doc.yml
- src/components/pages/docs.js
- src/components/pages/docs.yml
- src/components/pages/lesson.js
- src/components/pages/room.js
- src/domain/schemas/lesson-schemas.js
- src/resources/common.yml
- src/resources/resources.json
- src/server/lesson-controller.js
- src/server/lesson-controller.spec.js
- src/services/client-data-mapping-service.js
- src/ui/default-prop-types.js
- src/utils/urls.js
Closes https://educandu.atlassian.net/browse/EDU-459
> EDU-459 Enable lesson cloning

- src/components/pages/login.less
- src/components/pages/register.js
- src/components/pages/register.less
- src/components/pages/reset-password.js
- src/components/pages/reset-password.less
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-462
> EDU-462 Adjust register and reset-password forms to match login form

- src/components/pages/room.js
Closes https://educandu.atlassian.net/browse/EDU-481
> EDU-481 Do not let non-owners clone or delete lessons

- migrations/educandu-2022-04-08-01-add-initial-page-number-to-pdf-viewer-plugin.js
- src/plugins/pdf-viewer/display/pdf-viewer-display.js
- src/plugins/pdf-viewer/editing/pdf-viewer-editor.js
- src/plugins/pdf-viewer/info.js
- src/plugins/pdf-viewer/pdf-viewer.yml
- src/resources/resources.json
- src/styles/antd-style-overrides.less
Closes https://educandu.atlassian.net/browse/EDU-474
> EDU-474 Make initial PDF page number configurable

- src/components/icons/general/private-icon.js
- src/components/icons/general/public-icon.js
- src/components/pages/lesson.js
- src/components/pages/room.js
- src/components/pages/room.less
- src/components/storage-browser.js
Closes https://educandu.atlassian.net/browse/EDU-479
I ended up adjusting both SVGs (sizes and shapes) to get something distinguishable in the UI.
> EDU-479 Streamline public/private icons

- src/components/pages/users.js
Closes https://educandu.atlassian.net/browse/EDU-488
> EDU-488 Fix user sorting by storage

- src/services/lesson-service.js
- src/services/lesson-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-489
> EDU-489 Fix lessons sorting by schedule.startsOn

- src/stores/user-store.js
- src/stores/user-store.spec.js
Closes https://educandu.atlassian.net/browse/EDU-490
> EDU-490 Compare email adresses in lower case

- src/components/pages/docs.js
Closes https://educandu.atlassian.net/browse/EDU-493
> EDU-493 Restrict archiving sorting option based on permissions

- src/components/pages/lesson.js
- src/components/pages/lesson.less
- src/components/pages/room.js
- src/components/pages/room.less
- src/components/pages/room.yml
- src/resources/common.yml
- src/resources/resources.json
- src/styles/breadcrumbs.less
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-497
> EDU-497 Add breadcrumbs to room page

- src/server/user-controller.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/stores/user-store.js
- src/stores/user-store.spec.js
Closes https://educandu.atlassian.net/browse/EDU-492
> EDU-492 Remove business logic from store

- src/components/login-form.js
- src/ui/browser-helper.js
Closes https://educandu.atlassian.net/browse/EDU-440
> EDU-440 Ensure form values are set correctly after hydration

- src/components/pages/search.js
- src/components/pages/search.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-499
> EDU-499 Show searching headlines while fetching documents

- src/components/grid-selector.less
- src/components/plugin-selector-dialog.js
- src/components/plugin-selector-dialog.less
- src/components/section-display.js
- src/plugins/abc-notation/abc-notation-info.js
- src/plugins/anavis/anavis-info.js
- src/plugins/annotation/annotation-info.js
- src/plugins/audio/audio-info.js
- src/plugins/diagram-net/diagram-net-info.js
- src/plugins/ear-training/ear-training-info.js
- src/plugins/iframe/iframe-info.js
- src/plugins/image-tiles/image-tiles-info.js
- src/plugins/image/image-info.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media-icon.js
- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/interactive-media/interactive-media.yml
- src/plugins/interval-trainer/interval-trainer-info.js
- src/plugins/markdown/markdown-info.js
- src/plugins/pdf-viewer/pdf-viewer-info.js
- src/plugins/plugin-registry.js
- src/plugins/quick-tester/quick-tester-info.js
- src/plugins/video/video-info.js
- src/resources/resources.json
- src/styles/main.less
- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-507
> EDU-507 Add interactive media plugin

- src/plugins/anavis/anavis-editor.js
Closes https://educandu.atlassian.net/browse/EDU-521
> EDU-521 Fix changing aspect ratio in Anavis editor

- src/plugins/image/image-display.js
Closes https://educandu.atlassian.net/browse/EDU-520
> EDU-520 Render hover image in canvas of same size as the original image

- src/plugins/image/image-display.js
Closes https://educandu.atlassian.net/browse/EDU-524
> EDU-524 Show copyright with clip effect

- src/components/markdown.js
Closes https://educandu.atlassian.net/browse/EDU-523
> EDU-523 Prevent Markdown class from being overridden

- src/components/admin/license-settings.js
- src/plugins/image-tiles/image-tile-editor.js
- src/plugins/image-tiles/image-tiles-utils.js
- src/resources/resources.json
- src/ui/validation.js
- src/ui/validation.spec.js
- src/ui/validation.yml
Closes https://educandu.atlassian.net/browse/EDU-525
> EDU-525 Allow mailto links as image tile targets

- src/components/link-popover.js
Closes https://educandu.atlassian.net/browse/EDU-522
> EDU-522 Remove separator after last item in page menu

- src/plugins/image/image-display.js
- src/plugins/image/image.less
Closes https://educandu.atlassian.net/browse/EDU-527
> EDU-527 Apply hover effect only on image surface hover

- src/components/pages/doc.js
- src/server/document-controller.js
Closes https://educandu.atlassian.net/browse/EDU-526
> EDU-526 Update page states after document revision is restored

- migrations/educandu-2022-05-03-01-sourceDuration-and-chapters-to-annotation-plugin.js
- migrations/educandu-2022-05-05-01-sourceDuration-and-chapters-to-annotation-plugin.js
- src/common/github-flavored-markdown.js
- src/domain/constants.js
- src/plugins/interactive-media/constants.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/interactive-media/interactive-media.yml
- src/resources/resources.json
- src/utils/media-utils.js
- src/utils/media-utils.spec.js
https://educandu.atlassian.net/browse/EDU-531
> EDU-531 Get media duration

- src/plugins/image/image-display.js
Closes https://educandu.atlassian.net/browse/EDU-537
> EDU-537 Toggle copyright texts

- src/components/timeline.js
- src/components/timeline.less
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/interactive-media/interactive-media.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-530
Sample view:
> EDU-530 Allow chapter editing

- src/components/debounced-input.js
- src/plugins/interactive-media/interactive-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-535
> EDU-535 Debounce typed in source url

- src/components/media-player-controls.js
Closes https://educandu.atlassian.net/browse/EDU-541
> EDU-541 Make volume slider behave better when muted

- src/plugins/image-tiles/image-tiles-display.js
- src/plugins/image-tiles/image-tiles.less
- src/styles/utilities.less
Closes https://educandu.atlassian.net/browse/EDU-539
> EDU-539 Disable link functionality on image tiles with no link set

- src/components/account-tab.js
- src/components/login-form.js
- src/components/pages/register.js
- src/components/username-form-item.js
Closes https://educandu.atlassian.net/browse/EDU-534
> EDU-534 Always trim usernames before sending them to the server

- src/plugins/image/image-display.js
- src/plugins/image/image.less
- src/plugins/image/image.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-544
> EDU-544 Show error message when image load fails for main image

- src/components/pages/tests.js
- src/domain/page-name.js
- src/domain/page-resolver.js
- src/server/tests-controller.js
- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-550
> EDU-550 Add tests page

- migrations/educandu-2022-05-10-01-convert-audio-only-video-sections-to-audio-sections.js
- migrations/educandu-2022-05-10-02-remove-showVideo-from-video-plugins.js
- src/domain/constants.js
- src/plugins/anavis/anavis-display.js
- src/plugins/anavis/anavis-editor.js
- src/plugins/anavis/anavis-info.js
- src/plugins/anavis/anavis-info.spec.js
- src/plugins/anavis/constants.js
- src/plugins/audio/audio-display.js
- src/plugins/audio/audio-editor.js
- src/plugins/audio/audio-info.js
- src/plugins/audio/audio-info.spec.js
- src/plugins/audio/constants.js
- src/plugins/interactive-media/constants.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/interactive-media/interactive-media-info.spec.js
- src/plugins/pdf-viewer/pdf-viewer.yml
- src/plugins/video/constants.js
- src/plugins/video/video-display.js
- src/plugins/video/video-editor.js
- src/plugins/video/video-info.js
- src/plugins/video/video-info.spec.js
- src/resources/common.yml
- src/resources/resources.json
- src/services/document-import-task-processor.spec.js
- src/services/document-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-547
> EDU-547 Clearly separate video and audio player

- migrations/educandu-2022-05-10-03-add-source-start-and-stop-timecode-to-interactive-media.js
- src/components/media-player-controls.js
- src/components/media-player-track.js
- src/components/media-player.js
- src/components/media-range-selector.js
- src/components/media-range-selector.less
- src/components/media-range-selector.yml
- src/plugins/anavis/anavis-editor.js
- src/plugins/audio/audio-editor.js
- src/plugins/ear-training/ear-training-sound-editor.js
- src/plugins/image-tiles/image-tile-editor.js
- src/plugins/image/image-editor.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/interactive-media/interactive-media.yml
- src/plugins/pdf-viewer/pdf-viewer-editor.js
- src/plugins/pdf-viewer/pdf-viewer.less
- src/plugins/video/video-editor.js
- src/resources/resources.json
- src/styles/main.less
- src/styles/utilities.less
- src/utils/media-utils.js
- src/utils/media-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-546
> EDU-546 custom start and end timecodes

- src/components/media-player-controls.js
- src/components/media-player-controls.less
- src/components/media-player.js
- src/plugins/interactive-media/interactive-media-display.js
Closes https://educandu.atlassian.net/browse/EDU-545
> EDU-545 Show chapter markers in media player progress bar

- src/components/media-player-controls.js
- src/components/media-player-controls.less
- src/components/media-player.less
- src/plugins/anavis/anavis.less
- src/plugins/audio/audio-display.js
- src/plugins/audio/audio.less
- src/plugins/ear-training/ear-training-display.js
- src/plugins/ear-training/ear-training.less
- src/styles/main.less
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-558
> EDU-558 Fix UI issues with media player

- src/components/files-grid-viewer.js
- src/components/files-list-viewer.js
- src/components/files-list-viewer.less
- src/components/pages/tests.js
- src/resources/common.yml
- src/resources/resources.json
- src/styles/antd-style-overrides.less
- src/styles/antd-variable-overrides.less
- src/styles/global-variables.less
- src/styles/main.less
- src/utils/resource-utils.js
Closes https://educandu.atlassian.net/browse/EDU-552
> EDU-552 Create files list viewer component

- src/components/media-player-controls.less
μPR closing https://educandu.atlassian.net/browse/EDU-565
> EDU-565 Eliminate media controls jump due to markers

- src/plugins/interactive-media/interactive-media-editor.js
- src/utils/media-utils.js
- src/utils/media-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-557
> EDU-557 Support shortened youtube links

- src/components/timeline.js
- src/components/timeline.less
- src/plugins/interactive-media/interactive-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-566
> EDU-566 Show timecode on timeline hover

- src/components/document-selector.js
Closes https://educandu.atlassian.net/browse/EDU-562
> EDU-562 Fix empty box after selecting a document

- src/components/file-preview.js
- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.js
- src/components/files-list-viewer.less
- src/components/icons/files/file-audio-filled-icon.js
- src/components/icons/files/file-audio-icon.js
- src/components/icons/files/file-image-filled-icon.js
- src/components/icons/files/file-image-icon.js
- src/components/icons/files/file-pdf-filled-icon.js
- src/components/icons/files/file-pdf-icon.js
- src/components/icons/files/file-text-filled-icon.js
- src/components/icons/files/file-text-icon.js
- src/components/icons/files/file-unknown-filled-icon.js
- src/components/icons/files/file-unknown-icon.js
- src/components/icons/files/file-video-filled-icon.js
- src/components/icons/files/file-video-icon.js
- src/components/icons/files/folder-filled-icon.js
- src/components/icons/files/folder-icon.js
- src/utils/resource-utils.js
Closes https://educandu.atlassian.net/browse/EDU-571
> EDU-571 Replace files icons

- src/plugins/interactive-media/interactive-media-editor.js
- src/utils/media-utils.js
Closes https://educandu.atlassian.net/browse/EDU-569
> EDU-569 Avoid page freeze when media duration cannot be determined

- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/pages/tests.js
Closes https://educandu.atlassian.net/browse/EDU-568
> EDU-568 Show real image instead of icon

- src/plugins/interactive-media/interactive-media-editor.js
- src/utils/media-utils.js
- src/utils/media-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-560
> EDU-560 Ensure chapters always fit into playback range

- src/plugins/image/image-display.js
Closes https://educandu.atlassian.net/browse/EDU-555
This particular case is pretty hard to reproduce locally, but my suspicion is that this change will fix it.
> EDU-555 Fix clip effect canvas sometimes not drawn on first render

- src/components/media-player-controls.js
- src/components/media-player-track.js
- src/components/media-player.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media.less
Closes https://educandu.atlassian.net/browse/EDU-548
> EDU548 - Show overlay on chapter end

- src/api-clients/http-client.js
- src/components/file-preview.js
- src/components/link-popover.js
- src/components/media-player-controls.js
- src/components/media-player-controls.yml
- src/components/media-player.js
- src/plugins/audio/audio-display.js
- src/plugins/ear-training/ear-training-display.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/video/video-display.js
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-573
> EDU-573 Add download option to media player

- src/plugins/image/image-display.js
Closes https://educandu.atlassian.net/browse/EDU-578
> EDU-578 Resize hover image to better fit main image

- README.md
- src/bootstrap/server-config.js
- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/pages/tests.js
- src/components/storage-browser.js
- src/resources/resources.json
- src/test-helper.js
- src/ui/default-prop-types.js
- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-570
> EDU-570 Require public storage upload liability confirmation

- src/components/confirmation-dialogs.js
- src/components/default-page-header.js
- src/components/icons/main-menu/logout-icon.js
- src/components/login-form.js
- src/components/login-form.yml
- src/components/login.js
- src/components/login.yml
- src/components/pages/complete-password-reset.yml
- src/components/pages/complete-registration.yml
- src/components/pages/login.js
- src/components/pages/login.less
- src/components/pages/register.js
- src/components/pages/register.less
- src/components/pages/register.yml
- src/components/pages/reset-password.yml
- src/resources/common.yml
- src/resources/resource-manager.spec.js
- src/resources/resources.json
- test-app/src/bundles/page-header.js
Closes https://educandu.atlassian.net/browse/EDU-576
Unifies english terms for "log in/on" and "log off/out" to simply "login" and "logout"
> EDU-576 Make registration procedure clearer

- src/api-clients/storage-api-client.js
- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.js
- src/components/files-viewer.js
- src/components/files-viewer.less
- src/components/pages/tests.js
- src/components/storage-browser.js
- src/domain/constants.js
- src/domain/schemas/storage-schemas.js
- src/resources/common.yml
- src/resources/resources.json
- src/server/storage-controller.js
- src/server/storage-controller.spec.js
- src/server/tests-controller.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/styles/main.less
- src/ui/default-prop-types.js
- src/ui/path-helper.js
- src/ui/path-helper.spec.js
- src/utils/path-utils.js
- src/utils/resource-utils.js
Closes https://educandu.atlassian.net/browse/EDU-553
Sorry for the huge pull request. I started to modernize the server API and tried to keep it as tame as possible. There are more issues that should be fixed, but I created individual JIRA tickets for them.
> EDU-553 Prepare new storage browser

- src/components/pages/room.js
- src/components/pages/room.less
Closes https://educandu.atlassian.net/browse/EDU-581
> EDU-581 Fix lessons styling on mobile

- src/components/pages/tests.js
- src/components/resource-selector.js
- src/components/storage-location.js
- src/domain/constants.js
- src/server/document-controller.js
- src/server/lesson-controller.js
- src/server/room-controller.js
- src/server/storage-controller.js
- src/server/tests-controller.js
- src/services/storage-service.js
- src/utils/storage-utils.js
- src/utils/storage-utils.spec.js
- src/utils/url-utils.js
- src/utils/url-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-580
> EDU-580-Create-storage-browser-top-component

- src/plugins/image-tiles/image-tiles-editor.js
Closes https://educandu.atlassian.net/browse/EDU-586
> EDU-586 Fix delete tile menu item

- src/components/file-preview.js
- src/components/icons/general/audio-icon.js
- src/components/media-player-controls.js
- src/components/media-player-controls.less
- src/components/media-player-track.js
- src/components/media-player-track.less
- src/components/media-player.js
- src/components/media-player.less
- src/domain/constants.js
- src/plugins/anavis/anavis-display.js
- src/plugins/audio/audio-display.js
- src/plugins/ear-training/ear-training-display.js
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-589
> EDU-589 Show placeholder screen for audio

- src/components/edit-control-panel.less
- src/components/files-grid-viewer.less
- src/components/timeline.less
- src/plugins/anavis/anavis.less
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/interactive-media/interactive-media.yml
- src/resources/resources.json
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-588
> EDU-588 Support chapter Q and A in display mode

- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.js
- src/components/files-list-viewer.less
- src/components/files-viewer.js
- src/components/icons/files/folder-filled-navigate-icon.js
- src/components/icons/files/folder-navigate-icon.js
- src/components/pages/tests.js
- src/server/storage-controller.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-597
> EDU-597 Add parent display name

- src/components/pages/docs.js
- src/components/pages/docs.less
- src/components/pages/docs.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-585
> EDU-585 Clarify that the input on the docs page executes a filtering

- src/components/dimensions-provider.js
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.js
- src/components/files-list-viewer.less
- src/components/files-viewer.js
- src/components/files-viewer.less
- src/components/pages/tests.js
- src/components/resource-selector.js
- src/components/storage-location.js
- src/components/storage-location.less
- src/components/storage-location.yml
- src/resources/resources.json
- src/styles/main.less
- src/styles/mixins.less
- src/utils/storage-utils.js
Closes https://educandu.atlassian.net/browse/EDU-591
> EDU-591 Create storage location component

- src/components/admin/settings-tab.less
- src/components/delete-button.less
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.less
- src/components/pages/room.less
- src/components/section-display.less
- src/plugins/interactive-media/interactive-media.less
- src/styles/antd-variable-overrides.less
- src/styles/global-variables.less
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-605
Clone document with sections look:
> EDU-605 Unify success and error colors

- src/components/files-list-viewer.less
- src/components/storage-location.js
- src/components/storage-location.less
- src/components/storage-location.yml
- src/resources/resources.json
- src/server/tests-controller.js
- src/styles/antd-variable-overrides.less
- src/styles/global-variables.less
Closes https://educandu.atlassian.net/browse/EDU-596
> EDU-596 Show used storage

- src/components/files-list-viewer.js
- src/components/files-viewer.js
- src/components/pages/tests.js
- src/components/storage-context.js
- src/components/storage-location.js
- src/components/storage-location.less
Closes https://educandu.atlassian.net/browse/EDU-594
> EDU-594 Support file deletion

- src/components/file-preview.js
- src/components/files-grid-viewer.less
- src/components/files-viewer.js
- src/components/pages/tests.js
- src/components/resource-selector.js
- src/components/resource-selector.yml
- src/components/storage-location.js
- src/components/storage-location.less
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-595
> EDU-595 Support file preview

- src/components/pages/tests.js
- src/components/storage-location.js
Closes https://educandu.atlassian.net/browse/EDU-592
> EDU-592 Set up select button

- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/interactive-media/interactive-media.less
Closes https://educandu.atlassian.net/browse/EDU-607
> EDU-607 Make the read-only mode clear

- src/common/github-flavored-markdown.js
- src/common/github-flavored-markdown.spec.js
Closes https://educandu.atlassian.net/browse/EDU-606
> EDU-606 Take autolinks in markdown into consideration

- src/server/storage-controller.js
- src/server/storage-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-582
> EDU-582 Check permissions also when listing files

- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/storage-location.js
- src/components/storage-location.less
- src/components/storage-location.yml
- src/resources/resources.json
- src/utils/resource-utils.js
- src/utils/storage-utils.js
Closes https://educandu.atlassian.net/browse/EDU-593
> EDU-593 Support file upload

- src/components/history-control-panel.js
Closes https://educandu.atlassian.net/browse/EDU-625
> EDU-625 Update slider marks rendering

- src/plugins/table/table.less
Closes https://educandu.atlassian.net/browse/EDU-615
> EDU-615 Make table plugin scroll horizontally on small devices

- src/components/media-player-controls.less
- src/plugins/audio/audio.less
- src/plugins/ear-training/ear-training.less
Closes https://educandu.atlassian.net/browse/EDU-615
> EDU-616 Make audio player have a max-width in audio and ear-training plugins

- src/components/pages/docs.js
- src/components/pages/docs.less
Closes https://educandu.atlassian.net/browse/EDU-626
> EDU-626 Replace action links on docs page with icons

- src/components/admin/storage-plans-tab.js
Closes https://educandu.atlassian.net/browse/EDU-617
> EDU-617 Make storage plans table responsive

- src/components/alert.less
- src/components/files-grid-viewer.js
- src/components/files-grid-viewer.less
- src/components/files-list-viewer.less
- src/components/grid-selector.less
- src/components/section-display.less
- src/components/ui-language-dialog.less
- src/plugins/interactive-media/interactive-media.less
- src/styles/antd-style-overrides.less
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-604
> EDU-604 Unify selected and hover styles across components

- package.json
- src/bootstrap/server-config.js
- src/server/educandu-server.js
- test-app/src/index.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-610
> EDU-610 Add simple basic auth layer with configurable credentials

- src/plugins/interactive-media/interactive-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-627
> EDU-627 Calculate timeline duration from actual playback duration

- src/server/educandu-server.js
Closes https://educandu.atlassian.net/browse/EDU-629
> EDU-629 Exclude API routes from basic auth

- src/services/maintenance-service.js
- src/services/maintenance-service.spec.js
- src/utils/storage-utils.js
Closes https://educandu.atlassian.net/browse/EDU-622
> EDU-622 Create default CDN directories at startup

- src/plugins/table/table-designer.js
- src/plugins/table/table-utils.js
- src/plugins/table/table-utils.spec.js
- src/plugins/table/table.less
Closes https://educandu.atlassian.net/browse/EDU-603
> EDU-603 Fix rendering issues in table designer

- src/components/literal-url-link.js
- src/components/markdown-help.js
- src/utils/string-utils.js
- src/utils/string-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-632
> EDU-632 Make markdown help table columns the same width on all screens

- src/components/files-grid-viewer.less
- src/components/localization/country-flag-and-name.less
- src/components/ui-language-dialog.js
- src/components/ui-language-dialog.less
Closes https://educandu.atlassian.net/browse/EDU-631
> EDU-631 Remove color change effect on grid items hover

- migrations/educandu-2022-06-30-01-add-review-to-documents.js
- src/components/alert.js
- src/components/alert.less
- src/components/default-page-template.js
- src/components/document-metadata-modal.js
- src/components/document-metadata-modal.yml
- src/components/pages/doc.js
- src/components/pages/docs.js
- src/domain/constants.js
- src/domain/permissions.js
- src/domain/permissions.spec.js
- src/domain/schemas/document-schemas.js
- src/index.js
- src/resources/resources.json
- src/services/document-service.js
- src/services/document-service.spec.js
- src/stores/document-store.js
- src/ui/default-prop-types.js
- test-app/src/bundles/page-template.js
Closes https://educandu.atlassian.net/browse/EDU-650
> EDU-650 Introduce maintainer role

- src/plugins/image-tiles/image-tiles-utils.js
Swiftly closes https://educandu.atlassian.net/browse/EDU-652
> EDU-652 Change default source-type for image tiles plugin

- src/plugins/table/table.less
Closes https://educandu.atlassian.net/browse/EDU-641
> EDU-641 Change table header background color

- src/components/markdown.less
Closes https://educandu.atlassian.net/browse/EDU-646
> EDU-646 Add more spacing and better styling to hr elements rendered by Markdown

- README.md
- src/bootstrap/server-config.js
- src/services/amb-service.js
- src/services/amb-service.spec.js
- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-656
> EDU-656 Extend AMB response

- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/icons/user-activities/room-exited-icon.js
- src/components/icons/user-activities/room-joined-icon.js
- src/components/pages/room.js
- src/components/pages/room.less
- src/components/pages/room.yml
- src/resources/resources.json
- src/server/admin-controller.spec.js
- src/server/document-controller.spec.js
- src/server/lesson-controller.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/server/storage-controller.spec.js
- src/server/user-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-635
> EDU-635 Support leave room option

- src/components/pages/docs.js
Closes https://educandu.atlassian.net/browse/EDU-645
> EDU-645 Order documents by update date

- src/components/pages/dashboard.js
- src/components/room-card.js
- src/components/room-card.less
- src/components/room-card.yml
- src/components/rooms-tab.js
- src/resources/resources.json
- src/server/dashboard-controller.js
- src/services/client-data-mapping-service.js
- src/services/client-data-mapping-service.spec.js
- src/services/room-service.js
- src/stores/room-invitation-store.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-655
> EDU-655 Show invitations in rooms tab

- src/components/object-width-slider.js
- src/utils/array-utils.js
- src/utils/array-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-658
**Desktop**
**Mobile**
> EDU-658 Finer scale on width slider

- src/plugins/ear-training/ear-training-display.js
- src/plugins/quick-tester/quick-tester-display.js
Closes https://educandu.atlassian.net/browse/EDU-670
> EDU-670 Correct tooltip text for tests plugins

- src/components/pages/room.js
Closes https://educandu.atlassian.net/browse/EDU-671
> EDU-671 Fix object sorting in lesson list

- src/components/file-preview.less
- src/components/files-upload-overview.js
- src/components/files-upload-overview.less
- src/components/files-upload-overview.yml
- src/components/resource-picker.js
- src/components/resource-selector.js
- src/components/resource-selector.less
- src/components/storage-location.js
- src/components/storage-location.less
- src/components/storage-location.yml
- src/components/used-storage.less
- src/components/used-storage.yml
- src/resources/resources.json
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-665
**Upload overview**
**File preview desktop**
**File preview mobile**
> EDU-665 Create upload overview panel

- src/components/input-and-preview.less
- src/components/markdown-input.js
- src/components/markdown-input.less
- src/components/markdown-input.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-662
> EDU-662 Improve markdown preview styling

- src/services/amb-service.js
- src/services/amb-service.spec.js
- src/stores/document-store.js
Closes https://educandu.atlassian.net/browse/EDU-676
> EDU-676 Filter out not tagged documents from AMB endpoint

- migrations/educandu-2022-07-20-02-change-favorite-type-from-lesson-to-document.js
- src/services/document-service.js
- src/services/lesson-convertor.js
- src/services/lesson-convertor.spec.js
- src/services/maintenance-service.js
- src/services/maintenance-service.spec.js
- src/stores/collection-specs/lessons.js
- src/stores/database.js
Closes https://educandu.atlassian.net/browse/EDU-683
> EDU-683 Add migration logic to convert lessons to documents

- src/components/document-info-cell.js
- src/components/document-info-cell.less
- src/components/icons/general/room-icon.js
- src/components/pages/docs.js
- src/components/pages/search.js
- src/server/document-controller.js
- src/server/document-controller.spec.js
- src/server/search-controller.js
- src/server/search-controller.spec.js
- src/services/room-service.js
- src/stores/document-store.js
- src/stores/room-store.js
- src/styles/main.less
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-684
**Desktop**
**Mobile**
> EDU-684 Show documents in containing room frame

- src/components/dialog-footer-buttons.js
- src/components/dialog-footer-buttons.less
- src/components/file-preview.js
- src/components/file-preview.less
- src/components/files-upload-overview.js
- src/components/files-upload-overview.less
- src/components/storage-location.js
- src/components/storage-location.less
- src/server/storage-controller.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-679
> EDU-679 Add buttons to upload view

- src/components/pages/doc.js
Closes https://educandu.atlassian.net/browse/EDU-693
> EDU-639 Disable editing documents in exclusive rooms

- src/components/pages/room.js
Closes https://educandu.atlassian.net/browse/EDU-694
> EDU-694 Fix documents sorting in room

- src/components/admin/settings-tab.js
Closes https://educandu.atlassian.net/browse/EDU-689
> EDU-689 Allow removing plugin helptexts

- src/components/favorites-tab.js
- src/components/favorites-tab.yml
- src/components/icons/user-activities/user-marked-favorite-icon.js
- src/components/news-tab.js
- src/components/news-tab.yml
- src/components/pages/user.js
- src/components/pages/user.less
- src/domain/constants.js
- src/resources/resources.json
- src/services/client-data-mapping-service.js
- src/services/dashboard-service.js
- src/services/dashboard-service.spec.js
- src/services/user-service.js
- src/services/user-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-697
> EDU-697 Mark user as favorite

- src/services/maintenance-service.js
Closes https://educandu.atlassian.net/browse/EDU-699
> EDU-699 Do not swallow duplicate key errors happening during maintenance

- src/server/document-controller.js
- src/server/document-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-703
> EDU-703 Fix document deletion handler

- src/components/document-card.js
- src/components/document-card.less
- src/components/favorite-star.js
- src/components/favorite-star.yml
- src/components/favorites-tab.js
- src/components/favorites-tab.less
- src/components/favorites-tab.yml
- src/components/pages/docs.js
- src/components/pages/user.js
- src/components/pages/user.less
- src/components/room-card.js
- src/components/room-card.less
- src/components/rooms-tab.less
- src/resources/common.yml
- src/resources/resources.json
- src/server/user-controller.js
- src/services/client-data-mapping-service.js
- src/services/storage-service.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/styles/mixins.less
Closes https://educandu.atlassian.net/browse/EDU-704
Base on https://github.com/educandu/educandu/pull/533, which has to be merged first.
> EDU-704 - Rework favorites tab UI to inline with rooms tab and user page

- src/components/pages/search.js
Closes https://educandu.atlassian.net/browse/EDU-715
> EDU-715 fix subsequent search

- src/plugins/interactive-media/interactive-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-710
> EDU-710 Fix sourceURL change event handling in interactive media plugin

- src/stores/document-store.js
Easily closes https://educandu.atlassian.net/browse/EDU-709
> EDU-709 Exclude room documents from export/import

- src/domain/schemas/document-schemas.js
Closes https://educandu.atlassian.net/browse/EDU-718
> EDU-718 Fix server-side validation for document cloning case

- src/components/copyright-notice.less
Closes https://educandu.atlassian.net/browse/EDU-717
> EDU-717 Remove copyright sign

- src/components/ui-language-dialog.js
Closes https://educandu.atlassian.net/browse/EDU-691
> EDU-691 Select and close language dialog with double click

- src/components/room-metadata-form.js
- src/components/room-metadata-form.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-716
> EDU-716 Disable public rooms creation

- src/components/timeline.js
Closes https://educandu.atlassian.net/browse/EDU-707
**When dragging:**
> EDU-707 Show marker position when dragging

- src/components/pages/tests.js
- src/plugins/interactive-media/interactive-media-info.spec.js
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/plugins/multitrack-media/multitrack-media-icon.js
- src/plugins/multitrack-media/multitrack-media-info.js
- src/plugins/multitrack-media/multitrack-media-info.spec.js
- src/plugins/multitrack-media/multitrack-media.less
- src/plugins/multitrack-media/multitrack-media.yml
- src/resources/resources.json
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-719
> EDU-719 Create empty multitrack-media plugin

- src/common/github-flavored-markdown.js
- src/domain/constants.js
- src/plugins/anavis/anavis-editor.js
- src/plugins/audio/audio-editor.js
- src/plugins/ear-training/ear-training-editor.js
- src/plugins/image-tiles/image-tile-editor.js
- src/plugins/image/image-editor.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/pdf-viewer/pdf-viewer-editor.js
- src/plugins/video/video-editor.js
- src/services/storage-service.js
- src/utils/storage-utils.js
Closes https://educandu.atlassian.net/browse/EDU-711
> EDU-711 Reduce internal source url prefix

- src/components/pages/tests.js
- src/components/timeline.js
Closes https://educandu.atlassian.net/browse/EDU-706
> EDU-706-Fix-timeline-on-test-page

- src/components/media-player-track.js
- src/components/media-player.js
- src/components/pages/tests.js
- src/ui/hooks.js
Closes https://educandu.atlassian.net/browse/EDU-700
> EDU-700-Reflect-props-in-media-player

- src/components/item-panel.js
- src/components/pages/tests.js
- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/plugins/multitrack-media/multitrack-media-info.js
- src/plugins/multitrack-media/multitrack-media-utils.js
- src/plugins/multitrack-media/multitrack-media.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-722
> EDU-722 Set up multitrack media editor with placeholder sections

- src/components/secondary-track-editor.js
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-721
> EDU-721 Create secondary-track-editor component

- src/plugins/annotation/annotation-display.js
- src/plugins/annotation/annotation-editor.js
- src/plugins/annotation/annotation-info.js
Closes https://educandu.atlassian.net/browse/EDU-732
> EDU-732 Make annotation titles support markdown

- src/components/consent-drawer.js
Closes https://educandu.atlassian.net/browse/EDU-734
> EDU-734 Do not block keyboard if no consent text is configured

- src/components/section-display.js
- src/components/section-display.less
Closes https://educandu.atlassian.net/browse/EDU-731
> EDU-731 Show solid red border around invalid sections

- src/components/icons/media-player/backward-icon.js
- src/components/icons/media-player/fast-backward-icon.js
- src/components/icons/media-player/fast-forward-icon.js
- src/components/icons/media-player/forward-icon.js
- src/components/media-player-controls.js
- src/components/media-player-controls.less
- src/components/media-player-track.js
- src/components/media-player.js
- src/components/pages/tests.js
- src/components/secondary-track-editor.js
- src/components/track-mixer.js
- src/components/track-mixer.less
- src/components/track-mixer.yml
- src/components/volume-slider.js
- src/components/volume-slider.less
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/resources/resources.json
- src/styles/main.less
- src/utils/media-utils.js
- src/utils/media-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-723
> EDU-723 Create track mixer

- package.json
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-735
> EDU-735 Update dev-tools to v3.0.1

- src/plugins/interactive-media/interactive-media-info.js
- src/plugins/multitrack-media/multitrack-media-icon.js
- src/plugins/multitrack-media/multitrack-media.yml
- src/plugins/plugin-registry.js
- src/resources/resources.json
- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-726
(Also switched around the table and interactive-media plugins, so that we'll have all the fancy media plugins at the end)
> EDU-726 Include multitrack-media plugin in list

- src/components/plugin-selector-dialog.js
- src/plugins/multitrack-media/multitrack-media-icon.js
Closes https://educandu.atlassian.net/browse/EDU-737
> EDU-737 Add plugin icon

- migrations/educandu-2022-08-16-01-add-verified-flag-to-documents.js
- src/components/document-metadata-modal.js
- src/components/document-metadata-modal.less
- src/components/document-metadata-modal.yml
- src/components/edit-control-panel.js
- src/components/edit-control-panel.less
- src/components/pages/doc.js
- src/components/pages/doc.yml
- src/domain/permissions.js
- src/domain/permissions.spec.js
- src/domain/schemas/document-schemas.js
- src/resources/resources.json
- src/services/document-service.js
- src/services/document-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-749
> EDU-749 Mark documents as verified

- src/components/files-upload-overview.js
- src/components/files-upload-overview.less
- src/components/files-upload-overview.yml
- src/resources/resources.json
- src/utils/storage-utils.js
Closes https://educandu.atlassian.net/browse/EDU-754
For now I've placed the checkbox on the right of the upload button. Placing it on top breaks screen content for the case when one file is uploaded and the preview is shown (there's not enough space). We'll improve this with the upcoming refactoring.
> EDU-754 Re-introduce possibility to opt out image optimization upon upload

- src/components/default-page-header.js
- test-app/src/bundles/page-header.js
Closes https://educandu.atlassian.net/browse/EDU-755
> EDU-755 Correct condition for showing helpPage menu item

- src/components/resource-picker/files-upload-screen.js
- src/components/resource-picker/files-upload-screen.less
Closes https://educandu.atlassian.net/browse/EDU-757
> EDU-757 Enable uploaded resource selection

- src/components/copyright-notice.less
Closes https://educandu.atlassian.net/browse/EDU-752
> EDU-752 Center copyright notice

- migrations/educandu-2022-08-24-01-add-allowedOpenContribution-field-to-documents.js
- src/components/document-metadata-modal.js
- src/components/document-metadata-modal.yml
- src/components/edit-control-panel.js
- src/components/pages/doc.js
- src/domain/constants.js
- src/domain/permissions.js
- src/domain/permissions.spec.js
- src/domain/schemas/document-schemas.js
- src/resources/resources.json
- src/services/document-service.js
- src/services/document-service.spec.js
- src/ui/default-prop-types.js
- src/utils/doc-utils.js
- src/utils/doc-utils.spec.js
- src/utils/room-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-750
> EDU-750 Restrict document editing

- src/plugins/video/video-editor.js
Closes https://educandu.atlassian.net/browse/EDU-739
> EDU-739 Allow poster images for youtube videos

- src/components/markdown-help.less
Closes https://educandu.atlassian.net/browse/EDU-762
> EDU-762 Fix markdown help content overflow

- src/plugins/quick-tester/quick-tester-info.js
- src/plugins/quick-tester/quick-tester-info.spec.js
- src/services/section-helper.js
Closes https://educandu.atlassian.net/browse/EDU-758
> EDU-758 Fix copy/pasting quick tester section content

- migrations/educandu-2022-08-29-01-create-comments-collection.js
- src/domain/permissions.js
- src/domain/permissions.spec.js
- src/domain/schemas/comment-schemas.js
- src/domain/validation-constants.js
- src/server/comment-controller.js
- src/server/comment-controller.spec.js
- src/server/controller-factory.js
- src/server/room-controller.js
- src/services/client-data-mapping-service.js
- src/services/client-data-mapping-service.spec.js
- src/services/comment-service.js
- src/services/comment-service.spec.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/stores/collection-specs/comments.js
- src/stores/comment-store.js
- src/stores/database.js
Closes https://educandu.atlassian.net/browse/EDU-764
> EDU-764 Create backend for comments

- src/api-clients/comment-api-client.js
- src/components/control-panel.js
- src/components/control-panel.less
- src/components/edit-control-panel.js
- src/components/history-control-panel.js
- src/components/news-tab.less
- src/components/pages/doc.js
- src/components/pages/doc.less
- src/components/pages/doc.yml
- src/components/profile-header.less
- src/domain/constants.js
- src/resources/resources.json
- src/server/comment-controller.js
- src/server/comment-controller.spec.js
- src/styles/main.less
Closes https://educandu.atlassian.net/browse/EDU-763
**Closed:**
**Open:**
> EDU-763 Add comments view to document page

- src/components/control-panel.less
- src/components/pages/doc.js
- src/components/pages/doc.less
Closes https://educandu.atlassian.net/browse/EDU-773
> EDU-773 Fix control panel width issue

- src/components/pages/room.js
- src/services/client-data-mapping-service.js
- src/services/client-data-mapping-service.spec.js
- src/ui/default-prop-types.js
Closes https://educandu.atlassian.net/browse/EDU-772
> EDU-772 Drop the key property from mapped users

- src/components/media-player/multitrack-media-player.js
- src/components/media-player/multitrack-media-player.less
- src/components/media-player/multitrack-media-player.yml
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/plugins/multitrack-media/multitrack-media.less
- src/plugins/multitrack-media/multitrack-media.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-774
> EDU-774 Fix prop validation and show nice error messages

- src/api-clients/comment-api-client.js
- src/components/pages/doc.js
- src/components/pages/doc.less
- src/components/pages/doc.yml
- src/resources/resources.json
- src/services/client-data-mapping-service.js
- src/services/client-data-mapping-service.spec.js
- src/services/comment-service.js
- src/utils/doc-utils.js
- src/utils/doc-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-765
**Desktop:**
**Mobile:**
> EDU-765 Display comments on doc page

- test-app/src/index.js
Closes https://educandu.atlassian.net/browse/EDU-775
> EDU-775 Reorder plugins for plugin selector dialog

- src/components/comments-panel.js
- src/components/comments-panel.less
- src/components/comments-panel.yml
- src/components/input-and-preview.less
- src/components/markdown-input.js
- src/components/markdown-input.less
- src/components/pages/doc.js
- src/components/pages/doc.less
- src/components/pdf-document.js
- src/resources/resources.json
- src/styles/main.less
- src/ui/default-prop-types.js
- src/utils/comment-utils.js
- src/utils/comment-utils.spec.js
- src/utils/doc-utils.js
- src/utils/doc-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-766
> EDU-766 Support writing comments

- src/api-clients/comment-api-client.js
- src/components/comments-panel.js
- src/components/comments-panel.less
- src/components/comments-panel.yml
- src/components/confirmation-dialogs.js
- src/components/confirmation-dialogs.yml
- src/components/pages/doc.js
- src/domain/schemas/comment-schemas.js
- src/resources/resources.json
- src/server/comment-controller.js
- src/server/comment-controller.spec.js
- src/services/comment-service.js
- src/services/comment-service.spec.js
- src/stores/comment-store.js
Closes https://educandu.atlassian.net/browse/EDU-767
> EDU-767 Support maintaining comments

- src/components/document-selector.js
- src/components/markdown.js
- src/plugins/catalog/catalog-display.js
- src/plugins/catalog/catalog-editor.js
- src/plugins/catalog/catalog-item-editor.js
- src/plugins/catalog/catalog-utils.js
- src/plugins/catalog/catalog.less
- src/plugins/catalog/catalog.yml
- src/plugins/interactive-media/interactive-media-display.js
- src/plugins/quick-tester/quick-tester-display.js
- src/resources/resources.json
- src/styles/utilities.less
Closes https://educandu.atlassian.net/browse/EDU-769
> EDU-769 Expand catalog features

- src/components/media-player/track-mixer.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/utils/media-utils.js
Closes https://educandu.atlassian.net/browse/EDU-783
> EDU-783 Fix tracks state reset on volume change

- src/utils/room-utils.js
- src/utils/room-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-779
> EDU-779 Bring back the add document button in room

- src/components/pages/doc.less
Closes https://educandu.atlassian.net/browse/EDU-780
> EDU-780 Attempt to fix hard to reproduce issue with floating panel

- src/components/favorite-star.less
- src/components/icons/general/allowed-open-contribution-content-icon.js
- src/components/icons/general/allowed-open-contribution-metadata-and-content-icon.js
- src/components/icons/general/allowed-open-contribution-none-icon.js
- src/components/pages/doc.js
- src/components/pages/doc.less
- src/components/pages/docs.js
- src/components/pages/docs.less
- src/components/pages/docs.yml
- src/resources/common.yml
- src/resources/resources.json
- src/stores/document-store.js
- src/styles/utilities.less
Closes https://educandu.atlassian.net/browse/EDU-777
> EDU-777 Indicate document configuration

- src/components/media-player/media-duration-cache.js
- src/components/media-player/track-mixer.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/interactive-media/interactive-media.less
- src/plugins/media-slideshow/media-slideshow-editor.js
- src/plugins/media-slideshow/media-slideshow.less
Closes https://educandu.atlassian.net/browse/EDU-786
> EDU-786 Fix showing percentages instead of timecodes in timelines

- src/components/resource-picker/storage-location.js
- src/components/resource-picker/storage-location.less
- src/components/resource-picker/utilities.less
- src/plugins/interactive-media/interactive-media.less
Closes https://educandu.atlassian.net/browse/EDU-781
**Also corrected this:**
⬇️
> EDU-781 Fix resource picker UI on mobile

- src/components/pages/login.js
- src/components/pages/login.less
- src/components/pages/login.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-792
Clean clean clean!
> EDU-792 Remove no longer needed login hint

- migrations/educandu-2022-09-09-01-add-documents-list-to-rooms.js
- src/api-clients/room-api-client.js
- src/components/pages/room.js
- src/domain/schemas/room-schemas.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/document-service.js
- src/services/document-service.spec.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/stores/room-store.js
- src/test-helper.js
Closes https://educandu.atlassian.net/browse/EDU-793
> EDU-793 Transform rooms domain model to keep list of included documents

- src/components/search-bar.js
- src/components/search-bar.yml
- src/resources/common.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-798
> EDU-798 Make search bar placeholder text into local resource

- src/services/document-service.js
- src/services/task-processor.js
- src/services/task-processor.spec.js
Closes https://educandu.atlassian.net/browse/EDU-803
> EDU-803 Avoid retrying failed tasks that will never succeed

- src/components/pages/room.less
- src/plugins/media-slideshow/media-slideshow-icon.js
Closes https://educandu.atlassian.net/browse/EDU-785
> EDU-785 Change media-slideshow-icon

- migrations/educandu-2022-09-13-01-rename-plan-to-planId-in-user-storage.js
- src/components/pages/users.js
- src/domain/schemas/user-schemas.js
- src/server/user-controller.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
- src/services/user-service.js
- src/services/user-service.spec.js
- src/stores/user-store.js
- src/test-helper.js
Closes https://educandu.atlassian.net/browse/EDU-787
> EDU-787 Rename storage.plan in user data model

- src/components/admin/settings-tab.js
- src/components/admin/settings-tab.less
- src/components/admin/settings-tab.yml
- src/components/admin/technical-maintenance-tab.js
- src/components/admin/technical-maintenance-tab.less
- src/components/admin/technical-maintenance-tab.yml
- src/components/files-list-viewer.js
- src/components/pages/admin.js
- src/components/pages/admin.yml
- src/resources/common.yml
- src/resources/resources.json
- src/styles/main.less
- src/ui/mime-type-helper.yml
Closes https://educandu.atlassian.net/browse/EDU-801
> EDU-801 Make tab out of technical maintenance tasks

- migrations/educandu-2022-09-12-01-add-type-to-media-slideshow-chapters.js
- src/plugins/catalog/catalog.yml
- src/plugins/image/image.yml
- src/plugins/media-slideshow/constants.js
- src/plugins/media-slideshow/media-slideshow-display.js
- src/plugins/media-slideshow/media-slideshow-editor.js
- src/plugins/media-slideshow/media-slideshow-info.js
- src/plugins/media-slideshow/media-slideshow-info.spec.js
- src/plugins/media-slideshow/media-slideshow.less
- src/plugins/media-slideshow/media-slideshow.yml
- src/plugins/table/table.yml
- src/resources/common.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-804
> EDU-804 Expand media slideshow

- src/api-clients/room-api-client.js
- src/components/pages/room.js
- src/components/pages/room.less
- src/domain/schemas/room-schemas.js
- src/domain/schemas/room-schemas.spec.js
- src/server/room-controller.js
- src/server/room-controller.spec.js
- src/services/document-service.js
- src/services/room-service.js
- src/services/room-service.spec.js
- src/services/user-service.spec.js
- src/stores/document-store.js
- src/stores/room-store.js
- src/utils/array-utils.js
- src/utils/array-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-794
> EDU-794 Reorder room documents

- src/plugins/image/image-editor.js
Closes https://educandu.atlassian.net/browse/EDU-809
> EDU-809 Fix state change on reveal orientation value change

- src/api-clients/storage-api-client.js
- src/components/debounced-input.js
- src/components/resource-picker/storage-location-screens.js
- src/components/resource-picker/storage-location.js
- src/domain/schemas/storage-schemas.js
- src/server/storage-controller.js
- src/server/storage-controller.spec.js
- src/services/storage-service.js
- src/services/storage-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-797
> EDU-797 Search human readable directory names

- src/plugins/multitrack-media/multitrack-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-808
> EDU-808 Start secondary tracks with number #2

- migrations/educandu-2022-09-20-01-rework-effects-in-image-plugin.js
- src/plugins/image/image-display.js
- src/plugins/image/image-editor.js
- src/plugins/image/image-info.js
- src/plugins/image/image-info.spec.js
- src/plugins/image/image-utils.js
- src/services/document-service.spec.js
Closes https://educandu.atlassian.net/browse/EDU-790
> EDU-790 Rework effect in image plugin

- src/components/media-player/chapter-selector.js
- src/components/media-player/chapter-selector.less
- src/components/media-player/timeline.js
- src/components/media-player/timeline.less
Closes https://educandu.atlassian.net/browse/EDU-812
**Version 1**
**Version 2**
> EDU-812 Expand timeline component for color support

- src/components/debounced-input.js
- src/components/pages/tests.js
- src/ui/hooks.js
Closes https://educandu.atlassian.net/browse/EDU-811
> EDU-811 Add flush function to debounced callback hook

- src/plugins/ear-training/ear-training-display.js
- src/plugins/ear-training/ear-training.less
Closes https://educandu.atlassian.net/browse/EDU-806
This solution doesn't adjust the answer image's size to fit the question image size. We can leave that to the author, IMO.
> EDU-806 Use original image sizes in ear training plugin

- migrations/educandu-2022-09-22-01-reset-allowedOpenContribution-on-private-documents.js
- src/components/document-metadata-modal.js
- src/components/pages/doc.js
Closes https://educandu.atlassian.net/browse/EDU-819
> EDU-819 Remove open contribution logic from private documents

- src/stores/document-store.js
Closes https://educandu.atlassian.net/browse/EDU-807
> EDU-807 Exclude archived documents from DB query

- migrations/educandu-2022-09-22-02-fix-invalid-slugs.js
- src/services/document-service.js
Closes https://educandu.atlassian.net/browse/EDU-820
> EDU-820 Migrate invalid slugs

- src/server/document-controller.js
- src/server/document-controller.spec.js
Closes https://educandu.atlassian.net/browse/EDU-821
> EDU-821 Fix 500 error on document page

- src/components/media-player/timeline.less
- src/plugins/media-analysis/media-analysis-display.js
- src/plugins/media-analysis/media-analysis.less
Closes https://educandu.atlassian.net/browse/EDU-815
**PR https://github.com/educandu/educandu/pull/635 needs to be merged first**
> EDU-815 Add segments to media analysis display

- src/components/document-metadata-modal-utils.js
- src/components/document-metadata-modal.js
Closes https://educandu.atlassian.net/browse/EDU-827
> EDU-827 Fix hiding allowedOpenContribution

- src/components/confirmation-dialogs.yml
- src/components/pages/room.js
- src/components/pages/room.yml
- src/resources/resources.json
Closes https://educandu.atlassian.net/browse/EDU-825
> EDU-825 Improve wording when leaving a room

- src/components/document-metadata-modal.js
- src/domain/schemas/document-schemas.js
- src/server/document-controller.js
Closes https://educandu.atlassian.net/browse/EDU-818
> EDU-818 Always use default quality metadata unless updating

- src/server/document-controller.js
- src/server/document-controller.spec.js
- src/utils/doc-utils.js
- src/utils/doc-utils.spec.js
Closes https://educandu.atlassian.net/browse/EDU-826
> EDU-826 Correct logic for determining if doc editing is allowed and redirect if not allowed

- src/components/icons/media-player/solo-icon.js
- src/components/media-player/media-player-track-mixer.js
- src/components/media-player/media-player-track-mixer.less
- src/components/media-player/media-volume-slider.js
Closes https://educandu.atlassian.net/browse/EDU-830
> EDU-830 Restore volume with unmutting and support solo

- src/components/media-player/main-track-editor.js
- src/components/media-player/media-player-track-group.js
- src/components/media-player/media-player-track.js
- src/components/media-player/preloading-media-player-track.js
- src/domain/constants.js
- src/plugins/interactive-media/interactive-media-editor.js
- src/plugins/media-analysis/media-analysis-display.js
- src/plugins/media-analysis/media-analysis-editor.js
- src/plugins/media-slideshow/media-slideshow-editor.js
- src/plugins/multitrack-media/multitrack-media-display.js
- src/plugins/multitrack-media/multitrack-media-editor.js
- src/ui/hooks.js
- src/utils/media-utils.js
Closes https://educandu.atlassian.net/browse/EDU-831
> EDU-831 Preload media tracks coming from the internal CDN

- package.json
- src/components/media-player/media-player-track-group.js
- src/components/media-player/media-player-track.js
- src/components/pages/tests.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-843
> EDU-843 Fix multitrack issues

- src/components/music-xml-document.js
Closes https://educandu.atlassian.net/browse/EDU-858
> EDU-858 Attempt to fix CORS issue in private storage

- .gitignore
- package.json
- src/components/item-panel.js
- src/plugins/media-analysis/media-analysis-editor.js
- src/plugins/media-analysis/media-analysis-utils.js
- src/plugins/media-analysis/media-analysis-utils.spec.js
- src/plugins/media-analysis/media-analysis.less
- src/plugins/media-analysis/media-analysis.yml
- src/resources/resources.json
- src/utils/csv-utils.js
- src/utils/csv-utils.spec.js
- yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-840
> EDU-840 Import CSV into media analysis plugin

- src/plugins/multitrack-media/multitrack-media-editor.js
Closes https://educandu.atlassian.net/browse/EDU-866
> EDU-866 Fix state discrepancy on adding new track in multitrack-media plugin

- src/plugins/media-analysis/media-analysis-display.js
Closes https://educandu.atlassian.net/browse/EDU-868
> EDU-868 Fix volume reset on text toggled in media-analysis-display

- src/plugins/media-slideshow/media-slideshow.less
Closes https://educandu.atlassian.net/browse/EDU-864
> EDU-864 Make text content in media slideshows scroll if too big

- src/components/media-player/media-player-track-group.js
Closes https://educandu.atlassian.net/browse/EDU-865
> EDU-868 Keep pre-determined media duration on reset

- src/components/media-player/preloading-media-player-track.js
Closes https://educandu.atlassian.net/browse/EDU-873
> EDU-873 Send credentials when fetching media files from internal URLs
